
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Abilita` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Abilita
 * 
 */
export type AbilitaModel = runtime.Types.Result.DefaultSelection<Prisma.$AbilitaPayload>

export type AggregateAbilita = {
  _count: AbilitaCountAggregateOutputType | null
  _avg: AbilitaAvgAggregateOutputType | null
  _sum: AbilitaSumAggregateOutputType | null
  _min: AbilitaMinAggregateOutputType | null
  _max: AbilitaMaxAggregateOutputType | null
}

export type AbilitaAvgAggregateOutputType = {
  Id: number | null
}

export type AbilitaSumAggregateOutputType = {
  Id: number | null
}

export type AbilitaMinAggregateOutputType = {
  Id: number | null
  NomeAbilità: string | null
  Descrizione: string | null
  Immagine: string | null
}

export type AbilitaMaxAggregateOutputType = {
  Id: number | null
  NomeAbilità: string | null
  Descrizione: string | null
  Immagine: string | null
}

export type AbilitaCountAggregateOutputType = {
  Id: number
  NomeAbilità: number
  Descrizione: number
  Immagine: number
  _all: number
}


export type AbilitaAvgAggregateInputType = {
  Id?: true
}

export type AbilitaSumAggregateInputType = {
  Id?: true
}

export type AbilitaMinAggregateInputType = {
  Id?: true
  NomeAbilità?: true
  Descrizione?: true
  Immagine?: true
}

export type AbilitaMaxAggregateInputType = {
  Id?: true
  NomeAbilità?: true
  Descrizione?: true
  Immagine?: true
}

export type AbilitaCountAggregateInputType = {
  Id?: true
  NomeAbilità?: true
  Descrizione?: true
  Immagine?: true
  _all?: true
}

export type AbilitaAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Abilita to aggregate.
   */
  where?: Prisma.AbilitaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Abilitas to fetch.
   */
  orderBy?: Prisma.AbilitaOrderByWithRelationInput | Prisma.AbilitaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AbilitaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Abilitas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Abilitas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Abilitas
  **/
  _count?: true | AbilitaCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AbilitaAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AbilitaSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AbilitaMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AbilitaMaxAggregateInputType
}

export type GetAbilitaAggregateType<T extends AbilitaAggregateArgs> = {
      [P in keyof T & keyof AggregateAbilita]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAbilita[P]>
    : Prisma.GetScalarType<T[P], AggregateAbilita[P]>
}




export type AbilitaGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AbilitaWhereInput
  orderBy?: Prisma.AbilitaOrderByWithAggregationInput | Prisma.AbilitaOrderByWithAggregationInput[]
  by: Prisma.AbilitaScalarFieldEnum[] | Prisma.AbilitaScalarFieldEnum
  having?: Prisma.AbilitaScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AbilitaCountAggregateInputType | true
  _avg?: AbilitaAvgAggregateInputType
  _sum?: AbilitaSumAggregateInputType
  _min?: AbilitaMinAggregateInputType
  _max?: AbilitaMaxAggregateInputType
}

export type AbilitaGroupByOutputType = {
  Id: number
  NomeAbilità: string
  Descrizione: string
  Immagine: string
  _count: AbilitaCountAggregateOutputType | null
  _avg: AbilitaAvgAggregateOutputType | null
  _sum: AbilitaSumAggregateOutputType | null
  _min: AbilitaMinAggregateOutputType | null
  _max: AbilitaMaxAggregateOutputType | null
}

export type GetAbilitaGroupByPayload<T extends AbilitaGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AbilitaGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AbilitaGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AbilitaGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AbilitaGroupByOutputType[P]>
      }
    >
  >



export type AbilitaWhereInput = {
  AND?: Prisma.AbilitaWhereInput | Prisma.AbilitaWhereInput[]
  OR?: Prisma.AbilitaWhereInput[]
  NOT?: Prisma.AbilitaWhereInput | Prisma.AbilitaWhereInput[]
  Id?: Prisma.IntFilter<"Abilita"> | number
  NomeAbilità?: Prisma.StringFilter<"Abilita"> | string
  Descrizione?: Prisma.StringFilter<"Abilita"> | string
  Immagine?: Prisma.StringFilter<"Abilita"> | string
  KitAb?: Prisma.XOR<Prisma.Kit_AbilitaNullableScalarRelationFilter, Prisma.Kit_AbilitaWhereInput> | null
}

export type AbilitaOrderByWithRelationInput = {
  Id?: Prisma.SortOrder
  NomeAbilità?: Prisma.SortOrder
  Descrizione?: Prisma.SortOrder
  Immagine?: Prisma.SortOrder
  KitAb?: Prisma.Kit_AbilitaOrderByWithRelationInput
}

export type AbilitaWhereUniqueInput = Prisma.AtLeast<{
  Id?: number
  NomeAbilità?: string
  AND?: Prisma.AbilitaWhereInput | Prisma.AbilitaWhereInput[]
  OR?: Prisma.AbilitaWhereInput[]
  NOT?: Prisma.AbilitaWhereInput | Prisma.AbilitaWhereInput[]
  Descrizione?: Prisma.StringFilter<"Abilita"> | string
  Immagine?: Prisma.StringFilter<"Abilita"> | string
  KitAb?: Prisma.XOR<Prisma.Kit_AbilitaNullableScalarRelationFilter, Prisma.Kit_AbilitaWhereInput> | null
}, "Id" | "NomeAbilità">

export type AbilitaOrderByWithAggregationInput = {
  Id?: Prisma.SortOrder
  NomeAbilità?: Prisma.SortOrder
  Descrizione?: Prisma.SortOrder
  Immagine?: Prisma.SortOrder
  _count?: Prisma.AbilitaCountOrderByAggregateInput
  _avg?: Prisma.AbilitaAvgOrderByAggregateInput
  _max?: Prisma.AbilitaMaxOrderByAggregateInput
  _min?: Prisma.AbilitaMinOrderByAggregateInput
  _sum?: Prisma.AbilitaSumOrderByAggregateInput
}

export type AbilitaScalarWhereWithAggregatesInput = {
  AND?: Prisma.AbilitaScalarWhereWithAggregatesInput | Prisma.AbilitaScalarWhereWithAggregatesInput[]
  OR?: Prisma.AbilitaScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AbilitaScalarWhereWithAggregatesInput | Prisma.AbilitaScalarWhereWithAggregatesInput[]
  Id?: Prisma.IntWithAggregatesFilter<"Abilita"> | number
  NomeAbilità?: Prisma.StringWithAggregatesFilter<"Abilita"> | string
  Descrizione?: Prisma.StringWithAggregatesFilter<"Abilita"> | string
  Immagine?: Prisma.StringWithAggregatesFilter<"Abilita"> | string
}

export type AbilitaCreateInput = {
  NomeAbilità: string
  Descrizione: string
  Immagine: string
  KitAb?: Prisma.Kit_AbilitaCreateNestedOneWithoutAbilitaInput
}

export type AbilitaUncheckedCreateInput = {
  Id?: number
  NomeAbilità: string
  Descrizione: string
  Immagine: string
  KitAb?: Prisma.Kit_AbilitaUncheckedCreateNestedOneWithoutAbilitaInput
}

export type AbilitaUpdateInput = {
  NomeAbilità?: Prisma.StringFieldUpdateOperationsInput | string
  Descrizione?: Prisma.StringFieldUpdateOperationsInput | string
  Immagine?: Prisma.StringFieldUpdateOperationsInput | string
  KitAb?: Prisma.Kit_AbilitaUpdateOneWithoutAbilitaNestedInput
}

export type AbilitaUncheckedUpdateInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
  NomeAbilità?: Prisma.StringFieldUpdateOperationsInput | string
  Descrizione?: Prisma.StringFieldUpdateOperationsInput | string
  Immagine?: Prisma.StringFieldUpdateOperationsInput | string
  KitAb?: Prisma.Kit_AbilitaUncheckedUpdateOneWithoutAbilitaNestedInput
}

export type AbilitaCreateManyInput = {
  Id?: number
  NomeAbilità: string
  Descrizione: string
  Immagine: string
}

export type AbilitaUpdateManyMutationInput = {
  NomeAbilità?: Prisma.StringFieldUpdateOperationsInput | string
  Descrizione?: Prisma.StringFieldUpdateOperationsInput | string
  Immagine?: Prisma.StringFieldUpdateOperationsInput | string
}

export type AbilitaUncheckedUpdateManyInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
  NomeAbilità?: Prisma.StringFieldUpdateOperationsInput | string
  Descrizione?: Prisma.StringFieldUpdateOperationsInput | string
  Immagine?: Prisma.StringFieldUpdateOperationsInput | string
}

export type AbilitaCountOrderByAggregateInput = {
  Id?: Prisma.SortOrder
  NomeAbilità?: Prisma.SortOrder
  Descrizione?: Prisma.SortOrder
  Immagine?: Prisma.SortOrder
}

export type AbilitaAvgOrderByAggregateInput = {
  Id?: Prisma.SortOrder
}

export type AbilitaMaxOrderByAggregateInput = {
  Id?: Prisma.SortOrder
  NomeAbilità?: Prisma.SortOrder
  Descrizione?: Prisma.SortOrder
  Immagine?: Prisma.SortOrder
}

export type AbilitaMinOrderByAggregateInput = {
  Id?: Prisma.SortOrder
  NomeAbilità?: Prisma.SortOrder
  Descrizione?: Prisma.SortOrder
  Immagine?: Prisma.SortOrder
}

export type AbilitaSumOrderByAggregateInput = {
  Id?: Prisma.SortOrder
}

export type AbilitaScalarRelationFilter = {
  is?: Prisma.AbilitaWhereInput
  isNot?: Prisma.AbilitaWhereInput
}

export type AbilitaCreateNestedOneWithoutKitAbInput = {
  create?: Prisma.XOR<Prisma.AbilitaCreateWithoutKitAbInput, Prisma.AbilitaUncheckedCreateWithoutKitAbInput>
  connectOrCreate?: Prisma.AbilitaCreateOrConnectWithoutKitAbInput
  connect?: Prisma.AbilitaWhereUniqueInput
}

export type AbilitaUpdateOneRequiredWithoutKitAbNestedInput = {
  create?: Prisma.XOR<Prisma.AbilitaCreateWithoutKitAbInput, Prisma.AbilitaUncheckedCreateWithoutKitAbInput>
  connectOrCreate?: Prisma.AbilitaCreateOrConnectWithoutKitAbInput
  upsert?: Prisma.AbilitaUpsertWithoutKitAbInput
  connect?: Prisma.AbilitaWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AbilitaUpdateToOneWithWhereWithoutKitAbInput, Prisma.AbilitaUpdateWithoutKitAbInput>, Prisma.AbilitaUncheckedUpdateWithoutKitAbInput>
}

export type AbilitaCreateWithoutKitAbInput = {
  NomeAbilità: string
  Descrizione: string
  Immagine: string
}

export type AbilitaUncheckedCreateWithoutKitAbInput = {
  Id?: number
  NomeAbilità: string
  Descrizione: string
  Immagine: string
}

export type AbilitaCreateOrConnectWithoutKitAbInput = {
  where: Prisma.AbilitaWhereUniqueInput
  create: Prisma.XOR<Prisma.AbilitaCreateWithoutKitAbInput, Prisma.AbilitaUncheckedCreateWithoutKitAbInput>
}

export type AbilitaUpsertWithoutKitAbInput = {
  update: Prisma.XOR<Prisma.AbilitaUpdateWithoutKitAbInput, Prisma.AbilitaUncheckedUpdateWithoutKitAbInput>
  create: Prisma.XOR<Prisma.AbilitaCreateWithoutKitAbInput, Prisma.AbilitaUncheckedCreateWithoutKitAbInput>
  where?: Prisma.AbilitaWhereInput
}

export type AbilitaUpdateToOneWithWhereWithoutKitAbInput = {
  where?: Prisma.AbilitaWhereInput
  data: Prisma.XOR<Prisma.AbilitaUpdateWithoutKitAbInput, Prisma.AbilitaUncheckedUpdateWithoutKitAbInput>
}

export type AbilitaUpdateWithoutKitAbInput = {
  NomeAbilità?: Prisma.StringFieldUpdateOperationsInput | string
  Descrizione?: Prisma.StringFieldUpdateOperationsInput | string
  Immagine?: Prisma.StringFieldUpdateOperationsInput | string
}

export type AbilitaUncheckedUpdateWithoutKitAbInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
  NomeAbilità?: Prisma.StringFieldUpdateOperationsInput | string
  Descrizione?: Prisma.StringFieldUpdateOperationsInput | string
  Immagine?: Prisma.StringFieldUpdateOperationsInput | string
}



export type AbilitaSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  Id?: boolean
  NomeAbilità?: boolean
  Descrizione?: boolean
  Immagine?: boolean
  KitAb?: boolean | Prisma.Abilita$KitAbArgs<ExtArgs>
}, ExtArgs["result"]["abilita"]>

export type AbilitaSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  Id?: boolean
  NomeAbilità?: boolean
  Descrizione?: boolean
  Immagine?: boolean
}, ExtArgs["result"]["abilita"]>

export type AbilitaSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  Id?: boolean
  NomeAbilità?: boolean
  Descrizione?: boolean
  Immagine?: boolean
}, ExtArgs["result"]["abilita"]>

export type AbilitaSelectScalar = {
  Id?: boolean
  NomeAbilità?: boolean
  Descrizione?: boolean
  Immagine?: boolean
}

export type AbilitaOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"Id" | "NomeAbilità" | "Descrizione" | "Immagine", ExtArgs["result"]["abilita"]>
export type AbilitaInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  KitAb?: boolean | Prisma.Abilita$KitAbArgs<ExtArgs>
}
export type AbilitaIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type AbilitaIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $AbilitaPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Abilita"
  objects: {
    KitAb: Prisma.$Kit_AbilitaPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    Id: number
    NomeAbilità: string
    Descrizione: string
    Immagine: string
  }, ExtArgs["result"]["abilita"]>
  composites: {}
}

export type AbilitaGetPayload<S extends boolean | null | undefined | AbilitaDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AbilitaPayload, S>

export type AbilitaCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AbilitaFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AbilitaCountAggregateInputType | true
  }

export interface AbilitaDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Abilita'], meta: { name: 'Abilita' } }
  /**
   * Find zero or one Abilita that matches the filter.
   * @param {AbilitaFindUniqueArgs} args - Arguments to find a Abilita
   * @example
   * // Get one Abilita
   * const abilita = await prisma.abilita.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AbilitaFindUniqueArgs>(args: Prisma.SelectSubset<T, AbilitaFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AbilitaClient<runtime.Types.Result.GetResult<Prisma.$AbilitaPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Abilita that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AbilitaFindUniqueOrThrowArgs} args - Arguments to find a Abilita
   * @example
   * // Get one Abilita
   * const abilita = await prisma.abilita.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AbilitaFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AbilitaFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AbilitaClient<runtime.Types.Result.GetResult<Prisma.$AbilitaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Abilita that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AbilitaFindFirstArgs} args - Arguments to find a Abilita
   * @example
   * // Get one Abilita
   * const abilita = await prisma.abilita.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AbilitaFindFirstArgs>(args?: Prisma.SelectSubset<T, AbilitaFindFirstArgs<ExtArgs>>): Prisma.Prisma__AbilitaClient<runtime.Types.Result.GetResult<Prisma.$AbilitaPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Abilita that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AbilitaFindFirstOrThrowArgs} args - Arguments to find a Abilita
   * @example
   * // Get one Abilita
   * const abilita = await prisma.abilita.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AbilitaFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AbilitaFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AbilitaClient<runtime.Types.Result.GetResult<Prisma.$AbilitaPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Abilitas that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AbilitaFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Abilitas
   * const abilitas = await prisma.abilita.findMany()
   * 
   * // Get first 10 Abilitas
   * const abilitas = await prisma.abilita.findMany({ take: 10 })
   * 
   * // Only select the `Id`
   * const abilitaWithIdOnly = await prisma.abilita.findMany({ select: { Id: true } })
   * 
   */
  findMany<T extends AbilitaFindManyArgs>(args?: Prisma.SelectSubset<T, AbilitaFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AbilitaPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Abilita.
   * @param {AbilitaCreateArgs} args - Arguments to create a Abilita.
   * @example
   * // Create one Abilita
   * const Abilita = await prisma.abilita.create({
   *   data: {
   *     // ... data to create a Abilita
   *   }
   * })
   * 
   */
  create<T extends AbilitaCreateArgs>(args: Prisma.SelectSubset<T, AbilitaCreateArgs<ExtArgs>>): Prisma.Prisma__AbilitaClient<runtime.Types.Result.GetResult<Prisma.$AbilitaPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Abilitas.
   * @param {AbilitaCreateManyArgs} args - Arguments to create many Abilitas.
   * @example
   * // Create many Abilitas
   * const abilita = await prisma.abilita.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AbilitaCreateManyArgs>(args?: Prisma.SelectSubset<T, AbilitaCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Abilitas and returns the data saved in the database.
   * @param {AbilitaCreateManyAndReturnArgs} args - Arguments to create many Abilitas.
   * @example
   * // Create many Abilitas
   * const abilita = await prisma.abilita.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Abilitas and only return the `Id`
   * const abilitaWithIdOnly = await prisma.abilita.createManyAndReturn({
   *   select: { Id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AbilitaCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AbilitaCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AbilitaPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Abilita.
   * @param {AbilitaDeleteArgs} args - Arguments to delete one Abilita.
   * @example
   * // Delete one Abilita
   * const Abilita = await prisma.abilita.delete({
   *   where: {
   *     // ... filter to delete one Abilita
   *   }
   * })
   * 
   */
  delete<T extends AbilitaDeleteArgs>(args: Prisma.SelectSubset<T, AbilitaDeleteArgs<ExtArgs>>): Prisma.Prisma__AbilitaClient<runtime.Types.Result.GetResult<Prisma.$AbilitaPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Abilita.
   * @param {AbilitaUpdateArgs} args - Arguments to update one Abilita.
   * @example
   * // Update one Abilita
   * const abilita = await prisma.abilita.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AbilitaUpdateArgs>(args: Prisma.SelectSubset<T, AbilitaUpdateArgs<ExtArgs>>): Prisma.Prisma__AbilitaClient<runtime.Types.Result.GetResult<Prisma.$AbilitaPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Abilitas.
   * @param {AbilitaDeleteManyArgs} args - Arguments to filter Abilitas to delete.
   * @example
   * // Delete a few Abilitas
   * const { count } = await prisma.abilita.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AbilitaDeleteManyArgs>(args?: Prisma.SelectSubset<T, AbilitaDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Abilitas.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AbilitaUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Abilitas
   * const abilita = await prisma.abilita.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AbilitaUpdateManyArgs>(args: Prisma.SelectSubset<T, AbilitaUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Abilitas and returns the data updated in the database.
   * @param {AbilitaUpdateManyAndReturnArgs} args - Arguments to update many Abilitas.
   * @example
   * // Update many Abilitas
   * const abilita = await prisma.abilita.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Abilitas and only return the `Id`
   * const abilitaWithIdOnly = await prisma.abilita.updateManyAndReturn({
   *   select: { Id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AbilitaUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AbilitaUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AbilitaPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Abilita.
   * @param {AbilitaUpsertArgs} args - Arguments to update or create a Abilita.
   * @example
   * // Update or create a Abilita
   * const abilita = await prisma.abilita.upsert({
   *   create: {
   *     // ... data to create a Abilita
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Abilita we want to update
   *   }
   * })
   */
  upsert<T extends AbilitaUpsertArgs>(args: Prisma.SelectSubset<T, AbilitaUpsertArgs<ExtArgs>>): Prisma.Prisma__AbilitaClient<runtime.Types.Result.GetResult<Prisma.$AbilitaPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Abilitas.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AbilitaCountArgs} args - Arguments to filter Abilitas to count.
   * @example
   * // Count the number of Abilitas
   * const count = await prisma.abilita.count({
   *   where: {
   *     // ... the filter for the Abilitas we want to count
   *   }
   * })
  **/
  count<T extends AbilitaCountArgs>(
    args?: Prisma.Subset<T, AbilitaCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AbilitaCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Abilita.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AbilitaAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AbilitaAggregateArgs>(args: Prisma.Subset<T, AbilitaAggregateArgs>): Prisma.PrismaPromise<GetAbilitaAggregateType<T>>

  /**
   * Group by Abilita.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AbilitaGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AbilitaGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AbilitaGroupByArgs['orderBy'] }
      : { orderBy?: AbilitaGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AbilitaGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAbilitaGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Abilita model
 */
readonly fields: AbilitaFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Abilita.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AbilitaClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  KitAb<T extends Prisma.Abilita$KitAbArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Abilita$KitAbArgs<ExtArgs>>): Prisma.Prisma__Kit_AbilitaClient<runtime.Types.Result.GetResult<Prisma.$Kit_AbilitaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Abilita model
 */
export interface AbilitaFieldRefs {
  readonly Id: Prisma.FieldRef<"Abilita", 'Int'>
  readonly NomeAbilità: Prisma.FieldRef<"Abilita", 'String'>
  readonly Descrizione: Prisma.FieldRef<"Abilita", 'String'>
  readonly Immagine: Prisma.FieldRef<"Abilita", 'String'>
}
    

// Custom InputTypes
/**
 * Abilita findUnique
 */
export type AbilitaFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Abilita
   */
  select?: Prisma.AbilitaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Abilita
   */
  omit?: Prisma.AbilitaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AbilitaInclude<ExtArgs> | null
  /**
   * Filter, which Abilita to fetch.
   */
  where: Prisma.AbilitaWhereUniqueInput
}

/**
 * Abilita findUniqueOrThrow
 */
export type AbilitaFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Abilita
   */
  select?: Prisma.AbilitaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Abilita
   */
  omit?: Prisma.AbilitaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AbilitaInclude<ExtArgs> | null
  /**
   * Filter, which Abilita to fetch.
   */
  where: Prisma.AbilitaWhereUniqueInput
}

/**
 * Abilita findFirst
 */
export type AbilitaFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Abilita
   */
  select?: Prisma.AbilitaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Abilita
   */
  omit?: Prisma.AbilitaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AbilitaInclude<ExtArgs> | null
  /**
   * Filter, which Abilita to fetch.
   */
  where?: Prisma.AbilitaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Abilitas to fetch.
   */
  orderBy?: Prisma.AbilitaOrderByWithRelationInput | Prisma.AbilitaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Abilitas.
   */
  cursor?: Prisma.AbilitaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Abilitas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Abilitas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Abilitas.
   */
  distinct?: Prisma.AbilitaScalarFieldEnum | Prisma.AbilitaScalarFieldEnum[]
}

/**
 * Abilita findFirstOrThrow
 */
export type AbilitaFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Abilita
   */
  select?: Prisma.AbilitaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Abilita
   */
  omit?: Prisma.AbilitaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AbilitaInclude<ExtArgs> | null
  /**
   * Filter, which Abilita to fetch.
   */
  where?: Prisma.AbilitaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Abilitas to fetch.
   */
  orderBy?: Prisma.AbilitaOrderByWithRelationInput | Prisma.AbilitaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Abilitas.
   */
  cursor?: Prisma.AbilitaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Abilitas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Abilitas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Abilitas.
   */
  distinct?: Prisma.AbilitaScalarFieldEnum | Prisma.AbilitaScalarFieldEnum[]
}

/**
 * Abilita findMany
 */
export type AbilitaFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Abilita
   */
  select?: Prisma.AbilitaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Abilita
   */
  omit?: Prisma.AbilitaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AbilitaInclude<ExtArgs> | null
  /**
   * Filter, which Abilitas to fetch.
   */
  where?: Prisma.AbilitaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Abilitas to fetch.
   */
  orderBy?: Prisma.AbilitaOrderByWithRelationInput | Prisma.AbilitaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Abilitas.
   */
  cursor?: Prisma.AbilitaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Abilitas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Abilitas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Abilitas.
   */
  distinct?: Prisma.AbilitaScalarFieldEnum | Prisma.AbilitaScalarFieldEnum[]
}

/**
 * Abilita create
 */
export type AbilitaCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Abilita
   */
  select?: Prisma.AbilitaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Abilita
   */
  omit?: Prisma.AbilitaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AbilitaInclude<ExtArgs> | null
  /**
   * The data needed to create a Abilita.
   */
  data: Prisma.XOR<Prisma.AbilitaCreateInput, Prisma.AbilitaUncheckedCreateInput>
}

/**
 * Abilita createMany
 */
export type AbilitaCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Abilitas.
   */
  data: Prisma.AbilitaCreateManyInput | Prisma.AbilitaCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Abilita createManyAndReturn
 */
export type AbilitaCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Abilita
   */
  select?: Prisma.AbilitaSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Abilita
   */
  omit?: Prisma.AbilitaOmit<ExtArgs> | null
  /**
   * The data used to create many Abilitas.
   */
  data: Prisma.AbilitaCreateManyInput | Prisma.AbilitaCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Abilita update
 */
export type AbilitaUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Abilita
   */
  select?: Prisma.AbilitaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Abilita
   */
  omit?: Prisma.AbilitaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AbilitaInclude<ExtArgs> | null
  /**
   * The data needed to update a Abilita.
   */
  data: Prisma.XOR<Prisma.AbilitaUpdateInput, Prisma.AbilitaUncheckedUpdateInput>
  /**
   * Choose, which Abilita to update.
   */
  where: Prisma.AbilitaWhereUniqueInput
}

/**
 * Abilita updateMany
 */
export type AbilitaUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Abilitas.
   */
  data: Prisma.XOR<Prisma.AbilitaUpdateManyMutationInput, Prisma.AbilitaUncheckedUpdateManyInput>
  /**
   * Filter which Abilitas to update
   */
  where?: Prisma.AbilitaWhereInput
  /**
   * Limit how many Abilitas to update.
   */
  limit?: number
}

/**
 * Abilita updateManyAndReturn
 */
export type AbilitaUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Abilita
   */
  select?: Prisma.AbilitaSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Abilita
   */
  omit?: Prisma.AbilitaOmit<ExtArgs> | null
  /**
   * The data used to update Abilitas.
   */
  data: Prisma.XOR<Prisma.AbilitaUpdateManyMutationInput, Prisma.AbilitaUncheckedUpdateManyInput>
  /**
   * Filter which Abilitas to update
   */
  where?: Prisma.AbilitaWhereInput
  /**
   * Limit how many Abilitas to update.
   */
  limit?: number
}

/**
 * Abilita upsert
 */
export type AbilitaUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Abilita
   */
  select?: Prisma.AbilitaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Abilita
   */
  omit?: Prisma.AbilitaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AbilitaInclude<ExtArgs> | null
  /**
   * The filter to search for the Abilita to update in case it exists.
   */
  where: Prisma.AbilitaWhereUniqueInput
  /**
   * In case the Abilita found by the `where` argument doesn't exist, create a new Abilita with this data.
   */
  create: Prisma.XOR<Prisma.AbilitaCreateInput, Prisma.AbilitaUncheckedCreateInput>
  /**
   * In case the Abilita was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AbilitaUpdateInput, Prisma.AbilitaUncheckedUpdateInput>
}

/**
 * Abilita delete
 */
export type AbilitaDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Abilita
   */
  select?: Prisma.AbilitaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Abilita
   */
  omit?: Prisma.AbilitaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AbilitaInclude<ExtArgs> | null
  /**
   * Filter which Abilita to delete.
   */
  where: Prisma.AbilitaWhereUniqueInput
}

/**
 * Abilita deleteMany
 */
export type AbilitaDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Abilitas to delete
   */
  where?: Prisma.AbilitaWhereInput
  /**
   * Limit how many Abilitas to delete.
   */
  limit?: number
}

/**
 * Abilita.KitAb
 */
export type Abilita$KitAbArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Kit_Abilita
   */
  select?: Prisma.Kit_AbilitaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Kit_Abilita
   */
  omit?: Prisma.Kit_AbilitaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Kit_AbilitaInclude<ExtArgs> | null
  where?: Prisma.Kit_AbilitaWhereInput
}

/**
 * Abilita without action
 */
export type AbilitaDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Abilita
   */
  select?: Prisma.AbilitaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Abilita
   */
  omit?: Prisma.AbilitaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AbilitaInclude<ExtArgs> | null
}
