
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Razza` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Razza
 * 
 */
export type RazzaModel = runtime.Types.Result.DefaultSelection<Prisma.$RazzaPayload>

export type AggregateRazza = {
  _count: RazzaCountAggregateOutputType | null
  _min: RazzaMinAggregateOutputType | null
  _max: RazzaMaxAggregateOutputType | null
}

export type RazzaMinAggregateOutputType = {
  Nome: string | null
  Descrizione: string | null
}

export type RazzaMaxAggregateOutputType = {
  Nome: string | null
  Descrizione: string | null
}

export type RazzaCountAggregateOutputType = {
  Nome: number
  Descrizione: number
  _all: number
}


export type RazzaMinAggregateInputType = {
  Nome?: true
  Descrizione?: true
}

export type RazzaMaxAggregateInputType = {
  Nome?: true
  Descrizione?: true
}

export type RazzaCountAggregateInputType = {
  Nome?: true
  Descrizione?: true
  _all?: true
}

export type RazzaAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Razza to aggregate.
   */
  where?: Prisma.RazzaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Razzas to fetch.
   */
  orderBy?: Prisma.RazzaOrderByWithRelationInput | Prisma.RazzaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.RazzaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Razzas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Razzas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Razzas
  **/
  _count?: true | RazzaCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RazzaMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RazzaMaxAggregateInputType
}

export type GetRazzaAggregateType<T extends RazzaAggregateArgs> = {
      [P in keyof T & keyof AggregateRazza]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRazza[P]>
    : Prisma.GetScalarType<T[P], AggregateRazza[P]>
}




export type RazzaGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RazzaWhereInput
  orderBy?: Prisma.RazzaOrderByWithAggregationInput | Prisma.RazzaOrderByWithAggregationInput[]
  by: Prisma.RazzaScalarFieldEnum[] | Prisma.RazzaScalarFieldEnum
  having?: Prisma.RazzaScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RazzaCountAggregateInputType | true
  _min?: RazzaMinAggregateInputType
  _max?: RazzaMaxAggregateInputType
}

export type RazzaGroupByOutputType = {
  Nome: string
  Descrizione: string
  _count: RazzaCountAggregateOutputType | null
  _min: RazzaMinAggregateOutputType | null
  _max: RazzaMaxAggregateOutputType | null
}

export type GetRazzaGroupByPayload<T extends RazzaGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RazzaGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RazzaGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RazzaGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RazzaGroupByOutputType[P]>
      }
    >
  >



export type RazzaWhereInput = {
  AND?: Prisma.RazzaWhereInput | Prisma.RazzaWhereInput[]
  OR?: Prisma.RazzaWhereInput[]
  NOT?: Prisma.RazzaWhereInput | Prisma.RazzaWhereInput[]
  Nome?: Prisma.StringFilter<"Razza"> | string
  Descrizione?: Prisma.StringFilter<"Razza"> | string
  relazione?: Prisma.Campione_RazzaListRelationFilter
}

export type RazzaOrderByWithRelationInput = {
  Nome?: Prisma.SortOrder
  Descrizione?: Prisma.SortOrder
  relazione?: Prisma.Campione_RazzaOrderByRelationAggregateInput
}

export type RazzaWhereUniqueInput = Prisma.AtLeast<{
  Nome?: string
  AND?: Prisma.RazzaWhereInput | Prisma.RazzaWhereInput[]
  OR?: Prisma.RazzaWhereInput[]
  NOT?: Prisma.RazzaWhereInput | Prisma.RazzaWhereInput[]
  Descrizione?: Prisma.StringFilter<"Razza"> | string
  relazione?: Prisma.Campione_RazzaListRelationFilter
}, "Nome">

export type RazzaOrderByWithAggregationInput = {
  Nome?: Prisma.SortOrder
  Descrizione?: Prisma.SortOrder
  _count?: Prisma.RazzaCountOrderByAggregateInput
  _max?: Prisma.RazzaMaxOrderByAggregateInput
  _min?: Prisma.RazzaMinOrderByAggregateInput
}

export type RazzaScalarWhereWithAggregatesInput = {
  AND?: Prisma.RazzaScalarWhereWithAggregatesInput | Prisma.RazzaScalarWhereWithAggregatesInput[]
  OR?: Prisma.RazzaScalarWhereWithAggregatesInput[]
  NOT?: Prisma.RazzaScalarWhereWithAggregatesInput | Prisma.RazzaScalarWhereWithAggregatesInput[]
  Nome?: Prisma.StringWithAggregatesFilter<"Razza"> | string
  Descrizione?: Prisma.StringWithAggregatesFilter<"Razza"> | string
}

export type RazzaCreateInput = {
  Nome: string
  Descrizione: string
  relazione?: Prisma.Campione_RazzaCreateNestedManyWithoutRazzaInput
}

export type RazzaUncheckedCreateInput = {
  Nome: string
  Descrizione: string
  relazione?: Prisma.Campione_RazzaUncheckedCreateNestedManyWithoutRazzaInput
}

export type RazzaUpdateInput = {
  Nome?: Prisma.StringFieldUpdateOperationsInput | string
  Descrizione?: Prisma.StringFieldUpdateOperationsInput | string
  relazione?: Prisma.Campione_RazzaUpdateManyWithoutRazzaNestedInput
}

export type RazzaUncheckedUpdateInput = {
  Nome?: Prisma.StringFieldUpdateOperationsInput | string
  Descrizione?: Prisma.StringFieldUpdateOperationsInput | string
  relazione?: Prisma.Campione_RazzaUncheckedUpdateManyWithoutRazzaNestedInput
}

export type RazzaCreateManyInput = {
  Nome: string
  Descrizione: string
}

export type RazzaUpdateManyMutationInput = {
  Nome?: Prisma.StringFieldUpdateOperationsInput | string
  Descrizione?: Prisma.StringFieldUpdateOperationsInput | string
}

export type RazzaUncheckedUpdateManyInput = {
  Nome?: Prisma.StringFieldUpdateOperationsInput | string
  Descrizione?: Prisma.StringFieldUpdateOperationsInput | string
}

export type RazzaCountOrderByAggregateInput = {
  Nome?: Prisma.SortOrder
  Descrizione?: Prisma.SortOrder
}

export type RazzaMaxOrderByAggregateInput = {
  Nome?: Prisma.SortOrder
  Descrizione?: Prisma.SortOrder
}

export type RazzaMinOrderByAggregateInput = {
  Nome?: Prisma.SortOrder
  Descrizione?: Prisma.SortOrder
}

export type RazzaScalarRelationFilter = {
  is?: Prisma.RazzaWhereInput
  isNot?: Prisma.RazzaWhereInput
}

export type RazzaCreateNestedOneWithoutRelazioneInput = {
  create?: Prisma.XOR<Prisma.RazzaCreateWithoutRelazioneInput, Prisma.RazzaUncheckedCreateWithoutRelazioneInput>
  connectOrCreate?: Prisma.RazzaCreateOrConnectWithoutRelazioneInput
  connect?: Prisma.RazzaWhereUniqueInput
}

export type RazzaUpdateOneRequiredWithoutRelazioneNestedInput = {
  create?: Prisma.XOR<Prisma.RazzaCreateWithoutRelazioneInput, Prisma.RazzaUncheckedCreateWithoutRelazioneInput>
  connectOrCreate?: Prisma.RazzaCreateOrConnectWithoutRelazioneInput
  upsert?: Prisma.RazzaUpsertWithoutRelazioneInput
  connect?: Prisma.RazzaWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.RazzaUpdateToOneWithWhereWithoutRelazioneInput, Prisma.RazzaUpdateWithoutRelazioneInput>, Prisma.RazzaUncheckedUpdateWithoutRelazioneInput>
}

export type RazzaCreateWithoutRelazioneInput = {
  Nome: string
  Descrizione: string
}

export type RazzaUncheckedCreateWithoutRelazioneInput = {
  Nome: string
  Descrizione: string
}

export type RazzaCreateOrConnectWithoutRelazioneInput = {
  where: Prisma.RazzaWhereUniqueInput
  create: Prisma.XOR<Prisma.RazzaCreateWithoutRelazioneInput, Prisma.RazzaUncheckedCreateWithoutRelazioneInput>
}

export type RazzaUpsertWithoutRelazioneInput = {
  update: Prisma.XOR<Prisma.RazzaUpdateWithoutRelazioneInput, Prisma.RazzaUncheckedUpdateWithoutRelazioneInput>
  create: Prisma.XOR<Prisma.RazzaCreateWithoutRelazioneInput, Prisma.RazzaUncheckedCreateWithoutRelazioneInput>
  where?: Prisma.RazzaWhereInput
}

export type RazzaUpdateToOneWithWhereWithoutRelazioneInput = {
  where?: Prisma.RazzaWhereInput
  data: Prisma.XOR<Prisma.RazzaUpdateWithoutRelazioneInput, Prisma.RazzaUncheckedUpdateWithoutRelazioneInput>
}

export type RazzaUpdateWithoutRelazioneInput = {
  Nome?: Prisma.StringFieldUpdateOperationsInput | string
  Descrizione?: Prisma.StringFieldUpdateOperationsInput | string
}

export type RazzaUncheckedUpdateWithoutRelazioneInput = {
  Nome?: Prisma.StringFieldUpdateOperationsInput | string
  Descrizione?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type RazzaCountOutputType
 */

export type RazzaCountOutputType = {
  relazione: number
}

export type RazzaCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  relazione?: boolean | RazzaCountOutputTypeCountRelazioneArgs
}

/**
 * RazzaCountOutputType without action
 */
export type RazzaCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RazzaCountOutputType
   */
  select?: Prisma.RazzaCountOutputTypeSelect<ExtArgs> | null
}

/**
 * RazzaCountOutputType without action
 */
export type RazzaCountOutputTypeCountRelazioneArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.Campione_RazzaWhereInput
}


export type RazzaSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  Nome?: boolean
  Descrizione?: boolean
  relazione?: boolean | Prisma.Razza$relazioneArgs<ExtArgs>
  _count?: boolean | Prisma.RazzaCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["razza"]>

export type RazzaSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  Nome?: boolean
  Descrizione?: boolean
}, ExtArgs["result"]["razza"]>

export type RazzaSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  Nome?: boolean
  Descrizione?: boolean
}, ExtArgs["result"]["razza"]>

export type RazzaSelectScalar = {
  Nome?: boolean
  Descrizione?: boolean
}

export type RazzaOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"Nome" | "Descrizione", ExtArgs["result"]["razza"]>
export type RazzaInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  relazione?: boolean | Prisma.Razza$relazioneArgs<ExtArgs>
  _count?: boolean | Prisma.RazzaCountOutputTypeDefaultArgs<ExtArgs>
}
export type RazzaIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type RazzaIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $RazzaPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Razza"
  objects: {
    relazione: Prisma.$Campione_RazzaPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    Nome: string
    Descrizione: string
  }, ExtArgs["result"]["razza"]>
  composites: {}
}

export type RazzaGetPayload<S extends boolean | null | undefined | RazzaDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$RazzaPayload, S>

export type RazzaCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<RazzaFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RazzaCountAggregateInputType | true
  }

export interface RazzaDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Razza'], meta: { name: 'Razza' } }
  /**
   * Find zero or one Razza that matches the filter.
   * @param {RazzaFindUniqueArgs} args - Arguments to find a Razza
   * @example
   * // Get one Razza
   * const razza = await prisma.razza.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RazzaFindUniqueArgs>(args: Prisma.SelectSubset<T, RazzaFindUniqueArgs<ExtArgs>>): Prisma.Prisma__RazzaClient<runtime.Types.Result.GetResult<Prisma.$RazzaPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Razza that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RazzaFindUniqueOrThrowArgs} args - Arguments to find a Razza
   * @example
   * // Get one Razza
   * const razza = await prisma.razza.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RazzaFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, RazzaFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__RazzaClient<runtime.Types.Result.GetResult<Prisma.$RazzaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Razza that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RazzaFindFirstArgs} args - Arguments to find a Razza
   * @example
   * // Get one Razza
   * const razza = await prisma.razza.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RazzaFindFirstArgs>(args?: Prisma.SelectSubset<T, RazzaFindFirstArgs<ExtArgs>>): Prisma.Prisma__RazzaClient<runtime.Types.Result.GetResult<Prisma.$RazzaPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Razza that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RazzaFindFirstOrThrowArgs} args - Arguments to find a Razza
   * @example
   * // Get one Razza
   * const razza = await prisma.razza.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RazzaFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, RazzaFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__RazzaClient<runtime.Types.Result.GetResult<Prisma.$RazzaPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Razzas that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RazzaFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Razzas
   * const razzas = await prisma.razza.findMany()
   * 
   * // Get first 10 Razzas
   * const razzas = await prisma.razza.findMany({ take: 10 })
   * 
   * // Only select the `Nome`
   * const razzaWithNomeOnly = await prisma.razza.findMany({ select: { Nome: true } })
   * 
   */
  findMany<T extends RazzaFindManyArgs>(args?: Prisma.SelectSubset<T, RazzaFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RazzaPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Razza.
   * @param {RazzaCreateArgs} args - Arguments to create a Razza.
   * @example
   * // Create one Razza
   * const Razza = await prisma.razza.create({
   *   data: {
   *     // ... data to create a Razza
   *   }
   * })
   * 
   */
  create<T extends RazzaCreateArgs>(args: Prisma.SelectSubset<T, RazzaCreateArgs<ExtArgs>>): Prisma.Prisma__RazzaClient<runtime.Types.Result.GetResult<Prisma.$RazzaPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Razzas.
   * @param {RazzaCreateManyArgs} args - Arguments to create many Razzas.
   * @example
   * // Create many Razzas
   * const razza = await prisma.razza.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends RazzaCreateManyArgs>(args?: Prisma.SelectSubset<T, RazzaCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Razzas and returns the data saved in the database.
   * @param {RazzaCreateManyAndReturnArgs} args - Arguments to create many Razzas.
   * @example
   * // Create many Razzas
   * const razza = await prisma.razza.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Razzas and only return the `Nome`
   * const razzaWithNomeOnly = await prisma.razza.createManyAndReturn({
   *   select: { Nome: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends RazzaCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, RazzaCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RazzaPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Razza.
   * @param {RazzaDeleteArgs} args - Arguments to delete one Razza.
   * @example
   * // Delete one Razza
   * const Razza = await prisma.razza.delete({
   *   where: {
   *     // ... filter to delete one Razza
   *   }
   * })
   * 
   */
  delete<T extends RazzaDeleteArgs>(args: Prisma.SelectSubset<T, RazzaDeleteArgs<ExtArgs>>): Prisma.Prisma__RazzaClient<runtime.Types.Result.GetResult<Prisma.$RazzaPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Razza.
   * @param {RazzaUpdateArgs} args - Arguments to update one Razza.
   * @example
   * // Update one Razza
   * const razza = await prisma.razza.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends RazzaUpdateArgs>(args: Prisma.SelectSubset<T, RazzaUpdateArgs<ExtArgs>>): Prisma.Prisma__RazzaClient<runtime.Types.Result.GetResult<Prisma.$RazzaPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Razzas.
   * @param {RazzaDeleteManyArgs} args - Arguments to filter Razzas to delete.
   * @example
   * // Delete a few Razzas
   * const { count } = await prisma.razza.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends RazzaDeleteManyArgs>(args?: Prisma.SelectSubset<T, RazzaDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Razzas.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RazzaUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Razzas
   * const razza = await prisma.razza.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends RazzaUpdateManyArgs>(args: Prisma.SelectSubset<T, RazzaUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Razzas and returns the data updated in the database.
   * @param {RazzaUpdateManyAndReturnArgs} args - Arguments to update many Razzas.
   * @example
   * // Update many Razzas
   * const razza = await prisma.razza.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Razzas and only return the `Nome`
   * const razzaWithNomeOnly = await prisma.razza.updateManyAndReturn({
   *   select: { Nome: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends RazzaUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, RazzaUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RazzaPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Razza.
   * @param {RazzaUpsertArgs} args - Arguments to update or create a Razza.
   * @example
   * // Update or create a Razza
   * const razza = await prisma.razza.upsert({
   *   create: {
   *     // ... data to create a Razza
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Razza we want to update
   *   }
   * })
   */
  upsert<T extends RazzaUpsertArgs>(args: Prisma.SelectSubset<T, RazzaUpsertArgs<ExtArgs>>): Prisma.Prisma__RazzaClient<runtime.Types.Result.GetResult<Prisma.$RazzaPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Razzas.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RazzaCountArgs} args - Arguments to filter Razzas to count.
   * @example
   * // Count the number of Razzas
   * const count = await prisma.razza.count({
   *   where: {
   *     // ... the filter for the Razzas we want to count
   *   }
   * })
  **/
  count<T extends RazzaCountArgs>(
    args?: Prisma.Subset<T, RazzaCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RazzaCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Razza.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RazzaAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RazzaAggregateArgs>(args: Prisma.Subset<T, RazzaAggregateArgs>): Prisma.PrismaPromise<GetRazzaAggregateType<T>>

  /**
   * Group by Razza.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RazzaGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends RazzaGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RazzaGroupByArgs['orderBy'] }
      : { orderBy?: RazzaGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, RazzaGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRazzaGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Razza model
 */
readonly fields: RazzaFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Razza.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RazzaClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  relazione<T extends Prisma.Razza$relazioneArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Razza$relazioneArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Campione_RazzaPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Razza model
 */
export interface RazzaFieldRefs {
  readonly Nome: Prisma.FieldRef<"Razza", 'String'>
  readonly Descrizione: Prisma.FieldRef<"Razza", 'String'>
}
    

// Custom InputTypes
/**
 * Razza findUnique
 */
export type RazzaFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Razza
   */
  select?: Prisma.RazzaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Razza
   */
  omit?: Prisma.RazzaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RazzaInclude<ExtArgs> | null
  /**
   * Filter, which Razza to fetch.
   */
  where: Prisma.RazzaWhereUniqueInput
}

/**
 * Razza findUniqueOrThrow
 */
export type RazzaFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Razza
   */
  select?: Prisma.RazzaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Razza
   */
  omit?: Prisma.RazzaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RazzaInclude<ExtArgs> | null
  /**
   * Filter, which Razza to fetch.
   */
  where: Prisma.RazzaWhereUniqueInput
}

/**
 * Razza findFirst
 */
export type RazzaFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Razza
   */
  select?: Prisma.RazzaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Razza
   */
  omit?: Prisma.RazzaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RazzaInclude<ExtArgs> | null
  /**
   * Filter, which Razza to fetch.
   */
  where?: Prisma.RazzaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Razzas to fetch.
   */
  orderBy?: Prisma.RazzaOrderByWithRelationInput | Prisma.RazzaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Razzas.
   */
  cursor?: Prisma.RazzaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Razzas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Razzas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Razzas.
   */
  distinct?: Prisma.RazzaScalarFieldEnum | Prisma.RazzaScalarFieldEnum[]
}

/**
 * Razza findFirstOrThrow
 */
export type RazzaFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Razza
   */
  select?: Prisma.RazzaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Razza
   */
  omit?: Prisma.RazzaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RazzaInclude<ExtArgs> | null
  /**
   * Filter, which Razza to fetch.
   */
  where?: Prisma.RazzaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Razzas to fetch.
   */
  orderBy?: Prisma.RazzaOrderByWithRelationInput | Prisma.RazzaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Razzas.
   */
  cursor?: Prisma.RazzaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Razzas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Razzas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Razzas.
   */
  distinct?: Prisma.RazzaScalarFieldEnum | Prisma.RazzaScalarFieldEnum[]
}

/**
 * Razza findMany
 */
export type RazzaFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Razza
   */
  select?: Prisma.RazzaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Razza
   */
  omit?: Prisma.RazzaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RazzaInclude<ExtArgs> | null
  /**
   * Filter, which Razzas to fetch.
   */
  where?: Prisma.RazzaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Razzas to fetch.
   */
  orderBy?: Prisma.RazzaOrderByWithRelationInput | Prisma.RazzaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Razzas.
   */
  cursor?: Prisma.RazzaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Razzas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Razzas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Razzas.
   */
  distinct?: Prisma.RazzaScalarFieldEnum | Prisma.RazzaScalarFieldEnum[]
}

/**
 * Razza create
 */
export type RazzaCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Razza
   */
  select?: Prisma.RazzaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Razza
   */
  omit?: Prisma.RazzaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RazzaInclude<ExtArgs> | null
  /**
   * The data needed to create a Razza.
   */
  data: Prisma.XOR<Prisma.RazzaCreateInput, Prisma.RazzaUncheckedCreateInput>
}

/**
 * Razza createMany
 */
export type RazzaCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Razzas.
   */
  data: Prisma.RazzaCreateManyInput | Prisma.RazzaCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Razza createManyAndReturn
 */
export type RazzaCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Razza
   */
  select?: Prisma.RazzaSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Razza
   */
  omit?: Prisma.RazzaOmit<ExtArgs> | null
  /**
   * The data used to create many Razzas.
   */
  data: Prisma.RazzaCreateManyInput | Prisma.RazzaCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Razza update
 */
export type RazzaUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Razza
   */
  select?: Prisma.RazzaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Razza
   */
  omit?: Prisma.RazzaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RazzaInclude<ExtArgs> | null
  /**
   * The data needed to update a Razza.
   */
  data: Prisma.XOR<Prisma.RazzaUpdateInput, Prisma.RazzaUncheckedUpdateInput>
  /**
   * Choose, which Razza to update.
   */
  where: Prisma.RazzaWhereUniqueInput
}

/**
 * Razza updateMany
 */
export type RazzaUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Razzas.
   */
  data: Prisma.XOR<Prisma.RazzaUpdateManyMutationInput, Prisma.RazzaUncheckedUpdateManyInput>
  /**
   * Filter which Razzas to update
   */
  where?: Prisma.RazzaWhereInput
  /**
   * Limit how many Razzas to update.
   */
  limit?: number
}

/**
 * Razza updateManyAndReturn
 */
export type RazzaUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Razza
   */
  select?: Prisma.RazzaSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Razza
   */
  omit?: Prisma.RazzaOmit<ExtArgs> | null
  /**
   * The data used to update Razzas.
   */
  data: Prisma.XOR<Prisma.RazzaUpdateManyMutationInput, Prisma.RazzaUncheckedUpdateManyInput>
  /**
   * Filter which Razzas to update
   */
  where?: Prisma.RazzaWhereInput
  /**
   * Limit how many Razzas to update.
   */
  limit?: number
}

/**
 * Razza upsert
 */
export type RazzaUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Razza
   */
  select?: Prisma.RazzaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Razza
   */
  omit?: Prisma.RazzaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RazzaInclude<ExtArgs> | null
  /**
   * The filter to search for the Razza to update in case it exists.
   */
  where: Prisma.RazzaWhereUniqueInput
  /**
   * In case the Razza found by the `where` argument doesn't exist, create a new Razza with this data.
   */
  create: Prisma.XOR<Prisma.RazzaCreateInput, Prisma.RazzaUncheckedCreateInput>
  /**
   * In case the Razza was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.RazzaUpdateInput, Prisma.RazzaUncheckedUpdateInput>
}

/**
 * Razza delete
 */
export type RazzaDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Razza
   */
  select?: Prisma.RazzaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Razza
   */
  omit?: Prisma.RazzaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RazzaInclude<ExtArgs> | null
  /**
   * Filter which Razza to delete.
   */
  where: Prisma.RazzaWhereUniqueInput
}

/**
 * Razza deleteMany
 */
export type RazzaDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Razzas to delete
   */
  where?: Prisma.RazzaWhereInput
  /**
   * Limit how many Razzas to delete.
   */
  limit?: number
}

/**
 * Razza.relazione
 */
export type Razza$relazioneArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Campione_Razza
   */
  select?: Prisma.Campione_RazzaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Campione_Razza
   */
  omit?: Prisma.Campione_RazzaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Campione_RazzaInclude<ExtArgs> | null
  where?: Prisma.Campione_RazzaWhereInput
  orderBy?: Prisma.Campione_RazzaOrderByWithRelationInput | Prisma.Campione_RazzaOrderByWithRelationInput[]
  cursor?: Prisma.Campione_RazzaWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Campione_RazzaScalarFieldEnum | Prisma.Campione_RazzaScalarFieldEnum[]
}

/**
 * Razza without action
 */
export type RazzaDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Razza
   */
  select?: Prisma.RazzaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Razza
   */
  omit?: Prisma.RazzaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RazzaInclude<ExtArgs> | null
}
