
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Runa` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Runa
 * 
 */
export type RunaModel = runtime.Types.Result.DefaultSelection<Prisma.$RunaPayload>

export type AggregateRuna = {
  _count: RunaCountAggregateOutputType | null
  _avg: RunaAvgAggregateOutputType | null
  _sum: RunaSumAggregateOutputType | null
  _min: RunaMinAggregateOutputType | null
  _max: RunaMaxAggregateOutputType | null
}

export type RunaAvgAggregateOutputType = {
  CamminoId: number | null
  Grado: number | null
}

export type RunaSumAggregateOutputType = {
  CamminoId: number | null
  Grado: number | null
}

export type RunaMinAggregateOutputType = {
  Nome: string | null
  Descrizione: string | null
  CamminoId: number | null
  Grado: number | null
  Immagine: string | null
  Deprecata: boolean | null
}

export type RunaMaxAggregateOutputType = {
  Nome: string | null
  Descrizione: string | null
  CamminoId: number | null
  Grado: number | null
  Immagine: string | null
  Deprecata: boolean | null
}

export type RunaCountAggregateOutputType = {
  Nome: number
  Descrizione: number
  CamminoId: number
  Grado: number
  Immagine: number
  Deprecata: number
  _all: number
}


export type RunaAvgAggregateInputType = {
  CamminoId?: true
  Grado?: true
}

export type RunaSumAggregateInputType = {
  CamminoId?: true
  Grado?: true
}

export type RunaMinAggregateInputType = {
  Nome?: true
  Descrizione?: true
  CamminoId?: true
  Grado?: true
  Immagine?: true
  Deprecata?: true
}

export type RunaMaxAggregateInputType = {
  Nome?: true
  Descrizione?: true
  CamminoId?: true
  Grado?: true
  Immagine?: true
  Deprecata?: true
}

export type RunaCountAggregateInputType = {
  Nome?: true
  Descrizione?: true
  CamminoId?: true
  Grado?: true
  Immagine?: true
  Deprecata?: true
  _all?: true
}

export type RunaAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Runa to aggregate.
   */
  where?: Prisma.RunaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Runas to fetch.
   */
  orderBy?: Prisma.RunaOrderByWithRelationInput | Prisma.RunaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.RunaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Runas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Runas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Runas
  **/
  _count?: true | RunaCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: RunaAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: RunaSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RunaMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RunaMaxAggregateInputType
}

export type GetRunaAggregateType<T extends RunaAggregateArgs> = {
      [P in keyof T & keyof AggregateRuna]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRuna[P]>
    : Prisma.GetScalarType<T[P], AggregateRuna[P]>
}




export type RunaGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RunaWhereInput
  orderBy?: Prisma.RunaOrderByWithAggregationInput | Prisma.RunaOrderByWithAggregationInput[]
  by: Prisma.RunaScalarFieldEnum[] | Prisma.RunaScalarFieldEnum
  having?: Prisma.RunaScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RunaCountAggregateInputType | true
  _avg?: RunaAvgAggregateInputType
  _sum?: RunaSumAggregateInputType
  _min?: RunaMinAggregateInputType
  _max?: RunaMaxAggregateInputType
}

export type RunaGroupByOutputType = {
  Nome: string
  Descrizione: string
  CamminoId: number
  Grado: number
  Immagine: string
  Deprecata: boolean
  _count: RunaCountAggregateOutputType | null
  _avg: RunaAvgAggregateOutputType | null
  _sum: RunaSumAggregateOutputType | null
  _min: RunaMinAggregateOutputType | null
  _max: RunaMaxAggregateOutputType | null
}

export type GetRunaGroupByPayload<T extends RunaGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RunaGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RunaGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RunaGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RunaGroupByOutputType[P]>
      }
    >
  >



export type RunaWhereInput = {
  AND?: Prisma.RunaWhereInput | Prisma.RunaWhereInput[]
  OR?: Prisma.RunaWhereInput[]
  NOT?: Prisma.RunaWhereInput | Prisma.RunaWhereInput[]
  Nome?: Prisma.StringFilter<"Runa"> | string
  Descrizione?: Prisma.StringFilter<"Runa"> | string
  CamminoId?: Prisma.IntFilter<"Runa"> | number
  Grado?: Prisma.IntFilter<"Runa"> | number
  Immagine?: Prisma.StringFilter<"Runa"> | string
  Deprecata?: Prisma.BoolFilter<"Runa"> | boolean
  Camm?: Prisma.XOR<Prisma.Tipologia_runaScalarRelationFilter, Prisma.Tipologia_runaWhereInput>
  keystone?: Prisma.Sezione_RunaListRelationFilter
  Prima?: Prisma.Sezione_RunaListRelationFilter
  Centrale?: Prisma.Sezione_RunaListRelationFilter
  Ultima?: Prisma.Sezione_RunaListRelationFilter
}

export type RunaOrderByWithRelationInput = {
  Nome?: Prisma.SortOrder
  Descrizione?: Prisma.SortOrder
  CamminoId?: Prisma.SortOrder
  Grado?: Prisma.SortOrder
  Immagine?: Prisma.SortOrder
  Deprecata?: Prisma.SortOrder
  Camm?: Prisma.Tipologia_runaOrderByWithRelationInput
  keystone?: Prisma.Sezione_RunaOrderByRelationAggregateInput
  Prima?: Prisma.Sezione_RunaOrderByRelationAggregateInput
  Centrale?: Prisma.Sezione_RunaOrderByRelationAggregateInput
  Ultima?: Prisma.Sezione_RunaOrderByRelationAggregateInput
}

export type RunaWhereUniqueInput = Prisma.AtLeast<{
  Nome?: string
  AND?: Prisma.RunaWhereInput | Prisma.RunaWhereInput[]
  OR?: Prisma.RunaWhereInput[]
  NOT?: Prisma.RunaWhereInput | Prisma.RunaWhereInput[]
  Descrizione?: Prisma.StringFilter<"Runa"> | string
  CamminoId?: Prisma.IntFilter<"Runa"> | number
  Grado?: Prisma.IntFilter<"Runa"> | number
  Immagine?: Prisma.StringFilter<"Runa"> | string
  Deprecata?: Prisma.BoolFilter<"Runa"> | boolean
  Camm?: Prisma.XOR<Prisma.Tipologia_runaScalarRelationFilter, Prisma.Tipologia_runaWhereInput>
  keystone?: Prisma.Sezione_RunaListRelationFilter
  Prima?: Prisma.Sezione_RunaListRelationFilter
  Centrale?: Prisma.Sezione_RunaListRelationFilter
  Ultima?: Prisma.Sezione_RunaListRelationFilter
}, "Nome">

export type RunaOrderByWithAggregationInput = {
  Nome?: Prisma.SortOrder
  Descrizione?: Prisma.SortOrder
  CamminoId?: Prisma.SortOrder
  Grado?: Prisma.SortOrder
  Immagine?: Prisma.SortOrder
  Deprecata?: Prisma.SortOrder
  _count?: Prisma.RunaCountOrderByAggregateInput
  _avg?: Prisma.RunaAvgOrderByAggregateInput
  _max?: Prisma.RunaMaxOrderByAggregateInput
  _min?: Prisma.RunaMinOrderByAggregateInput
  _sum?: Prisma.RunaSumOrderByAggregateInput
}

export type RunaScalarWhereWithAggregatesInput = {
  AND?: Prisma.RunaScalarWhereWithAggregatesInput | Prisma.RunaScalarWhereWithAggregatesInput[]
  OR?: Prisma.RunaScalarWhereWithAggregatesInput[]
  NOT?: Prisma.RunaScalarWhereWithAggregatesInput | Prisma.RunaScalarWhereWithAggregatesInput[]
  Nome?: Prisma.StringWithAggregatesFilter<"Runa"> | string
  Descrizione?: Prisma.StringWithAggregatesFilter<"Runa"> | string
  CamminoId?: Prisma.IntWithAggregatesFilter<"Runa"> | number
  Grado?: Prisma.IntWithAggregatesFilter<"Runa"> | number
  Immagine?: Prisma.StringWithAggregatesFilter<"Runa"> | string
  Deprecata?: Prisma.BoolWithAggregatesFilter<"Runa"> | boolean
}

export type RunaCreateInput = {
  Nome: string
  Descrizione: string
  Grado: number
  Immagine: string
  Deprecata?: boolean
  Camm: Prisma.Tipologia_runaCreateNestedOneWithoutCammInput
  keystone?: Prisma.Sezione_RunaCreateNestedManyWithoutKeystoneInput
  Prima?: Prisma.Sezione_RunaCreateNestedManyWithoutFirstInput
  Centrale?: Prisma.Sezione_RunaCreateNestedManyWithoutMiddleInput
  Ultima?: Prisma.Sezione_RunaCreateNestedManyWithoutLowerInput
}

export type RunaUncheckedCreateInput = {
  Nome: string
  Descrizione: string
  CamminoId: number
  Grado: number
  Immagine: string
  Deprecata?: boolean
  keystone?: Prisma.Sezione_RunaUncheckedCreateNestedManyWithoutKeystoneInput
  Prima?: Prisma.Sezione_RunaUncheckedCreateNestedManyWithoutFirstInput
  Centrale?: Prisma.Sezione_RunaUncheckedCreateNestedManyWithoutMiddleInput
  Ultima?: Prisma.Sezione_RunaUncheckedCreateNestedManyWithoutLowerInput
}

export type RunaUpdateInput = {
  Nome?: Prisma.StringFieldUpdateOperationsInput | string
  Descrizione?: Prisma.StringFieldUpdateOperationsInput | string
  Grado?: Prisma.IntFieldUpdateOperationsInput | number
  Immagine?: Prisma.StringFieldUpdateOperationsInput | string
  Deprecata?: Prisma.BoolFieldUpdateOperationsInput | boolean
  Camm?: Prisma.Tipologia_runaUpdateOneRequiredWithoutCammNestedInput
  keystone?: Prisma.Sezione_RunaUpdateManyWithoutKeystoneNestedInput
  Prima?: Prisma.Sezione_RunaUpdateManyWithoutFirstNestedInput
  Centrale?: Prisma.Sezione_RunaUpdateManyWithoutMiddleNestedInput
  Ultima?: Prisma.Sezione_RunaUpdateManyWithoutLowerNestedInput
}

export type RunaUncheckedUpdateInput = {
  Nome?: Prisma.StringFieldUpdateOperationsInput | string
  Descrizione?: Prisma.StringFieldUpdateOperationsInput | string
  CamminoId?: Prisma.IntFieldUpdateOperationsInput | number
  Grado?: Prisma.IntFieldUpdateOperationsInput | number
  Immagine?: Prisma.StringFieldUpdateOperationsInput | string
  Deprecata?: Prisma.BoolFieldUpdateOperationsInput | boolean
  keystone?: Prisma.Sezione_RunaUncheckedUpdateManyWithoutKeystoneNestedInput
  Prima?: Prisma.Sezione_RunaUncheckedUpdateManyWithoutFirstNestedInput
  Centrale?: Prisma.Sezione_RunaUncheckedUpdateManyWithoutMiddleNestedInput
  Ultima?: Prisma.Sezione_RunaUncheckedUpdateManyWithoutLowerNestedInput
}

export type RunaCreateManyInput = {
  Nome: string
  Descrizione: string
  CamminoId: number
  Grado: number
  Immagine: string
  Deprecata?: boolean
}

export type RunaUpdateManyMutationInput = {
  Nome?: Prisma.StringFieldUpdateOperationsInput | string
  Descrizione?: Prisma.StringFieldUpdateOperationsInput | string
  Grado?: Prisma.IntFieldUpdateOperationsInput | number
  Immagine?: Prisma.StringFieldUpdateOperationsInput | string
  Deprecata?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type RunaUncheckedUpdateManyInput = {
  Nome?: Prisma.StringFieldUpdateOperationsInput | string
  Descrizione?: Prisma.StringFieldUpdateOperationsInput | string
  CamminoId?: Prisma.IntFieldUpdateOperationsInput | number
  Grado?: Prisma.IntFieldUpdateOperationsInput | number
  Immagine?: Prisma.StringFieldUpdateOperationsInput | string
  Deprecata?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type RunaScalarRelationFilter = {
  is?: Prisma.RunaWhereInput
  isNot?: Prisma.RunaWhereInput
}

export type RunaCountOrderByAggregateInput = {
  Nome?: Prisma.SortOrder
  Descrizione?: Prisma.SortOrder
  CamminoId?: Prisma.SortOrder
  Grado?: Prisma.SortOrder
  Immagine?: Prisma.SortOrder
  Deprecata?: Prisma.SortOrder
}

export type RunaAvgOrderByAggregateInput = {
  CamminoId?: Prisma.SortOrder
  Grado?: Prisma.SortOrder
}

export type RunaMaxOrderByAggregateInput = {
  Nome?: Prisma.SortOrder
  Descrizione?: Prisma.SortOrder
  CamminoId?: Prisma.SortOrder
  Grado?: Prisma.SortOrder
  Immagine?: Prisma.SortOrder
  Deprecata?: Prisma.SortOrder
}

export type RunaMinOrderByAggregateInput = {
  Nome?: Prisma.SortOrder
  Descrizione?: Prisma.SortOrder
  CamminoId?: Prisma.SortOrder
  Grado?: Prisma.SortOrder
  Immagine?: Prisma.SortOrder
  Deprecata?: Prisma.SortOrder
}

export type RunaSumOrderByAggregateInput = {
  CamminoId?: Prisma.SortOrder
  Grado?: Prisma.SortOrder
}

export type RunaListRelationFilter = {
  every?: Prisma.RunaWhereInput
  some?: Prisma.RunaWhereInput
  none?: Prisma.RunaWhereInput
}

export type RunaOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type RunaCreateNestedOneWithoutKeystoneInput = {
  create?: Prisma.XOR<Prisma.RunaCreateWithoutKeystoneInput, Prisma.RunaUncheckedCreateWithoutKeystoneInput>
  connectOrCreate?: Prisma.RunaCreateOrConnectWithoutKeystoneInput
  connect?: Prisma.RunaWhereUniqueInput
}

export type RunaCreateNestedOneWithoutPrimaInput = {
  create?: Prisma.XOR<Prisma.RunaCreateWithoutPrimaInput, Prisma.RunaUncheckedCreateWithoutPrimaInput>
  connectOrCreate?: Prisma.RunaCreateOrConnectWithoutPrimaInput
  connect?: Prisma.RunaWhereUniqueInput
}

export type RunaCreateNestedOneWithoutCentraleInput = {
  create?: Prisma.XOR<Prisma.RunaCreateWithoutCentraleInput, Prisma.RunaUncheckedCreateWithoutCentraleInput>
  connectOrCreate?: Prisma.RunaCreateOrConnectWithoutCentraleInput
  connect?: Prisma.RunaWhereUniqueInput
}

export type RunaCreateNestedOneWithoutUltimaInput = {
  create?: Prisma.XOR<Prisma.RunaCreateWithoutUltimaInput, Prisma.RunaUncheckedCreateWithoutUltimaInput>
  connectOrCreate?: Prisma.RunaCreateOrConnectWithoutUltimaInput
  connect?: Prisma.RunaWhereUniqueInput
}

export type RunaUpdateOneRequiredWithoutKeystoneNestedInput = {
  create?: Prisma.XOR<Prisma.RunaCreateWithoutKeystoneInput, Prisma.RunaUncheckedCreateWithoutKeystoneInput>
  connectOrCreate?: Prisma.RunaCreateOrConnectWithoutKeystoneInput
  upsert?: Prisma.RunaUpsertWithoutKeystoneInput
  connect?: Prisma.RunaWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.RunaUpdateToOneWithWhereWithoutKeystoneInput, Prisma.RunaUpdateWithoutKeystoneInput>, Prisma.RunaUncheckedUpdateWithoutKeystoneInput>
}

export type RunaUpdateOneRequiredWithoutPrimaNestedInput = {
  create?: Prisma.XOR<Prisma.RunaCreateWithoutPrimaInput, Prisma.RunaUncheckedCreateWithoutPrimaInput>
  connectOrCreate?: Prisma.RunaCreateOrConnectWithoutPrimaInput
  upsert?: Prisma.RunaUpsertWithoutPrimaInput
  connect?: Prisma.RunaWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.RunaUpdateToOneWithWhereWithoutPrimaInput, Prisma.RunaUpdateWithoutPrimaInput>, Prisma.RunaUncheckedUpdateWithoutPrimaInput>
}

export type RunaUpdateOneRequiredWithoutCentraleNestedInput = {
  create?: Prisma.XOR<Prisma.RunaCreateWithoutCentraleInput, Prisma.RunaUncheckedCreateWithoutCentraleInput>
  connectOrCreate?: Prisma.RunaCreateOrConnectWithoutCentraleInput
  upsert?: Prisma.RunaUpsertWithoutCentraleInput
  connect?: Prisma.RunaWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.RunaUpdateToOneWithWhereWithoutCentraleInput, Prisma.RunaUpdateWithoutCentraleInput>, Prisma.RunaUncheckedUpdateWithoutCentraleInput>
}

export type RunaUpdateOneRequiredWithoutUltimaNestedInput = {
  create?: Prisma.XOR<Prisma.RunaCreateWithoutUltimaInput, Prisma.RunaUncheckedCreateWithoutUltimaInput>
  connectOrCreate?: Prisma.RunaCreateOrConnectWithoutUltimaInput
  upsert?: Prisma.RunaUpsertWithoutUltimaInput
  connect?: Prisma.RunaWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.RunaUpdateToOneWithWhereWithoutUltimaInput, Prisma.RunaUpdateWithoutUltimaInput>, Prisma.RunaUncheckedUpdateWithoutUltimaInput>
}

export type RunaCreateNestedManyWithoutCammInput = {
  create?: Prisma.XOR<Prisma.RunaCreateWithoutCammInput, Prisma.RunaUncheckedCreateWithoutCammInput> | Prisma.RunaCreateWithoutCammInput[] | Prisma.RunaUncheckedCreateWithoutCammInput[]
  connectOrCreate?: Prisma.RunaCreateOrConnectWithoutCammInput | Prisma.RunaCreateOrConnectWithoutCammInput[]
  createMany?: Prisma.RunaCreateManyCammInputEnvelope
  connect?: Prisma.RunaWhereUniqueInput | Prisma.RunaWhereUniqueInput[]
}

export type RunaUncheckedCreateNestedManyWithoutCammInput = {
  create?: Prisma.XOR<Prisma.RunaCreateWithoutCammInput, Prisma.RunaUncheckedCreateWithoutCammInput> | Prisma.RunaCreateWithoutCammInput[] | Prisma.RunaUncheckedCreateWithoutCammInput[]
  connectOrCreate?: Prisma.RunaCreateOrConnectWithoutCammInput | Prisma.RunaCreateOrConnectWithoutCammInput[]
  createMany?: Prisma.RunaCreateManyCammInputEnvelope
  connect?: Prisma.RunaWhereUniqueInput | Prisma.RunaWhereUniqueInput[]
}

export type RunaUpdateManyWithoutCammNestedInput = {
  create?: Prisma.XOR<Prisma.RunaCreateWithoutCammInput, Prisma.RunaUncheckedCreateWithoutCammInput> | Prisma.RunaCreateWithoutCammInput[] | Prisma.RunaUncheckedCreateWithoutCammInput[]
  connectOrCreate?: Prisma.RunaCreateOrConnectWithoutCammInput | Prisma.RunaCreateOrConnectWithoutCammInput[]
  upsert?: Prisma.RunaUpsertWithWhereUniqueWithoutCammInput | Prisma.RunaUpsertWithWhereUniqueWithoutCammInput[]
  createMany?: Prisma.RunaCreateManyCammInputEnvelope
  set?: Prisma.RunaWhereUniqueInput | Prisma.RunaWhereUniqueInput[]
  disconnect?: Prisma.RunaWhereUniqueInput | Prisma.RunaWhereUniqueInput[]
  delete?: Prisma.RunaWhereUniqueInput | Prisma.RunaWhereUniqueInput[]
  connect?: Prisma.RunaWhereUniqueInput | Prisma.RunaWhereUniqueInput[]
  update?: Prisma.RunaUpdateWithWhereUniqueWithoutCammInput | Prisma.RunaUpdateWithWhereUniqueWithoutCammInput[]
  updateMany?: Prisma.RunaUpdateManyWithWhereWithoutCammInput | Prisma.RunaUpdateManyWithWhereWithoutCammInput[]
  deleteMany?: Prisma.RunaScalarWhereInput | Prisma.RunaScalarWhereInput[]
}

export type RunaUncheckedUpdateManyWithoutCammNestedInput = {
  create?: Prisma.XOR<Prisma.RunaCreateWithoutCammInput, Prisma.RunaUncheckedCreateWithoutCammInput> | Prisma.RunaCreateWithoutCammInput[] | Prisma.RunaUncheckedCreateWithoutCammInput[]
  connectOrCreate?: Prisma.RunaCreateOrConnectWithoutCammInput | Prisma.RunaCreateOrConnectWithoutCammInput[]
  upsert?: Prisma.RunaUpsertWithWhereUniqueWithoutCammInput | Prisma.RunaUpsertWithWhereUniqueWithoutCammInput[]
  createMany?: Prisma.RunaCreateManyCammInputEnvelope
  set?: Prisma.RunaWhereUniqueInput | Prisma.RunaWhereUniqueInput[]
  disconnect?: Prisma.RunaWhereUniqueInput | Prisma.RunaWhereUniqueInput[]
  delete?: Prisma.RunaWhereUniqueInput | Prisma.RunaWhereUniqueInput[]
  connect?: Prisma.RunaWhereUniqueInput | Prisma.RunaWhereUniqueInput[]
  update?: Prisma.RunaUpdateWithWhereUniqueWithoutCammInput | Prisma.RunaUpdateWithWhereUniqueWithoutCammInput[]
  updateMany?: Prisma.RunaUpdateManyWithWhereWithoutCammInput | Prisma.RunaUpdateManyWithWhereWithoutCammInput[]
  deleteMany?: Prisma.RunaScalarWhereInput | Prisma.RunaScalarWhereInput[]
}

export type RunaCreateWithoutKeystoneInput = {
  Nome: string
  Descrizione: string
  Grado: number
  Immagine: string
  Deprecata?: boolean
  Camm: Prisma.Tipologia_runaCreateNestedOneWithoutCammInput
  Prima?: Prisma.Sezione_RunaCreateNestedManyWithoutFirstInput
  Centrale?: Prisma.Sezione_RunaCreateNestedManyWithoutMiddleInput
  Ultima?: Prisma.Sezione_RunaCreateNestedManyWithoutLowerInput
}

export type RunaUncheckedCreateWithoutKeystoneInput = {
  Nome: string
  Descrizione: string
  CamminoId: number
  Grado: number
  Immagine: string
  Deprecata?: boolean
  Prima?: Prisma.Sezione_RunaUncheckedCreateNestedManyWithoutFirstInput
  Centrale?: Prisma.Sezione_RunaUncheckedCreateNestedManyWithoutMiddleInput
  Ultima?: Prisma.Sezione_RunaUncheckedCreateNestedManyWithoutLowerInput
}

export type RunaCreateOrConnectWithoutKeystoneInput = {
  where: Prisma.RunaWhereUniqueInput
  create: Prisma.XOR<Prisma.RunaCreateWithoutKeystoneInput, Prisma.RunaUncheckedCreateWithoutKeystoneInput>
}

export type RunaCreateWithoutPrimaInput = {
  Nome: string
  Descrizione: string
  Grado: number
  Immagine: string
  Deprecata?: boolean
  Camm: Prisma.Tipologia_runaCreateNestedOneWithoutCammInput
  keystone?: Prisma.Sezione_RunaCreateNestedManyWithoutKeystoneInput
  Centrale?: Prisma.Sezione_RunaCreateNestedManyWithoutMiddleInput
  Ultima?: Prisma.Sezione_RunaCreateNestedManyWithoutLowerInput
}

export type RunaUncheckedCreateWithoutPrimaInput = {
  Nome: string
  Descrizione: string
  CamminoId: number
  Grado: number
  Immagine: string
  Deprecata?: boolean
  keystone?: Prisma.Sezione_RunaUncheckedCreateNestedManyWithoutKeystoneInput
  Centrale?: Prisma.Sezione_RunaUncheckedCreateNestedManyWithoutMiddleInput
  Ultima?: Prisma.Sezione_RunaUncheckedCreateNestedManyWithoutLowerInput
}

export type RunaCreateOrConnectWithoutPrimaInput = {
  where: Prisma.RunaWhereUniqueInput
  create: Prisma.XOR<Prisma.RunaCreateWithoutPrimaInput, Prisma.RunaUncheckedCreateWithoutPrimaInput>
}

export type RunaCreateWithoutCentraleInput = {
  Nome: string
  Descrizione: string
  Grado: number
  Immagine: string
  Deprecata?: boolean
  Camm: Prisma.Tipologia_runaCreateNestedOneWithoutCammInput
  keystone?: Prisma.Sezione_RunaCreateNestedManyWithoutKeystoneInput
  Prima?: Prisma.Sezione_RunaCreateNestedManyWithoutFirstInput
  Ultima?: Prisma.Sezione_RunaCreateNestedManyWithoutLowerInput
}

export type RunaUncheckedCreateWithoutCentraleInput = {
  Nome: string
  Descrizione: string
  CamminoId: number
  Grado: number
  Immagine: string
  Deprecata?: boolean
  keystone?: Prisma.Sezione_RunaUncheckedCreateNestedManyWithoutKeystoneInput
  Prima?: Prisma.Sezione_RunaUncheckedCreateNestedManyWithoutFirstInput
  Ultima?: Prisma.Sezione_RunaUncheckedCreateNestedManyWithoutLowerInput
}

export type RunaCreateOrConnectWithoutCentraleInput = {
  where: Prisma.RunaWhereUniqueInput
  create: Prisma.XOR<Prisma.RunaCreateWithoutCentraleInput, Prisma.RunaUncheckedCreateWithoutCentraleInput>
}

export type RunaCreateWithoutUltimaInput = {
  Nome: string
  Descrizione: string
  Grado: number
  Immagine: string
  Deprecata?: boolean
  Camm: Prisma.Tipologia_runaCreateNestedOneWithoutCammInput
  keystone?: Prisma.Sezione_RunaCreateNestedManyWithoutKeystoneInput
  Prima?: Prisma.Sezione_RunaCreateNestedManyWithoutFirstInput
  Centrale?: Prisma.Sezione_RunaCreateNestedManyWithoutMiddleInput
}

export type RunaUncheckedCreateWithoutUltimaInput = {
  Nome: string
  Descrizione: string
  CamminoId: number
  Grado: number
  Immagine: string
  Deprecata?: boolean
  keystone?: Prisma.Sezione_RunaUncheckedCreateNestedManyWithoutKeystoneInput
  Prima?: Prisma.Sezione_RunaUncheckedCreateNestedManyWithoutFirstInput
  Centrale?: Prisma.Sezione_RunaUncheckedCreateNestedManyWithoutMiddleInput
}

export type RunaCreateOrConnectWithoutUltimaInput = {
  where: Prisma.RunaWhereUniqueInput
  create: Prisma.XOR<Prisma.RunaCreateWithoutUltimaInput, Prisma.RunaUncheckedCreateWithoutUltimaInput>
}

export type RunaUpsertWithoutKeystoneInput = {
  update: Prisma.XOR<Prisma.RunaUpdateWithoutKeystoneInput, Prisma.RunaUncheckedUpdateWithoutKeystoneInput>
  create: Prisma.XOR<Prisma.RunaCreateWithoutKeystoneInput, Prisma.RunaUncheckedCreateWithoutKeystoneInput>
  where?: Prisma.RunaWhereInput
}

export type RunaUpdateToOneWithWhereWithoutKeystoneInput = {
  where?: Prisma.RunaWhereInput
  data: Prisma.XOR<Prisma.RunaUpdateWithoutKeystoneInput, Prisma.RunaUncheckedUpdateWithoutKeystoneInput>
}

export type RunaUpdateWithoutKeystoneInput = {
  Nome?: Prisma.StringFieldUpdateOperationsInput | string
  Descrizione?: Prisma.StringFieldUpdateOperationsInput | string
  Grado?: Prisma.IntFieldUpdateOperationsInput | number
  Immagine?: Prisma.StringFieldUpdateOperationsInput | string
  Deprecata?: Prisma.BoolFieldUpdateOperationsInput | boolean
  Camm?: Prisma.Tipologia_runaUpdateOneRequiredWithoutCammNestedInput
  Prima?: Prisma.Sezione_RunaUpdateManyWithoutFirstNestedInput
  Centrale?: Prisma.Sezione_RunaUpdateManyWithoutMiddleNestedInput
  Ultima?: Prisma.Sezione_RunaUpdateManyWithoutLowerNestedInput
}

export type RunaUncheckedUpdateWithoutKeystoneInput = {
  Nome?: Prisma.StringFieldUpdateOperationsInput | string
  Descrizione?: Prisma.StringFieldUpdateOperationsInput | string
  CamminoId?: Prisma.IntFieldUpdateOperationsInput | number
  Grado?: Prisma.IntFieldUpdateOperationsInput | number
  Immagine?: Prisma.StringFieldUpdateOperationsInput | string
  Deprecata?: Prisma.BoolFieldUpdateOperationsInput | boolean
  Prima?: Prisma.Sezione_RunaUncheckedUpdateManyWithoutFirstNestedInput
  Centrale?: Prisma.Sezione_RunaUncheckedUpdateManyWithoutMiddleNestedInput
  Ultima?: Prisma.Sezione_RunaUncheckedUpdateManyWithoutLowerNestedInput
}

export type RunaUpsertWithoutPrimaInput = {
  update: Prisma.XOR<Prisma.RunaUpdateWithoutPrimaInput, Prisma.RunaUncheckedUpdateWithoutPrimaInput>
  create: Prisma.XOR<Prisma.RunaCreateWithoutPrimaInput, Prisma.RunaUncheckedCreateWithoutPrimaInput>
  where?: Prisma.RunaWhereInput
}

export type RunaUpdateToOneWithWhereWithoutPrimaInput = {
  where?: Prisma.RunaWhereInput
  data: Prisma.XOR<Prisma.RunaUpdateWithoutPrimaInput, Prisma.RunaUncheckedUpdateWithoutPrimaInput>
}

export type RunaUpdateWithoutPrimaInput = {
  Nome?: Prisma.StringFieldUpdateOperationsInput | string
  Descrizione?: Prisma.StringFieldUpdateOperationsInput | string
  Grado?: Prisma.IntFieldUpdateOperationsInput | number
  Immagine?: Prisma.StringFieldUpdateOperationsInput | string
  Deprecata?: Prisma.BoolFieldUpdateOperationsInput | boolean
  Camm?: Prisma.Tipologia_runaUpdateOneRequiredWithoutCammNestedInput
  keystone?: Prisma.Sezione_RunaUpdateManyWithoutKeystoneNestedInput
  Centrale?: Prisma.Sezione_RunaUpdateManyWithoutMiddleNestedInput
  Ultima?: Prisma.Sezione_RunaUpdateManyWithoutLowerNestedInput
}

export type RunaUncheckedUpdateWithoutPrimaInput = {
  Nome?: Prisma.StringFieldUpdateOperationsInput | string
  Descrizione?: Prisma.StringFieldUpdateOperationsInput | string
  CamminoId?: Prisma.IntFieldUpdateOperationsInput | number
  Grado?: Prisma.IntFieldUpdateOperationsInput | number
  Immagine?: Prisma.StringFieldUpdateOperationsInput | string
  Deprecata?: Prisma.BoolFieldUpdateOperationsInput | boolean
  keystone?: Prisma.Sezione_RunaUncheckedUpdateManyWithoutKeystoneNestedInput
  Centrale?: Prisma.Sezione_RunaUncheckedUpdateManyWithoutMiddleNestedInput
  Ultima?: Prisma.Sezione_RunaUncheckedUpdateManyWithoutLowerNestedInput
}

export type RunaUpsertWithoutCentraleInput = {
  update: Prisma.XOR<Prisma.RunaUpdateWithoutCentraleInput, Prisma.RunaUncheckedUpdateWithoutCentraleInput>
  create: Prisma.XOR<Prisma.RunaCreateWithoutCentraleInput, Prisma.RunaUncheckedCreateWithoutCentraleInput>
  where?: Prisma.RunaWhereInput
}

export type RunaUpdateToOneWithWhereWithoutCentraleInput = {
  where?: Prisma.RunaWhereInput
  data: Prisma.XOR<Prisma.RunaUpdateWithoutCentraleInput, Prisma.RunaUncheckedUpdateWithoutCentraleInput>
}

export type RunaUpdateWithoutCentraleInput = {
  Nome?: Prisma.StringFieldUpdateOperationsInput | string
  Descrizione?: Prisma.StringFieldUpdateOperationsInput | string
  Grado?: Prisma.IntFieldUpdateOperationsInput | number
  Immagine?: Prisma.StringFieldUpdateOperationsInput | string
  Deprecata?: Prisma.BoolFieldUpdateOperationsInput | boolean
  Camm?: Prisma.Tipologia_runaUpdateOneRequiredWithoutCammNestedInput
  keystone?: Prisma.Sezione_RunaUpdateManyWithoutKeystoneNestedInput
  Prima?: Prisma.Sezione_RunaUpdateManyWithoutFirstNestedInput
  Ultima?: Prisma.Sezione_RunaUpdateManyWithoutLowerNestedInput
}

export type RunaUncheckedUpdateWithoutCentraleInput = {
  Nome?: Prisma.StringFieldUpdateOperationsInput | string
  Descrizione?: Prisma.StringFieldUpdateOperationsInput | string
  CamminoId?: Prisma.IntFieldUpdateOperationsInput | number
  Grado?: Prisma.IntFieldUpdateOperationsInput | number
  Immagine?: Prisma.StringFieldUpdateOperationsInput | string
  Deprecata?: Prisma.BoolFieldUpdateOperationsInput | boolean
  keystone?: Prisma.Sezione_RunaUncheckedUpdateManyWithoutKeystoneNestedInput
  Prima?: Prisma.Sezione_RunaUncheckedUpdateManyWithoutFirstNestedInput
  Ultima?: Prisma.Sezione_RunaUncheckedUpdateManyWithoutLowerNestedInput
}

export type RunaUpsertWithoutUltimaInput = {
  update: Prisma.XOR<Prisma.RunaUpdateWithoutUltimaInput, Prisma.RunaUncheckedUpdateWithoutUltimaInput>
  create: Prisma.XOR<Prisma.RunaCreateWithoutUltimaInput, Prisma.RunaUncheckedCreateWithoutUltimaInput>
  where?: Prisma.RunaWhereInput
}

export type RunaUpdateToOneWithWhereWithoutUltimaInput = {
  where?: Prisma.RunaWhereInput
  data: Prisma.XOR<Prisma.RunaUpdateWithoutUltimaInput, Prisma.RunaUncheckedUpdateWithoutUltimaInput>
}

export type RunaUpdateWithoutUltimaInput = {
  Nome?: Prisma.StringFieldUpdateOperationsInput | string
  Descrizione?: Prisma.StringFieldUpdateOperationsInput | string
  Grado?: Prisma.IntFieldUpdateOperationsInput | number
  Immagine?: Prisma.StringFieldUpdateOperationsInput | string
  Deprecata?: Prisma.BoolFieldUpdateOperationsInput | boolean
  Camm?: Prisma.Tipologia_runaUpdateOneRequiredWithoutCammNestedInput
  keystone?: Prisma.Sezione_RunaUpdateManyWithoutKeystoneNestedInput
  Prima?: Prisma.Sezione_RunaUpdateManyWithoutFirstNestedInput
  Centrale?: Prisma.Sezione_RunaUpdateManyWithoutMiddleNestedInput
}

export type RunaUncheckedUpdateWithoutUltimaInput = {
  Nome?: Prisma.StringFieldUpdateOperationsInput | string
  Descrizione?: Prisma.StringFieldUpdateOperationsInput | string
  CamminoId?: Prisma.IntFieldUpdateOperationsInput | number
  Grado?: Prisma.IntFieldUpdateOperationsInput | number
  Immagine?: Prisma.StringFieldUpdateOperationsInput | string
  Deprecata?: Prisma.BoolFieldUpdateOperationsInput | boolean
  keystone?: Prisma.Sezione_RunaUncheckedUpdateManyWithoutKeystoneNestedInput
  Prima?: Prisma.Sezione_RunaUncheckedUpdateManyWithoutFirstNestedInput
  Centrale?: Prisma.Sezione_RunaUncheckedUpdateManyWithoutMiddleNestedInput
}

export type RunaCreateWithoutCammInput = {
  Nome: string
  Descrizione: string
  Grado: number
  Immagine: string
  Deprecata?: boolean
  keystone?: Prisma.Sezione_RunaCreateNestedManyWithoutKeystoneInput
  Prima?: Prisma.Sezione_RunaCreateNestedManyWithoutFirstInput
  Centrale?: Prisma.Sezione_RunaCreateNestedManyWithoutMiddleInput
  Ultima?: Prisma.Sezione_RunaCreateNestedManyWithoutLowerInput
}

export type RunaUncheckedCreateWithoutCammInput = {
  Nome: string
  Descrizione: string
  Grado: number
  Immagine: string
  Deprecata?: boolean
  keystone?: Prisma.Sezione_RunaUncheckedCreateNestedManyWithoutKeystoneInput
  Prima?: Prisma.Sezione_RunaUncheckedCreateNestedManyWithoutFirstInput
  Centrale?: Prisma.Sezione_RunaUncheckedCreateNestedManyWithoutMiddleInput
  Ultima?: Prisma.Sezione_RunaUncheckedCreateNestedManyWithoutLowerInput
}

export type RunaCreateOrConnectWithoutCammInput = {
  where: Prisma.RunaWhereUniqueInput
  create: Prisma.XOR<Prisma.RunaCreateWithoutCammInput, Prisma.RunaUncheckedCreateWithoutCammInput>
}

export type RunaCreateManyCammInputEnvelope = {
  data: Prisma.RunaCreateManyCammInput | Prisma.RunaCreateManyCammInput[]
  skipDuplicates?: boolean
}

export type RunaUpsertWithWhereUniqueWithoutCammInput = {
  where: Prisma.RunaWhereUniqueInput
  update: Prisma.XOR<Prisma.RunaUpdateWithoutCammInput, Prisma.RunaUncheckedUpdateWithoutCammInput>
  create: Prisma.XOR<Prisma.RunaCreateWithoutCammInput, Prisma.RunaUncheckedCreateWithoutCammInput>
}

export type RunaUpdateWithWhereUniqueWithoutCammInput = {
  where: Prisma.RunaWhereUniqueInput
  data: Prisma.XOR<Prisma.RunaUpdateWithoutCammInput, Prisma.RunaUncheckedUpdateWithoutCammInput>
}

export type RunaUpdateManyWithWhereWithoutCammInput = {
  where: Prisma.RunaScalarWhereInput
  data: Prisma.XOR<Prisma.RunaUpdateManyMutationInput, Prisma.RunaUncheckedUpdateManyWithoutCammInput>
}

export type RunaScalarWhereInput = {
  AND?: Prisma.RunaScalarWhereInput | Prisma.RunaScalarWhereInput[]
  OR?: Prisma.RunaScalarWhereInput[]
  NOT?: Prisma.RunaScalarWhereInput | Prisma.RunaScalarWhereInput[]
  Nome?: Prisma.StringFilter<"Runa"> | string
  Descrizione?: Prisma.StringFilter<"Runa"> | string
  CamminoId?: Prisma.IntFilter<"Runa"> | number
  Grado?: Prisma.IntFilter<"Runa"> | number
  Immagine?: Prisma.StringFilter<"Runa"> | string
  Deprecata?: Prisma.BoolFilter<"Runa"> | boolean
}

export type RunaCreateManyCammInput = {
  Nome: string
  Descrizione: string
  Grado: number
  Immagine: string
  Deprecata?: boolean
}

export type RunaUpdateWithoutCammInput = {
  Nome?: Prisma.StringFieldUpdateOperationsInput | string
  Descrizione?: Prisma.StringFieldUpdateOperationsInput | string
  Grado?: Prisma.IntFieldUpdateOperationsInput | number
  Immagine?: Prisma.StringFieldUpdateOperationsInput | string
  Deprecata?: Prisma.BoolFieldUpdateOperationsInput | boolean
  keystone?: Prisma.Sezione_RunaUpdateManyWithoutKeystoneNestedInput
  Prima?: Prisma.Sezione_RunaUpdateManyWithoutFirstNestedInput
  Centrale?: Prisma.Sezione_RunaUpdateManyWithoutMiddleNestedInput
  Ultima?: Prisma.Sezione_RunaUpdateManyWithoutLowerNestedInput
}

export type RunaUncheckedUpdateWithoutCammInput = {
  Nome?: Prisma.StringFieldUpdateOperationsInput | string
  Descrizione?: Prisma.StringFieldUpdateOperationsInput | string
  Grado?: Prisma.IntFieldUpdateOperationsInput | number
  Immagine?: Prisma.StringFieldUpdateOperationsInput | string
  Deprecata?: Prisma.BoolFieldUpdateOperationsInput | boolean
  keystone?: Prisma.Sezione_RunaUncheckedUpdateManyWithoutKeystoneNestedInput
  Prima?: Prisma.Sezione_RunaUncheckedUpdateManyWithoutFirstNestedInput
  Centrale?: Prisma.Sezione_RunaUncheckedUpdateManyWithoutMiddleNestedInput
  Ultima?: Prisma.Sezione_RunaUncheckedUpdateManyWithoutLowerNestedInput
}

export type RunaUncheckedUpdateManyWithoutCammInput = {
  Nome?: Prisma.StringFieldUpdateOperationsInput | string
  Descrizione?: Prisma.StringFieldUpdateOperationsInput | string
  Grado?: Prisma.IntFieldUpdateOperationsInput | number
  Immagine?: Prisma.StringFieldUpdateOperationsInput | string
  Deprecata?: Prisma.BoolFieldUpdateOperationsInput | boolean
}


/**
 * Count Type RunaCountOutputType
 */

export type RunaCountOutputType = {
  keystone: number
  Prima: number
  Centrale: number
  Ultima: number
}

export type RunaCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  keystone?: boolean | RunaCountOutputTypeCountKeystoneArgs
  Prima?: boolean | RunaCountOutputTypeCountPrimaArgs
  Centrale?: boolean | RunaCountOutputTypeCountCentraleArgs
  Ultima?: boolean | RunaCountOutputTypeCountUltimaArgs
}

/**
 * RunaCountOutputType without action
 */
export type RunaCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RunaCountOutputType
   */
  select?: Prisma.RunaCountOutputTypeSelect<ExtArgs> | null
}

/**
 * RunaCountOutputType without action
 */
export type RunaCountOutputTypeCountKeystoneArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.Sezione_RunaWhereInput
}

/**
 * RunaCountOutputType without action
 */
export type RunaCountOutputTypeCountPrimaArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.Sezione_RunaWhereInput
}

/**
 * RunaCountOutputType without action
 */
export type RunaCountOutputTypeCountCentraleArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.Sezione_RunaWhereInput
}

/**
 * RunaCountOutputType without action
 */
export type RunaCountOutputTypeCountUltimaArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.Sezione_RunaWhereInput
}


export type RunaSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  Nome?: boolean
  Descrizione?: boolean
  CamminoId?: boolean
  Grado?: boolean
  Immagine?: boolean
  Deprecata?: boolean
  Camm?: boolean | Prisma.Tipologia_runaDefaultArgs<ExtArgs>
  keystone?: boolean | Prisma.Runa$keystoneArgs<ExtArgs>
  Prima?: boolean | Prisma.Runa$PrimaArgs<ExtArgs>
  Centrale?: boolean | Prisma.Runa$CentraleArgs<ExtArgs>
  Ultima?: boolean | Prisma.Runa$UltimaArgs<ExtArgs>
  _count?: boolean | Prisma.RunaCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["runa"]>

export type RunaSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  Nome?: boolean
  Descrizione?: boolean
  CamminoId?: boolean
  Grado?: boolean
  Immagine?: boolean
  Deprecata?: boolean
  Camm?: boolean | Prisma.Tipologia_runaDefaultArgs<ExtArgs>
}, ExtArgs["result"]["runa"]>

export type RunaSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  Nome?: boolean
  Descrizione?: boolean
  CamminoId?: boolean
  Grado?: boolean
  Immagine?: boolean
  Deprecata?: boolean
  Camm?: boolean | Prisma.Tipologia_runaDefaultArgs<ExtArgs>
}, ExtArgs["result"]["runa"]>

export type RunaSelectScalar = {
  Nome?: boolean
  Descrizione?: boolean
  CamminoId?: boolean
  Grado?: boolean
  Immagine?: boolean
  Deprecata?: boolean
}

export type RunaOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"Nome" | "Descrizione" | "CamminoId" | "Grado" | "Immagine" | "Deprecata", ExtArgs["result"]["runa"]>
export type RunaInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Camm?: boolean | Prisma.Tipologia_runaDefaultArgs<ExtArgs>
  keystone?: boolean | Prisma.Runa$keystoneArgs<ExtArgs>
  Prima?: boolean | Prisma.Runa$PrimaArgs<ExtArgs>
  Centrale?: boolean | Prisma.Runa$CentraleArgs<ExtArgs>
  Ultima?: boolean | Prisma.Runa$UltimaArgs<ExtArgs>
  _count?: boolean | Prisma.RunaCountOutputTypeDefaultArgs<ExtArgs>
}
export type RunaIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Camm?: boolean | Prisma.Tipologia_runaDefaultArgs<ExtArgs>
}
export type RunaIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Camm?: boolean | Prisma.Tipologia_runaDefaultArgs<ExtArgs>
}

export type $RunaPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Runa"
  objects: {
    Camm: Prisma.$Tipologia_runaPayload<ExtArgs>
    keystone: Prisma.$Sezione_RunaPayload<ExtArgs>[]
    Prima: Prisma.$Sezione_RunaPayload<ExtArgs>[]
    Centrale: Prisma.$Sezione_RunaPayload<ExtArgs>[]
    Ultima: Prisma.$Sezione_RunaPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    Nome: string
    Descrizione: string
    CamminoId: number
    Grado: number
    Immagine: string
    Deprecata: boolean
  }, ExtArgs["result"]["runa"]>
  composites: {}
}

export type RunaGetPayload<S extends boolean | null | undefined | RunaDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$RunaPayload, S>

export type RunaCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<RunaFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RunaCountAggregateInputType | true
  }

export interface RunaDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Runa'], meta: { name: 'Runa' } }
  /**
   * Find zero or one Runa that matches the filter.
   * @param {RunaFindUniqueArgs} args - Arguments to find a Runa
   * @example
   * // Get one Runa
   * const runa = await prisma.runa.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RunaFindUniqueArgs>(args: Prisma.SelectSubset<T, RunaFindUniqueArgs<ExtArgs>>): Prisma.Prisma__RunaClient<runtime.Types.Result.GetResult<Prisma.$RunaPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Runa that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RunaFindUniqueOrThrowArgs} args - Arguments to find a Runa
   * @example
   * // Get one Runa
   * const runa = await prisma.runa.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RunaFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, RunaFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__RunaClient<runtime.Types.Result.GetResult<Prisma.$RunaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Runa that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RunaFindFirstArgs} args - Arguments to find a Runa
   * @example
   * // Get one Runa
   * const runa = await prisma.runa.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RunaFindFirstArgs>(args?: Prisma.SelectSubset<T, RunaFindFirstArgs<ExtArgs>>): Prisma.Prisma__RunaClient<runtime.Types.Result.GetResult<Prisma.$RunaPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Runa that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RunaFindFirstOrThrowArgs} args - Arguments to find a Runa
   * @example
   * // Get one Runa
   * const runa = await prisma.runa.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RunaFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, RunaFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__RunaClient<runtime.Types.Result.GetResult<Prisma.$RunaPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Runas that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RunaFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Runas
   * const runas = await prisma.runa.findMany()
   * 
   * // Get first 10 Runas
   * const runas = await prisma.runa.findMany({ take: 10 })
   * 
   * // Only select the `Nome`
   * const runaWithNomeOnly = await prisma.runa.findMany({ select: { Nome: true } })
   * 
   */
  findMany<T extends RunaFindManyArgs>(args?: Prisma.SelectSubset<T, RunaFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RunaPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Runa.
   * @param {RunaCreateArgs} args - Arguments to create a Runa.
   * @example
   * // Create one Runa
   * const Runa = await prisma.runa.create({
   *   data: {
   *     // ... data to create a Runa
   *   }
   * })
   * 
   */
  create<T extends RunaCreateArgs>(args: Prisma.SelectSubset<T, RunaCreateArgs<ExtArgs>>): Prisma.Prisma__RunaClient<runtime.Types.Result.GetResult<Prisma.$RunaPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Runas.
   * @param {RunaCreateManyArgs} args - Arguments to create many Runas.
   * @example
   * // Create many Runas
   * const runa = await prisma.runa.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends RunaCreateManyArgs>(args?: Prisma.SelectSubset<T, RunaCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Runas and returns the data saved in the database.
   * @param {RunaCreateManyAndReturnArgs} args - Arguments to create many Runas.
   * @example
   * // Create many Runas
   * const runa = await prisma.runa.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Runas and only return the `Nome`
   * const runaWithNomeOnly = await prisma.runa.createManyAndReturn({
   *   select: { Nome: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends RunaCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, RunaCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RunaPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Runa.
   * @param {RunaDeleteArgs} args - Arguments to delete one Runa.
   * @example
   * // Delete one Runa
   * const Runa = await prisma.runa.delete({
   *   where: {
   *     // ... filter to delete one Runa
   *   }
   * })
   * 
   */
  delete<T extends RunaDeleteArgs>(args: Prisma.SelectSubset<T, RunaDeleteArgs<ExtArgs>>): Prisma.Prisma__RunaClient<runtime.Types.Result.GetResult<Prisma.$RunaPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Runa.
   * @param {RunaUpdateArgs} args - Arguments to update one Runa.
   * @example
   * // Update one Runa
   * const runa = await prisma.runa.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends RunaUpdateArgs>(args: Prisma.SelectSubset<T, RunaUpdateArgs<ExtArgs>>): Prisma.Prisma__RunaClient<runtime.Types.Result.GetResult<Prisma.$RunaPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Runas.
   * @param {RunaDeleteManyArgs} args - Arguments to filter Runas to delete.
   * @example
   * // Delete a few Runas
   * const { count } = await prisma.runa.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends RunaDeleteManyArgs>(args?: Prisma.SelectSubset<T, RunaDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Runas.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RunaUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Runas
   * const runa = await prisma.runa.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends RunaUpdateManyArgs>(args: Prisma.SelectSubset<T, RunaUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Runas and returns the data updated in the database.
   * @param {RunaUpdateManyAndReturnArgs} args - Arguments to update many Runas.
   * @example
   * // Update many Runas
   * const runa = await prisma.runa.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Runas and only return the `Nome`
   * const runaWithNomeOnly = await prisma.runa.updateManyAndReturn({
   *   select: { Nome: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends RunaUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, RunaUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RunaPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Runa.
   * @param {RunaUpsertArgs} args - Arguments to update or create a Runa.
   * @example
   * // Update or create a Runa
   * const runa = await prisma.runa.upsert({
   *   create: {
   *     // ... data to create a Runa
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Runa we want to update
   *   }
   * })
   */
  upsert<T extends RunaUpsertArgs>(args: Prisma.SelectSubset<T, RunaUpsertArgs<ExtArgs>>): Prisma.Prisma__RunaClient<runtime.Types.Result.GetResult<Prisma.$RunaPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Runas.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RunaCountArgs} args - Arguments to filter Runas to count.
   * @example
   * // Count the number of Runas
   * const count = await prisma.runa.count({
   *   where: {
   *     // ... the filter for the Runas we want to count
   *   }
   * })
  **/
  count<T extends RunaCountArgs>(
    args?: Prisma.Subset<T, RunaCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RunaCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Runa.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RunaAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RunaAggregateArgs>(args: Prisma.Subset<T, RunaAggregateArgs>): Prisma.PrismaPromise<GetRunaAggregateType<T>>

  /**
   * Group by Runa.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RunaGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends RunaGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RunaGroupByArgs['orderBy'] }
      : { orderBy?: RunaGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, RunaGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRunaGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Runa model
 */
readonly fields: RunaFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Runa.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RunaClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  Camm<T extends Prisma.Tipologia_runaDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Tipologia_runaDefaultArgs<ExtArgs>>): Prisma.Prisma__Tipologia_runaClient<runtime.Types.Result.GetResult<Prisma.$Tipologia_runaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  keystone<T extends Prisma.Runa$keystoneArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Runa$keystoneArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Sezione_RunaPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  Prima<T extends Prisma.Runa$PrimaArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Runa$PrimaArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Sezione_RunaPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  Centrale<T extends Prisma.Runa$CentraleArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Runa$CentraleArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Sezione_RunaPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  Ultima<T extends Prisma.Runa$UltimaArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Runa$UltimaArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Sezione_RunaPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Runa model
 */
export interface RunaFieldRefs {
  readonly Nome: Prisma.FieldRef<"Runa", 'String'>
  readonly Descrizione: Prisma.FieldRef<"Runa", 'String'>
  readonly CamminoId: Prisma.FieldRef<"Runa", 'Int'>
  readonly Grado: Prisma.FieldRef<"Runa", 'Int'>
  readonly Immagine: Prisma.FieldRef<"Runa", 'String'>
  readonly Deprecata: Prisma.FieldRef<"Runa", 'Boolean'>
}
    

// Custom InputTypes
/**
 * Runa findUnique
 */
export type RunaFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Runa
   */
  select?: Prisma.RunaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Runa
   */
  omit?: Prisma.RunaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RunaInclude<ExtArgs> | null
  /**
   * Filter, which Runa to fetch.
   */
  where: Prisma.RunaWhereUniqueInput
}

/**
 * Runa findUniqueOrThrow
 */
export type RunaFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Runa
   */
  select?: Prisma.RunaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Runa
   */
  omit?: Prisma.RunaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RunaInclude<ExtArgs> | null
  /**
   * Filter, which Runa to fetch.
   */
  where: Prisma.RunaWhereUniqueInput
}

/**
 * Runa findFirst
 */
export type RunaFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Runa
   */
  select?: Prisma.RunaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Runa
   */
  omit?: Prisma.RunaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RunaInclude<ExtArgs> | null
  /**
   * Filter, which Runa to fetch.
   */
  where?: Prisma.RunaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Runas to fetch.
   */
  orderBy?: Prisma.RunaOrderByWithRelationInput | Prisma.RunaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Runas.
   */
  cursor?: Prisma.RunaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Runas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Runas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Runas.
   */
  distinct?: Prisma.RunaScalarFieldEnum | Prisma.RunaScalarFieldEnum[]
}

/**
 * Runa findFirstOrThrow
 */
export type RunaFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Runa
   */
  select?: Prisma.RunaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Runa
   */
  omit?: Prisma.RunaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RunaInclude<ExtArgs> | null
  /**
   * Filter, which Runa to fetch.
   */
  where?: Prisma.RunaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Runas to fetch.
   */
  orderBy?: Prisma.RunaOrderByWithRelationInput | Prisma.RunaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Runas.
   */
  cursor?: Prisma.RunaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Runas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Runas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Runas.
   */
  distinct?: Prisma.RunaScalarFieldEnum | Prisma.RunaScalarFieldEnum[]
}

/**
 * Runa findMany
 */
export type RunaFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Runa
   */
  select?: Prisma.RunaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Runa
   */
  omit?: Prisma.RunaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RunaInclude<ExtArgs> | null
  /**
   * Filter, which Runas to fetch.
   */
  where?: Prisma.RunaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Runas to fetch.
   */
  orderBy?: Prisma.RunaOrderByWithRelationInput | Prisma.RunaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Runas.
   */
  cursor?: Prisma.RunaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Runas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Runas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Runas.
   */
  distinct?: Prisma.RunaScalarFieldEnum | Prisma.RunaScalarFieldEnum[]
}

/**
 * Runa create
 */
export type RunaCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Runa
   */
  select?: Prisma.RunaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Runa
   */
  omit?: Prisma.RunaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RunaInclude<ExtArgs> | null
  /**
   * The data needed to create a Runa.
   */
  data: Prisma.XOR<Prisma.RunaCreateInput, Prisma.RunaUncheckedCreateInput>
}

/**
 * Runa createMany
 */
export type RunaCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Runas.
   */
  data: Prisma.RunaCreateManyInput | Prisma.RunaCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Runa createManyAndReturn
 */
export type RunaCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Runa
   */
  select?: Prisma.RunaSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Runa
   */
  omit?: Prisma.RunaOmit<ExtArgs> | null
  /**
   * The data used to create many Runas.
   */
  data: Prisma.RunaCreateManyInput | Prisma.RunaCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RunaIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Runa update
 */
export type RunaUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Runa
   */
  select?: Prisma.RunaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Runa
   */
  omit?: Prisma.RunaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RunaInclude<ExtArgs> | null
  /**
   * The data needed to update a Runa.
   */
  data: Prisma.XOR<Prisma.RunaUpdateInput, Prisma.RunaUncheckedUpdateInput>
  /**
   * Choose, which Runa to update.
   */
  where: Prisma.RunaWhereUniqueInput
}

/**
 * Runa updateMany
 */
export type RunaUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Runas.
   */
  data: Prisma.XOR<Prisma.RunaUpdateManyMutationInput, Prisma.RunaUncheckedUpdateManyInput>
  /**
   * Filter which Runas to update
   */
  where?: Prisma.RunaWhereInput
  /**
   * Limit how many Runas to update.
   */
  limit?: number
}

/**
 * Runa updateManyAndReturn
 */
export type RunaUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Runa
   */
  select?: Prisma.RunaSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Runa
   */
  omit?: Prisma.RunaOmit<ExtArgs> | null
  /**
   * The data used to update Runas.
   */
  data: Prisma.XOR<Prisma.RunaUpdateManyMutationInput, Prisma.RunaUncheckedUpdateManyInput>
  /**
   * Filter which Runas to update
   */
  where?: Prisma.RunaWhereInput
  /**
   * Limit how many Runas to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RunaIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Runa upsert
 */
export type RunaUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Runa
   */
  select?: Prisma.RunaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Runa
   */
  omit?: Prisma.RunaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RunaInclude<ExtArgs> | null
  /**
   * The filter to search for the Runa to update in case it exists.
   */
  where: Prisma.RunaWhereUniqueInput
  /**
   * In case the Runa found by the `where` argument doesn't exist, create a new Runa with this data.
   */
  create: Prisma.XOR<Prisma.RunaCreateInput, Prisma.RunaUncheckedCreateInput>
  /**
   * In case the Runa was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.RunaUpdateInput, Prisma.RunaUncheckedUpdateInput>
}

/**
 * Runa delete
 */
export type RunaDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Runa
   */
  select?: Prisma.RunaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Runa
   */
  omit?: Prisma.RunaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RunaInclude<ExtArgs> | null
  /**
   * Filter which Runa to delete.
   */
  where: Prisma.RunaWhereUniqueInput
}

/**
 * Runa deleteMany
 */
export type RunaDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Runas to delete
   */
  where?: Prisma.RunaWhereInput
  /**
   * Limit how many Runas to delete.
   */
  limit?: number
}

/**
 * Runa.keystone
 */
export type Runa$keystoneArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sezione_Runa
   */
  select?: Prisma.Sezione_RunaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sezione_Runa
   */
  omit?: Prisma.Sezione_RunaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Sezione_RunaInclude<ExtArgs> | null
  where?: Prisma.Sezione_RunaWhereInput
  orderBy?: Prisma.Sezione_RunaOrderByWithRelationInput | Prisma.Sezione_RunaOrderByWithRelationInput[]
  cursor?: Prisma.Sezione_RunaWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Sezione_RunaScalarFieldEnum | Prisma.Sezione_RunaScalarFieldEnum[]
}

/**
 * Runa.Prima
 */
export type Runa$PrimaArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sezione_Runa
   */
  select?: Prisma.Sezione_RunaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sezione_Runa
   */
  omit?: Prisma.Sezione_RunaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Sezione_RunaInclude<ExtArgs> | null
  where?: Prisma.Sezione_RunaWhereInput
  orderBy?: Prisma.Sezione_RunaOrderByWithRelationInput | Prisma.Sezione_RunaOrderByWithRelationInput[]
  cursor?: Prisma.Sezione_RunaWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Sezione_RunaScalarFieldEnum | Prisma.Sezione_RunaScalarFieldEnum[]
}

/**
 * Runa.Centrale
 */
export type Runa$CentraleArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sezione_Runa
   */
  select?: Prisma.Sezione_RunaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sezione_Runa
   */
  omit?: Prisma.Sezione_RunaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Sezione_RunaInclude<ExtArgs> | null
  where?: Prisma.Sezione_RunaWhereInput
  orderBy?: Prisma.Sezione_RunaOrderByWithRelationInput | Prisma.Sezione_RunaOrderByWithRelationInput[]
  cursor?: Prisma.Sezione_RunaWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Sezione_RunaScalarFieldEnum | Prisma.Sezione_RunaScalarFieldEnum[]
}

/**
 * Runa.Ultima
 */
export type Runa$UltimaArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sezione_Runa
   */
  select?: Prisma.Sezione_RunaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sezione_Runa
   */
  omit?: Prisma.Sezione_RunaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Sezione_RunaInclude<ExtArgs> | null
  where?: Prisma.Sezione_RunaWhereInput
  orderBy?: Prisma.Sezione_RunaOrderByWithRelationInput | Prisma.Sezione_RunaOrderByWithRelationInput[]
  cursor?: Prisma.Sezione_RunaWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Sezione_RunaScalarFieldEnum | Prisma.Sezione_RunaScalarFieldEnum[]
}

/**
 * Runa without action
 */
export type RunaDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Runa
   */
  select?: Prisma.RunaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Runa
   */
  omit?: Prisma.RunaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RunaInclude<ExtArgs> | null
}
