
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SetBase` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model SetBase
 * 
 */
export type SetBaseModel = runtime.Types.Result.DefaultSelection<Prisma.$SetBasePayload>

export type AggregateSetBase = {
  _count: SetBaseCountAggregateOutputType | null
  _avg: SetBaseAvgAggregateOutputType | null
  _sum: SetBaseSumAggregateOutputType | null
  _min: SetBaseMinAggregateOutputType | null
  _max: SetBaseMaxAggregateOutputType | null
}

export type SetBaseAvgAggregateOutputType = {
  IdStatistiche: number | null
  Vita: number | null
  VitaPerLivello: number | null
  Mana: number | null
  ManaPerLivello: number | null
  Velocità_di_movimento: number | null
  Armatura: number | null
  ArmaturaPerLivello: number | null
  ResistenzaMagica: number | null
  ResistenzaMagicaPerLivello: number | null
  Gittata: number | null
  RigenerazioneVita: number | null
  RigenerazioneMana: number | null
  RigenerazioneManaPerLivello: number | null
  Critico: number | null
  CriticoPerLivello: number | null
  Attacco: number | null
  AttaccoPerLivello: number | null
  VelocitàDiAttacco: number | null
  VelocitàDiAttaccoPerLivello: number | null
  AttaccoMagico: number | null
}

export type SetBaseSumAggregateOutputType = {
  IdStatistiche: number | null
  Vita: number | null
  VitaPerLivello: number | null
  Mana: number | null
  ManaPerLivello: number | null
  Velocità_di_movimento: number | null
  Armatura: number | null
  ArmaturaPerLivello: number | null
  ResistenzaMagica: number | null
  ResistenzaMagicaPerLivello: number | null
  Gittata: number | null
  RigenerazioneVita: number | null
  RigenerazioneMana: number | null
  RigenerazioneManaPerLivello: number | null
  Critico: number | null
  CriticoPerLivello: number | null
  Attacco: number | null
  AttaccoPerLivello: number | null
  VelocitàDiAttacco: number | null
  VelocitàDiAttaccoPerLivello: number | null
  AttaccoMagico: number | null
}

export type SetBaseMinAggregateOutputType = {
  IdStatistiche: number | null
  Vita: number | null
  VitaPerLivello: number | null
  Mana: number | null
  ManaPerLivello: number | null
  Velocità_di_movimento: number | null
  Armatura: number | null
  ArmaturaPerLivello: number | null
  ResistenzaMagica: number | null
  ResistenzaMagicaPerLivello: number | null
  Gittata: number | null
  RigenerazioneVita: number | null
  RigenerazioneMana: number | null
  RigenerazioneManaPerLivello: number | null
  Critico: number | null
  CriticoPerLivello: number | null
  Attacco: number | null
  AttaccoPerLivello: number | null
  VelocitàDiAttacco: number | null
  VelocitàDiAttaccoPerLivello: number | null
  AttaccoMagico: number | null
}

export type SetBaseMaxAggregateOutputType = {
  IdStatistiche: number | null
  Vita: number | null
  VitaPerLivello: number | null
  Mana: number | null
  ManaPerLivello: number | null
  Velocità_di_movimento: number | null
  Armatura: number | null
  ArmaturaPerLivello: number | null
  ResistenzaMagica: number | null
  ResistenzaMagicaPerLivello: number | null
  Gittata: number | null
  RigenerazioneVita: number | null
  RigenerazioneMana: number | null
  RigenerazioneManaPerLivello: number | null
  Critico: number | null
  CriticoPerLivello: number | null
  Attacco: number | null
  AttaccoPerLivello: number | null
  VelocitàDiAttacco: number | null
  VelocitàDiAttaccoPerLivello: number | null
  AttaccoMagico: number | null
}

export type SetBaseCountAggregateOutputType = {
  IdStatistiche: number
  Vita: number
  VitaPerLivello: number
  Mana: number
  ManaPerLivello: number
  Velocità_di_movimento: number
  Armatura: number
  ArmaturaPerLivello: number
  ResistenzaMagica: number
  ResistenzaMagicaPerLivello: number
  Gittata: number
  RigenerazioneVita: number
  RigenerazioneMana: number
  RigenerazioneManaPerLivello: number
  Critico: number
  CriticoPerLivello: number
  Attacco: number
  AttaccoPerLivello: number
  VelocitàDiAttacco: number
  VelocitàDiAttaccoPerLivello: number
  AttaccoMagico: number
  _all: number
}


export type SetBaseAvgAggregateInputType = {
  IdStatistiche?: true
  Vita?: true
  VitaPerLivello?: true
  Mana?: true
  ManaPerLivello?: true
  Velocità_di_movimento?: true
  Armatura?: true
  ArmaturaPerLivello?: true
  ResistenzaMagica?: true
  ResistenzaMagicaPerLivello?: true
  Gittata?: true
  RigenerazioneVita?: true
  RigenerazioneMana?: true
  RigenerazioneManaPerLivello?: true
  Critico?: true
  CriticoPerLivello?: true
  Attacco?: true
  AttaccoPerLivello?: true
  VelocitàDiAttacco?: true
  VelocitàDiAttaccoPerLivello?: true
  AttaccoMagico?: true
}

export type SetBaseSumAggregateInputType = {
  IdStatistiche?: true
  Vita?: true
  VitaPerLivello?: true
  Mana?: true
  ManaPerLivello?: true
  Velocità_di_movimento?: true
  Armatura?: true
  ArmaturaPerLivello?: true
  ResistenzaMagica?: true
  ResistenzaMagicaPerLivello?: true
  Gittata?: true
  RigenerazioneVita?: true
  RigenerazioneMana?: true
  RigenerazioneManaPerLivello?: true
  Critico?: true
  CriticoPerLivello?: true
  Attacco?: true
  AttaccoPerLivello?: true
  VelocitàDiAttacco?: true
  VelocitàDiAttaccoPerLivello?: true
  AttaccoMagico?: true
}

export type SetBaseMinAggregateInputType = {
  IdStatistiche?: true
  Vita?: true
  VitaPerLivello?: true
  Mana?: true
  ManaPerLivello?: true
  Velocità_di_movimento?: true
  Armatura?: true
  ArmaturaPerLivello?: true
  ResistenzaMagica?: true
  ResistenzaMagicaPerLivello?: true
  Gittata?: true
  RigenerazioneVita?: true
  RigenerazioneMana?: true
  RigenerazioneManaPerLivello?: true
  Critico?: true
  CriticoPerLivello?: true
  Attacco?: true
  AttaccoPerLivello?: true
  VelocitàDiAttacco?: true
  VelocitàDiAttaccoPerLivello?: true
  AttaccoMagico?: true
}

export type SetBaseMaxAggregateInputType = {
  IdStatistiche?: true
  Vita?: true
  VitaPerLivello?: true
  Mana?: true
  ManaPerLivello?: true
  Velocità_di_movimento?: true
  Armatura?: true
  ArmaturaPerLivello?: true
  ResistenzaMagica?: true
  ResistenzaMagicaPerLivello?: true
  Gittata?: true
  RigenerazioneVita?: true
  RigenerazioneMana?: true
  RigenerazioneManaPerLivello?: true
  Critico?: true
  CriticoPerLivello?: true
  Attacco?: true
  AttaccoPerLivello?: true
  VelocitàDiAttacco?: true
  VelocitàDiAttaccoPerLivello?: true
  AttaccoMagico?: true
}

export type SetBaseCountAggregateInputType = {
  IdStatistiche?: true
  Vita?: true
  VitaPerLivello?: true
  Mana?: true
  ManaPerLivello?: true
  Velocità_di_movimento?: true
  Armatura?: true
  ArmaturaPerLivello?: true
  ResistenzaMagica?: true
  ResistenzaMagicaPerLivello?: true
  Gittata?: true
  RigenerazioneVita?: true
  RigenerazioneMana?: true
  RigenerazioneManaPerLivello?: true
  Critico?: true
  CriticoPerLivello?: true
  Attacco?: true
  AttaccoPerLivello?: true
  VelocitàDiAttacco?: true
  VelocitàDiAttaccoPerLivello?: true
  AttaccoMagico?: true
  _all?: true
}

export type SetBaseAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SetBase to aggregate.
   */
  where?: Prisma.SetBaseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SetBases to fetch.
   */
  orderBy?: Prisma.SetBaseOrderByWithRelationInput | Prisma.SetBaseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SetBaseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SetBases from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SetBases.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SetBases
  **/
  _count?: true | SetBaseCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: SetBaseAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: SetBaseSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SetBaseMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SetBaseMaxAggregateInputType
}

export type GetSetBaseAggregateType<T extends SetBaseAggregateArgs> = {
      [P in keyof T & keyof AggregateSetBase]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSetBase[P]>
    : Prisma.GetScalarType<T[P], AggregateSetBase[P]>
}




export type SetBaseGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SetBaseWhereInput
  orderBy?: Prisma.SetBaseOrderByWithAggregationInput | Prisma.SetBaseOrderByWithAggregationInput[]
  by: Prisma.SetBaseScalarFieldEnum[] | Prisma.SetBaseScalarFieldEnum
  having?: Prisma.SetBaseScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SetBaseCountAggregateInputType | true
  _avg?: SetBaseAvgAggregateInputType
  _sum?: SetBaseSumAggregateInputType
  _min?: SetBaseMinAggregateInputType
  _max?: SetBaseMaxAggregateInputType
}

export type SetBaseGroupByOutputType = {
  IdStatistiche: number
  Vita: number
  VitaPerLivello: number
  Mana: number
  ManaPerLivello: number
  Velocità_di_movimento: number
  Armatura: number
  ArmaturaPerLivello: number
  ResistenzaMagica: number
  ResistenzaMagicaPerLivello: number
  Gittata: number
  RigenerazioneVita: number
  RigenerazioneMana: number
  RigenerazioneManaPerLivello: number
  Critico: number
  CriticoPerLivello: number
  Attacco: number
  AttaccoPerLivello: number
  VelocitàDiAttacco: number
  VelocitàDiAttaccoPerLivello: number
  AttaccoMagico: number
  _count: SetBaseCountAggregateOutputType | null
  _avg: SetBaseAvgAggregateOutputType | null
  _sum: SetBaseSumAggregateOutputType | null
  _min: SetBaseMinAggregateOutputType | null
  _max: SetBaseMaxAggregateOutputType | null
}

export type GetSetBaseGroupByPayload<T extends SetBaseGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SetBaseGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SetBaseGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SetBaseGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SetBaseGroupByOutputType[P]>
      }
    >
  >



export type SetBaseWhereInput = {
  AND?: Prisma.SetBaseWhereInput | Prisma.SetBaseWhereInput[]
  OR?: Prisma.SetBaseWhereInput[]
  NOT?: Prisma.SetBaseWhereInput | Prisma.SetBaseWhereInput[]
  IdStatistiche?: Prisma.IntFilter<"SetBase"> | number
  Vita?: Prisma.IntFilter<"SetBase"> | number
  VitaPerLivello?: Prisma.IntFilter<"SetBase"> | number
  Mana?: Prisma.IntFilter<"SetBase"> | number
  ManaPerLivello?: Prisma.IntFilter<"SetBase"> | number
  Velocità_di_movimento?: Prisma.IntFilter<"SetBase"> | number
  Armatura?: Prisma.FloatFilter<"SetBase"> | number
  ArmaturaPerLivello?: Prisma.FloatFilter<"SetBase"> | number
  ResistenzaMagica?: Prisma.FloatFilter<"SetBase"> | number
  ResistenzaMagicaPerLivello?: Prisma.FloatFilter<"SetBase"> | number
  Gittata?: Prisma.IntFilter<"SetBase"> | number
  RigenerazioneVita?: Prisma.FloatFilter<"SetBase"> | number
  RigenerazioneMana?: Prisma.FloatFilter<"SetBase"> | number
  RigenerazioneManaPerLivello?: Prisma.FloatFilter<"SetBase"> | number
  Critico?: Prisma.FloatFilter<"SetBase"> | number
  CriticoPerLivello?: Prisma.FloatFilter<"SetBase"> | number
  Attacco?: Prisma.FloatFilter<"SetBase"> | number
  AttaccoPerLivello?: Prisma.FloatFilter<"SetBase"> | number
  VelocitàDiAttacco?: Prisma.FloatFilter<"SetBase"> | number
  VelocitàDiAttaccoPerLivello?: Prisma.FloatFilter<"SetBase"> | number
  AttaccoMagico?: Prisma.IntFilter<"SetBase"> | number
  Champ?: Prisma.CampioneListRelationFilter
  Item?: Prisma.OggettoListRelationFilter
}

export type SetBaseOrderByWithRelationInput = {
  IdStatistiche?: Prisma.SortOrder
  Vita?: Prisma.SortOrder
  VitaPerLivello?: Prisma.SortOrder
  Mana?: Prisma.SortOrder
  ManaPerLivello?: Prisma.SortOrder
  Velocità_di_movimento?: Prisma.SortOrder
  Armatura?: Prisma.SortOrder
  ArmaturaPerLivello?: Prisma.SortOrder
  ResistenzaMagica?: Prisma.SortOrder
  ResistenzaMagicaPerLivello?: Prisma.SortOrder
  Gittata?: Prisma.SortOrder
  RigenerazioneVita?: Prisma.SortOrder
  RigenerazioneMana?: Prisma.SortOrder
  RigenerazioneManaPerLivello?: Prisma.SortOrder
  Critico?: Prisma.SortOrder
  CriticoPerLivello?: Prisma.SortOrder
  Attacco?: Prisma.SortOrder
  AttaccoPerLivello?: Prisma.SortOrder
  VelocitàDiAttacco?: Prisma.SortOrder
  VelocitàDiAttaccoPerLivello?: Prisma.SortOrder
  AttaccoMagico?: Prisma.SortOrder
  Champ?: Prisma.CampioneOrderByRelationAggregateInput
  Item?: Prisma.OggettoOrderByRelationAggregateInput
}

export type SetBaseWhereUniqueInput = Prisma.AtLeast<{
  IdStatistiche?: number
  AND?: Prisma.SetBaseWhereInput | Prisma.SetBaseWhereInput[]
  OR?: Prisma.SetBaseWhereInput[]
  NOT?: Prisma.SetBaseWhereInput | Prisma.SetBaseWhereInput[]
  Vita?: Prisma.IntFilter<"SetBase"> | number
  VitaPerLivello?: Prisma.IntFilter<"SetBase"> | number
  Mana?: Prisma.IntFilter<"SetBase"> | number
  ManaPerLivello?: Prisma.IntFilter<"SetBase"> | number
  Velocità_di_movimento?: Prisma.IntFilter<"SetBase"> | number
  Armatura?: Prisma.FloatFilter<"SetBase"> | number
  ArmaturaPerLivello?: Prisma.FloatFilter<"SetBase"> | number
  ResistenzaMagica?: Prisma.FloatFilter<"SetBase"> | number
  ResistenzaMagicaPerLivello?: Prisma.FloatFilter<"SetBase"> | number
  Gittata?: Prisma.IntFilter<"SetBase"> | number
  RigenerazioneVita?: Prisma.FloatFilter<"SetBase"> | number
  RigenerazioneMana?: Prisma.FloatFilter<"SetBase"> | number
  RigenerazioneManaPerLivello?: Prisma.FloatFilter<"SetBase"> | number
  Critico?: Prisma.FloatFilter<"SetBase"> | number
  CriticoPerLivello?: Prisma.FloatFilter<"SetBase"> | number
  Attacco?: Prisma.FloatFilter<"SetBase"> | number
  AttaccoPerLivello?: Prisma.FloatFilter<"SetBase"> | number
  VelocitàDiAttacco?: Prisma.FloatFilter<"SetBase"> | number
  VelocitàDiAttaccoPerLivello?: Prisma.FloatFilter<"SetBase"> | number
  AttaccoMagico?: Prisma.IntFilter<"SetBase"> | number
  Champ?: Prisma.CampioneListRelationFilter
  Item?: Prisma.OggettoListRelationFilter
}, "IdStatistiche">

export type SetBaseOrderByWithAggregationInput = {
  IdStatistiche?: Prisma.SortOrder
  Vita?: Prisma.SortOrder
  VitaPerLivello?: Prisma.SortOrder
  Mana?: Prisma.SortOrder
  ManaPerLivello?: Prisma.SortOrder
  Velocità_di_movimento?: Prisma.SortOrder
  Armatura?: Prisma.SortOrder
  ArmaturaPerLivello?: Prisma.SortOrder
  ResistenzaMagica?: Prisma.SortOrder
  ResistenzaMagicaPerLivello?: Prisma.SortOrder
  Gittata?: Prisma.SortOrder
  RigenerazioneVita?: Prisma.SortOrder
  RigenerazioneMana?: Prisma.SortOrder
  RigenerazioneManaPerLivello?: Prisma.SortOrder
  Critico?: Prisma.SortOrder
  CriticoPerLivello?: Prisma.SortOrder
  Attacco?: Prisma.SortOrder
  AttaccoPerLivello?: Prisma.SortOrder
  VelocitàDiAttacco?: Prisma.SortOrder
  VelocitàDiAttaccoPerLivello?: Prisma.SortOrder
  AttaccoMagico?: Prisma.SortOrder
  _count?: Prisma.SetBaseCountOrderByAggregateInput
  _avg?: Prisma.SetBaseAvgOrderByAggregateInput
  _max?: Prisma.SetBaseMaxOrderByAggregateInput
  _min?: Prisma.SetBaseMinOrderByAggregateInput
  _sum?: Prisma.SetBaseSumOrderByAggregateInput
}

export type SetBaseScalarWhereWithAggregatesInput = {
  AND?: Prisma.SetBaseScalarWhereWithAggregatesInput | Prisma.SetBaseScalarWhereWithAggregatesInput[]
  OR?: Prisma.SetBaseScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SetBaseScalarWhereWithAggregatesInput | Prisma.SetBaseScalarWhereWithAggregatesInput[]
  IdStatistiche?: Prisma.IntWithAggregatesFilter<"SetBase"> | number
  Vita?: Prisma.IntWithAggregatesFilter<"SetBase"> | number
  VitaPerLivello?: Prisma.IntWithAggregatesFilter<"SetBase"> | number
  Mana?: Prisma.IntWithAggregatesFilter<"SetBase"> | number
  ManaPerLivello?: Prisma.IntWithAggregatesFilter<"SetBase"> | number
  Velocità_di_movimento?: Prisma.IntWithAggregatesFilter<"SetBase"> | number
  Armatura?: Prisma.FloatWithAggregatesFilter<"SetBase"> | number
  ArmaturaPerLivello?: Prisma.FloatWithAggregatesFilter<"SetBase"> | number
  ResistenzaMagica?: Prisma.FloatWithAggregatesFilter<"SetBase"> | number
  ResistenzaMagicaPerLivello?: Prisma.FloatWithAggregatesFilter<"SetBase"> | number
  Gittata?: Prisma.IntWithAggregatesFilter<"SetBase"> | number
  RigenerazioneVita?: Prisma.FloatWithAggregatesFilter<"SetBase"> | number
  RigenerazioneMana?: Prisma.FloatWithAggregatesFilter<"SetBase"> | number
  RigenerazioneManaPerLivello?: Prisma.FloatWithAggregatesFilter<"SetBase"> | number
  Critico?: Prisma.FloatWithAggregatesFilter<"SetBase"> | number
  CriticoPerLivello?: Prisma.FloatWithAggregatesFilter<"SetBase"> | number
  Attacco?: Prisma.FloatWithAggregatesFilter<"SetBase"> | number
  AttaccoPerLivello?: Prisma.FloatWithAggregatesFilter<"SetBase"> | number
  VelocitàDiAttacco?: Prisma.FloatWithAggregatesFilter<"SetBase"> | number
  VelocitàDiAttaccoPerLivello?: Prisma.FloatWithAggregatesFilter<"SetBase"> | number
  AttaccoMagico?: Prisma.IntWithAggregatesFilter<"SetBase"> | number
}

export type SetBaseCreateInput = {
  IdStatistiche: number
  Vita: number
  VitaPerLivello: number
  Mana: number
  ManaPerLivello: number
  Velocità_di_movimento: number
  Armatura: number
  ArmaturaPerLivello: number
  ResistenzaMagica: number
  ResistenzaMagicaPerLivello: number
  Gittata: number
  RigenerazioneVita: number
  RigenerazioneMana: number
  RigenerazioneManaPerLivello: number
  Critico: number
  CriticoPerLivello: number
  Attacco: number
  AttaccoPerLivello: number
  VelocitàDiAttacco: number
  VelocitàDiAttaccoPerLivello: number
  AttaccoMagico?: number
  Champ?: Prisma.CampioneCreateNestedManyWithoutStatsInput
  Item?: Prisma.OggettoCreateNestedManyWithoutStatsInput
}

export type SetBaseUncheckedCreateInput = {
  IdStatistiche: number
  Vita: number
  VitaPerLivello: number
  Mana: number
  ManaPerLivello: number
  Velocità_di_movimento: number
  Armatura: number
  ArmaturaPerLivello: number
  ResistenzaMagica: number
  ResistenzaMagicaPerLivello: number
  Gittata: number
  RigenerazioneVita: number
  RigenerazioneMana: number
  RigenerazioneManaPerLivello: number
  Critico: number
  CriticoPerLivello: number
  Attacco: number
  AttaccoPerLivello: number
  VelocitàDiAttacco: number
  VelocitàDiAttaccoPerLivello: number
  AttaccoMagico?: number
  Champ?: Prisma.CampioneUncheckedCreateNestedManyWithoutStatsInput
  Item?: Prisma.OggettoUncheckedCreateNestedManyWithoutStatsInput
}

export type SetBaseUpdateInput = {
  IdStatistiche?: Prisma.IntFieldUpdateOperationsInput | number
  Vita?: Prisma.IntFieldUpdateOperationsInput | number
  VitaPerLivello?: Prisma.IntFieldUpdateOperationsInput | number
  Mana?: Prisma.IntFieldUpdateOperationsInput | number
  ManaPerLivello?: Prisma.IntFieldUpdateOperationsInput | number
  Velocità_di_movimento?: Prisma.IntFieldUpdateOperationsInput | number
  Armatura?: Prisma.FloatFieldUpdateOperationsInput | number
  ArmaturaPerLivello?: Prisma.FloatFieldUpdateOperationsInput | number
  ResistenzaMagica?: Prisma.FloatFieldUpdateOperationsInput | number
  ResistenzaMagicaPerLivello?: Prisma.FloatFieldUpdateOperationsInput | number
  Gittata?: Prisma.IntFieldUpdateOperationsInput | number
  RigenerazioneVita?: Prisma.FloatFieldUpdateOperationsInput | number
  RigenerazioneMana?: Prisma.FloatFieldUpdateOperationsInput | number
  RigenerazioneManaPerLivello?: Prisma.FloatFieldUpdateOperationsInput | number
  Critico?: Prisma.FloatFieldUpdateOperationsInput | number
  CriticoPerLivello?: Prisma.FloatFieldUpdateOperationsInput | number
  Attacco?: Prisma.FloatFieldUpdateOperationsInput | number
  AttaccoPerLivello?: Prisma.FloatFieldUpdateOperationsInput | number
  VelocitàDiAttacco?: Prisma.FloatFieldUpdateOperationsInput | number
  VelocitàDiAttaccoPerLivello?: Prisma.FloatFieldUpdateOperationsInput | number
  AttaccoMagico?: Prisma.IntFieldUpdateOperationsInput | number
  Champ?: Prisma.CampioneUpdateManyWithoutStatsNestedInput
  Item?: Prisma.OggettoUpdateManyWithoutStatsNestedInput
}

export type SetBaseUncheckedUpdateInput = {
  IdStatistiche?: Prisma.IntFieldUpdateOperationsInput | number
  Vita?: Prisma.IntFieldUpdateOperationsInput | number
  VitaPerLivello?: Prisma.IntFieldUpdateOperationsInput | number
  Mana?: Prisma.IntFieldUpdateOperationsInput | number
  ManaPerLivello?: Prisma.IntFieldUpdateOperationsInput | number
  Velocità_di_movimento?: Prisma.IntFieldUpdateOperationsInput | number
  Armatura?: Prisma.FloatFieldUpdateOperationsInput | number
  ArmaturaPerLivello?: Prisma.FloatFieldUpdateOperationsInput | number
  ResistenzaMagica?: Prisma.FloatFieldUpdateOperationsInput | number
  ResistenzaMagicaPerLivello?: Prisma.FloatFieldUpdateOperationsInput | number
  Gittata?: Prisma.IntFieldUpdateOperationsInput | number
  RigenerazioneVita?: Prisma.FloatFieldUpdateOperationsInput | number
  RigenerazioneMana?: Prisma.FloatFieldUpdateOperationsInput | number
  RigenerazioneManaPerLivello?: Prisma.FloatFieldUpdateOperationsInput | number
  Critico?: Prisma.FloatFieldUpdateOperationsInput | number
  CriticoPerLivello?: Prisma.FloatFieldUpdateOperationsInput | number
  Attacco?: Prisma.FloatFieldUpdateOperationsInput | number
  AttaccoPerLivello?: Prisma.FloatFieldUpdateOperationsInput | number
  VelocitàDiAttacco?: Prisma.FloatFieldUpdateOperationsInput | number
  VelocitàDiAttaccoPerLivello?: Prisma.FloatFieldUpdateOperationsInput | number
  AttaccoMagico?: Prisma.IntFieldUpdateOperationsInput | number
  Champ?: Prisma.CampioneUncheckedUpdateManyWithoutStatsNestedInput
  Item?: Prisma.OggettoUncheckedUpdateManyWithoutStatsNestedInput
}

export type SetBaseCreateManyInput = {
  IdStatistiche: number
  Vita: number
  VitaPerLivello: number
  Mana: number
  ManaPerLivello: number
  Velocità_di_movimento: number
  Armatura: number
  ArmaturaPerLivello: number
  ResistenzaMagica: number
  ResistenzaMagicaPerLivello: number
  Gittata: number
  RigenerazioneVita: number
  RigenerazioneMana: number
  RigenerazioneManaPerLivello: number
  Critico: number
  CriticoPerLivello: number
  Attacco: number
  AttaccoPerLivello: number
  VelocitàDiAttacco: number
  VelocitàDiAttaccoPerLivello: number
  AttaccoMagico?: number
}

export type SetBaseUpdateManyMutationInput = {
  IdStatistiche?: Prisma.IntFieldUpdateOperationsInput | number
  Vita?: Prisma.IntFieldUpdateOperationsInput | number
  VitaPerLivello?: Prisma.IntFieldUpdateOperationsInput | number
  Mana?: Prisma.IntFieldUpdateOperationsInput | number
  ManaPerLivello?: Prisma.IntFieldUpdateOperationsInput | number
  Velocità_di_movimento?: Prisma.IntFieldUpdateOperationsInput | number
  Armatura?: Prisma.FloatFieldUpdateOperationsInput | number
  ArmaturaPerLivello?: Prisma.FloatFieldUpdateOperationsInput | number
  ResistenzaMagica?: Prisma.FloatFieldUpdateOperationsInput | number
  ResistenzaMagicaPerLivello?: Prisma.FloatFieldUpdateOperationsInput | number
  Gittata?: Prisma.IntFieldUpdateOperationsInput | number
  RigenerazioneVita?: Prisma.FloatFieldUpdateOperationsInput | number
  RigenerazioneMana?: Prisma.FloatFieldUpdateOperationsInput | number
  RigenerazioneManaPerLivello?: Prisma.FloatFieldUpdateOperationsInput | number
  Critico?: Prisma.FloatFieldUpdateOperationsInput | number
  CriticoPerLivello?: Prisma.FloatFieldUpdateOperationsInput | number
  Attacco?: Prisma.FloatFieldUpdateOperationsInput | number
  AttaccoPerLivello?: Prisma.FloatFieldUpdateOperationsInput | number
  VelocitàDiAttacco?: Prisma.FloatFieldUpdateOperationsInput | number
  VelocitàDiAttaccoPerLivello?: Prisma.FloatFieldUpdateOperationsInput | number
  AttaccoMagico?: Prisma.IntFieldUpdateOperationsInput | number
}

export type SetBaseUncheckedUpdateManyInput = {
  IdStatistiche?: Prisma.IntFieldUpdateOperationsInput | number
  Vita?: Prisma.IntFieldUpdateOperationsInput | number
  VitaPerLivello?: Prisma.IntFieldUpdateOperationsInput | number
  Mana?: Prisma.IntFieldUpdateOperationsInput | number
  ManaPerLivello?: Prisma.IntFieldUpdateOperationsInput | number
  Velocità_di_movimento?: Prisma.IntFieldUpdateOperationsInput | number
  Armatura?: Prisma.FloatFieldUpdateOperationsInput | number
  ArmaturaPerLivello?: Prisma.FloatFieldUpdateOperationsInput | number
  ResistenzaMagica?: Prisma.FloatFieldUpdateOperationsInput | number
  ResistenzaMagicaPerLivello?: Prisma.FloatFieldUpdateOperationsInput | number
  Gittata?: Prisma.IntFieldUpdateOperationsInput | number
  RigenerazioneVita?: Prisma.FloatFieldUpdateOperationsInput | number
  RigenerazioneMana?: Prisma.FloatFieldUpdateOperationsInput | number
  RigenerazioneManaPerLivello?: Prisma.FloatFieldUpdateOperationsInput | number
  Critico?: Prisma.FloatFieldUpdateOperationsInput | number
  CriticoPerLivello?: Prisma.FloatFieldUpdateOperationsInput | number
  Attacco?: Prisma.FloatFieldUpdateOperationsInput | number
  AttaccoPerLivello?: Prisma.FloatFieldUpdateOperationsInput | number
  VelocitàDiAttacco?: Prisma.FloatFieldUpdateOperationsInput | number
  VelocitàDiAttaccoPerLivello?: Prisma.FloatFieldUpdateOperationsInput | number
  AttaccoMagico?: Prisma.IntFieldUpdateOperationsInput | number
}

export type SetBaseScalarRelationFilter = {
  is?: Prisma.SetBaseWhereInput
  isNot?: Prisma.SetBaseWhereInput
}

export type SetBaseCountOrderByAggregateInput = {
  IdStatistiche?: Prisma.SortOrder
  Vita?: Prisma.SortOrder
  VitaPerLivello?: Prisma.SortOrder
  Mana?: Prisma.SortOrder
  ManaPerLivello?: Prisma.SortOrder
  Velocità_di_movimento?: Prisma.SortOrder
  Armatura?: Prisma.SortOrder
  ArmaturaPerLivello?: Prisma.SortOrder
  ResistenzaMagica?: Prisma.SortOrder
  ResistenzaMagicaPerLivello?: Prisma.SortOrder
  Gittata?: Prisma.SortOrder
  RigenerazioneVita?: Prisma.SortOrder
  RigenerazioneMana?: Prisma.SortOrder
  RigenerazioneManaPerLivello?: Prisma.SortOrder
  Critico?: Prisma.SortOrder
  CriticoPerLivello?: Prisma.SortOrder
  Attacco?: Prisma.SortOrder
  AttaccoPerLivello?: Prisma.SortOrder
  VelocitàDiAttacco?: Prisma.SortOrder
  VelocitàDiAttaccoPerLivello?: Prisma.SortOrder
  AttaccoMagico?: Prisma.SortOrder
}

export type SetBaseAvgOrderByAggregateInput = {
  IdStatistiche?: Prisma.SortOrder
  Vita?: Prisma.SortOrder
  VitaPerLivello?: Prisma.SortOrder
  Mana?: Prisma.SortOrder
  ManaPerLivello?: Prisma.SortOrder
  Velocità_di_movimento?: Prisma.SortOrder
  Armatura?: Prisma.SortOrder
  ArmaturaPerLivello?: Prisma.SortOrder
  ResistenzaMagica?: Prisma.SortOrder
  ResistenzaMagicaPerLivello?: Prisma.SortOrder
  Gittata?: Prisma.SortOrder
  RigenerazioneVita?: Prisma.SortOrder
  RigenerazioneMana?: Prisma.SortOrder
  RigenerazioneManaPerLivello?: Prisma.SortOrder
  Critico?: Prisma.SortOrder
  CriticoPerLivello?: Prisma.SortOrder
  Attacco?: Prisma.SortOrder
  AttaccoPerLivello?: Prisma.SortOrder
  VelocitàDiAttacco?: Prisma.SortOrder
  VelocitàDiAttaccoPerLivello?: Prisma.SortOrder
  AttaccoMagico?: Prisma.SortOrder
}

export type SetBaseMaxOrderByAggregateInput = {
  IdStatistiche?: Prisma.SortOrder
  Vita?: Prisma.SortOrder
  VitaPerLivello?: Prisma.SortOrder
  Mana?: Prisma.SortOrder
  ManaPerLivello?: Prisma.SortOrder
  Velocità_di_movimento?: Prisma.SortOrder
  Armatura?: Prisma.SortOrder
  ArmaturaPerLivello?: Prisma.SortOrder
  ResistenzaMagica?: Prisma.SortOrder
  ResistenzaMagicaPerLivello?: Prisma.SortOrder
  Gittata?: Prisma.SortOrder
  RigenerazioneVita?: Prisma.SortOrder
  RigenerazioneMana?: Prisma.SortOrder
  RigenerazioneManaPerLivello?: Prisma.SortOrder
  Critico?: Prisma.SortOrder
  CriticoPerLivello?: Prisma.SortOrder
  Attacco?: Prisma.SortOrder
  AttaccoPerLivello?: Prisma.SortOrder
  VelocitàDiAttacco?: Prisma.SortOrder
  VelocitàDiAttaccoPerLivello?: Prisma.SortOrder
  AttaccoMagico?: Prisma.SortOrder
}

export type SetBaseMinOrderByAggregateInput = {
  IdStatistiche?: Prisma.SortOrder
  Vita?: Prisma.SortOrder
  VitaPerLivello?: Prisma.SortOrder
  Mana?: Prisma.SortOrder
  ManaPerLivello?: Prisma.SortOrder
  Velocità_di_movimento?: Prisma.SortOrder
  Armatura?: Prisma.SortOrder
  ArmaturaPerLivello?: Prisma.SortOrder
  ResistenzaMagica?: Prisma.SortOrder
  ResistenzaMagicaPerLivello?: Prisma.SortOrder
  Gittata?: Prisma.SortOrder
  RigenerazioneVita?: Prisma.SortOrder
  RigenerazioneMana?: Prisma.SortOrder
  RigenerazioneManaPerLivello?: Prisma.SortOrder
  Critico?: Prisma.SortOrder
  CriticoPerLivello?: Prisma.SortOrder
  Attacco?: Prisma.SortOrder
  AttaccoPerLivello?: Prisma.SortOrder
  VelocitàDiAttacco?: Prisma.SortOrder
  VelocitàDiAttaccoPerLivello?: Prisma.SortOrder
  AttaccoMagico?: Prisma.SortOrder
}

export type SetBaseSumOrderByAggregateInput = {
  IdStatistiche?: Prisma.SortOrder
  Vita?: Prisma.SortOrder
  VitaPerLivello?: Prisma.SortOrder
  Mana?: Prisma.SortOrder
  ManaPerLivello?: Prisma.SortOrder
  Velocità_di_movimento?: Prisma.SortOrder
  Armatura?: Prisma.SortOrder
  ArmaturaPerLivello?: Prisma.SortOrder
  ResistenzaMagica?: Prisma.SortOrder
  ResistenzaMagicaPerLivello?: Prisma.SortOrder
  Gittata?: Prisma.SortOrder
  RigenerazioneVita?: Prisma.SortOrder
  RigenerazioneMana?: Prisma.SortOrder
  RigenerazioneManaPerLivello?: Prisma.SortOrder
  Critico?: Prisma.SortOrder
  CriticoPerLivello?: Prisma.SortOrder
  Attacco?: Prisma.SortOrder
  AttaccoPerLivello?: Prisma.SortOrder
  VelocitàDiAttacco?: Prisma.SortOrder
  VelocitàDiAttaccoPerLivello?: Prisma.SortOrder
  AttaccoMagico?: Prisma.SortOrder
}

export type SetBaseCreateNestedOneWithoutChampInput = {
  create?: Prisma.XOR<Prisma.SetBaseCreateWithoutChampInput, Prisma.SetBaseUncheckedCreateWithoutChampInput>
  connectOrCreate?: Prisma.SetBaseCreateOrConnectWithoutChampInput
  connect?: Prisma.SetBaseWhereUniqueInput
}

export type SetBaseUpdateOneRequiredWithoutChampNestedInput = {
  create?: Prisma.XOR<Prisma.SetBaseCreateWithoutChampInput, Prisma.SetBaseUncheckedCreateWithoutChampInput>
  connectOrCreate?: Prisma.SetBaseCreateOrConnectWithoutChampInput
  upsert?: Prisma.SetBaseUpsertWithoutChampInput
  connect?: Prisma.SetBaseWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SetBaseUpdateToOneWithWhereWithoutChampInput, Prisma.SetBaseUpdateWithoutChampInput>, Prisma.SetBaseUncheckedUpdateWithoutChampInput>
}

export type SetBaseCreateNestedOneWithoutItemInput = {
  create?: Prisma.XOR<Prisma.SetBaseCreateWithoutItemInput, Prisma.SetBaseUncheckedCreateWithoutItemInput>
  connectOrCreate?: Prisma.SetBaseCreateOrConnectWithoutItemInput
  connect?: Prisma.SetBaseWhereUniqueInput
}

export type SetBaseUpdateOneRequiredWithoutItemNestedInput = {
  create?: Prisma.XOR<Prisma.SetBaseCreateWithoutItemInput, Prisma.SetBaseUncheckedCreateWithoutItemInput>
  connectOrCreate?: Prisma.SetBaseCreateOrConnectWithoutItemInput
  upsert?: Prisma.SetBaseUpsertWithoutItemInput
  connect?: Prisma.SetBaseWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SetBaseUpdateToOneWithWhereWithoutItemInput, Prisma.SetBaseUpdateWithoutItemInput>, Prisma.SetBaseUncheckedUpdateWithoutItemInput>
}

export type SetBaseCreateWithoutChampInput = {
  IdStatistiche: number
  Vita: number
  VitaPerLivello: number
  Mana: number
  ManaPerLivello: number
  Velocità_di_movimento: number
  Armatura: number
  ArmaturaPerLivello: number
  ResistenzaMagica: number
  ResistenzaMagicaPerLivello: number
  Gittata: number
  RigenerazioneVita: number
  RigenerazioneMana: number
  RigenerazioneManaPerLivello: number
  Critico: number
  CriticoPerLivello: number
  Attacco: number
  AttaccoPerLivello: number
  VelocitàDiAttacco: number
  VelocitàDiAttaccoPerLivello: number
  AttaccoMagico?: number
  Item?: Prisma.OggettoCreateNestedManyWithoutStatsInput
}

export type SetBaseUncheckedCreateWithoutChampInput = {
  IdStatistiche: number
  Vita: number
  VitaPerLivello: number
  Mana: number
  ManaPerLivello: number
  Velocità_di_movimento: number
  Armatura: number
  ArmaturaPerLivello: number
  ResistenzaMagica: number
  ResistenzaMagicaPerLivello: number
  Gittata: number
  RigenerazioneVita: number
  RigenerazioneMana: number
  RigenerazioneManaPerLivello: number
  Critico: number
  CriticoPerLivello: number
  Attacco: number
  AttaccoPerLivello: number
  VelocitàDiAttacco: number
  VelocitàDiAttaccoPerLivello: number
  AttaccoMagico?: number
  Item?: Prisma.OggettoUncheckedCreateNestedManyWithoutStatsInput
}

export type SetBaseCreateOrConnectWithoutChampInput = {
  where: Prisma.SetBaseWhereUniqueInput
  create: Prisma.XOR<Prisma.SetBaseCreateWithoutChampInput, Prisma.SetBaseUncheckedCreateWithoutChampInput>
}

export type SetBaseUpsertWithoutChampInput = {
  update: Prisma.XOR<Prisma.SetBaseUpdateWithoutChampInput, Prisma.SetBaseUncheckedUpdateWithoutChampInput>
  create: Prisma.XOR<Prisma.SetBaseCreateWithoutChampInput, Prisma.SetBaseUncheckedCreateWithoutChampInput>
  where?: Prisma.SetBaseWhereInput
}

export type SetBaseUpdateToOneWithWhereWithoutChampInput = {
  where?: Prisma.SetBaseWhereInput
  data: Prisma.XOR<Prisma.SetBaseUpdateWithoutChampInput, Prisma.SetBaseUncheckedUpdateWithoutChampInput>
}

export type SetBaseUpdateWithoutChampInput = {
  IdStatistiche?: Prisma.IntFieldUpdateOperationsInput | number
  Vita?: Prisma.IntFieldUpdateOperationsInput | number
  VitaPerLivello?: Prisma.IntFieldUpdateOperationsInput | number
  Mana?: Prisma.IntFieldUpdateOperationsInput | number
  ManaPerLivello?: Prisma.IntFieldUpdateOperationsInput | number
  Velocità_di_movimento?: Prisma.IntFieldUpdateOperationsInput | number
  Armatura?: Prisma.FloatFieldUpdateOperationsInput | number
  ArmaturaPerLivello?: Prisma.FloatFieldUpdateOperationsInput | number
  ResistenzaMagica?: Prisma.FloatFieldUpdateOperationsInput | number
  ResistenzaMagicaPerLivello?: Prisma.FloatFieldUpdateOperationsInput | number
  Gittata?: Prisma.IntFieldUpdateOperationsInput | number
  RigenerazioneVita?: Prisma.FloatFieldUpdateOperationsInput | number
  RigenerazioneMana?: Prisma.FloatFieldUpdateOperationsInput | number
  RigenerazioneManaPerLivello?: Prisma.FloatFieldUpdateOperationsInput | number
  Critico?: Prisma.FloatFieldUpdateOperationsInput | number
  CriticoPerLivello?: Prisma.FloatFieldUpdateOperationsInput | number
  Attacco?: Prisma.FloatFieldUpdateOperationsInput | number
  AttaccoPerLivello?: Prisma.FloatFieldUpdateOperationsInput | number
  VelocitàDiAttacco?: Prisma.FloatFieldUpdateOperationsInput | number
  VelocitàDiAttaccoPerLivello?: Prisma.FloatFieldUpdateOperationsInput | number
  AttaccoMagico?: Prisma.IntFieldUpdateOperationsInput | number
  Item?: Prisma.OggettoUpdateManyWithoutStatsNestedInput
}

export type SetBaseUncheckedUpdateWithoutChampInput = {
  IdStatistiche?: Prisma.IntFieldUpdateOperationsInput | number
  Vita?: Prisma.IntFieldUpdateOperationsInput | number
  VitaPerLivello?: Prisma.IntFieldUpdateOperationsInput | number
  Mana?: Prisma.IntFieldUpdateOperationsInput | number
  ManaPerLivello?: Prisma.IntFieldUpdateOperationsInput | number
  Velocità_di_movimento?: Prisma.IntFieldUpdateOperationsInput | number
  Armatura?: Prisma.FloatFieldUpdateOperationsInput | number
  ArmaturaPerLivello?: Prisma.FloatFieldUpdateOperationsInput | number
  ResistenzaMagica?: Prisma.FloatFieldUpdateOperationsInput | number
  ResistenzaMagicaPerLivello?: Prisma.FloatFieldUpdateOperationsInput | number
  Gittata?: Prisma.IntFieldUpdateOperationsInput | number
  RigenerazioneVita?: Prisma.FloatFieldUpdateOperationsInput | number
  RigenerazioneMana?: Prisma.FloatFieldUpdateOperationsInput | number
  RigenerazioneManaPerLivello?: Prisma.FloatFieldUpdateOperationsInput | number
  Critico?: Prisma.FloatFieldUpdateOperationsInput | number
  CriticoPerLivello?: Prisma.FloatFieldUpdateOperationsInput | number
  Attacco?: Prisma.FloatFieldUpdateOperationsInput | number
  AttaccoPerLivello?: Prisma.FloatFieldUpdateOperationsInput | number
  VelocitàDiAttacco?: Prisma.FloatFieldUpdateOperationsInput | number
  VelocitàDiAttaccoPerLivello?: Prisma.FloatFieldUpdateOperationsInput | number
  AttaccoMagico?: Prisma.IntFieldUpdateOperationsInput | number
  Item?: Prisma.OggettoUncheckedUpdateManyWithoutStatsNestedInput
}

export type SetBaseCreateWithoutItemInput = {
  IdStatistiche: number
  Vita: number
  VitaPerLivello: number
  Mana: number
  ManaPerLivello: number
  Velocità_di_movimento: number
  Armatura: number
  ArmaturaPerLivello: number
  ResistenzaMagica: number
  ResistenzaMagicaPerLivello: number
  Gittata: number
  RigenerazioneVita: number
  RigenerazioneMana: number
  RigenerazioneManaPerLivello: number
  Critico: number
  CriticoPerLivello: number
  Attacco: number
  AttaccoPerLivello: number
  VelocitàDiAttacco: number
  VelocitàDiAttaccoPerLivello: number
  AttaccoMagico?: number
  Champ?: Prisma.CampioneCreateNestedManyWithoutStatsInput
}

export type SetBaseUncheckedCreateWithoutItemInput = {
  IdStatistiche: number
  Vita: number
  VitaPerLivello: number
  Mana: number
  ManaPerLivello: number
  Velocità_di_movimento: number
  Armatura: number
  ArmaturaPerLivello: number
  ResistenzaMagica: number
  ResistenzaMagicaPerLivello: number
  Gittata: number
  RigenerazioneVita: number
  RigenerazioneMana: number
  RigenerazioneManaPerLivello: number
  Critico: number
  CriticoPerLivello: number
  Attacco: number
  AttaccoPerLivello: number
  VelocitàDiAttacco: number
  VelocitàDiAttaccoPerLivello: number
  AttaccoMagico?: number
  Champ?: Prisma.CampioneUncheckedCreateNestedManyWithoutStatsInput
}

export type SetBaseCreateOrConnectWithoutItemInput = {
  where: Prisma.SetBaseWhereUniqueInput
  create: Prisma.XOR<Prisma.SetBaseCreateWithoutItemInput, Prisma.SetBaseUncheckedCreateWithoutItemInput>
}

export type SetBaseUpsertWithoutItemInput = {
  update: Prisma.XOR<Prisma.SetBaseUpdateWithoutItemInput, Prisma.SetBaseUncheckedUpdateWithoutItemInput>
  create: Prisma.XOR<Prisma.SetBaseCreateWithoutItemInput, Prisma.SetBaseUncheckedCreateWithoutItemInput>
  where?: Prisma.SetBaseWhereInput
}

export type SetBaseUpdateToOneWithWhereWithoutItemInput = {
  where?: Prisma.SetBaseWhereInput
  data: Prisma.XOR<Prisma.SetBaseUpdateWithoutItemInput, Prisma.SetBaseUncheckedUpdateWithoutItemInput>
}

export type SetBaseUpdateWithoutItemInput = {
  IdStatistiche?: Prisma.IntFieldUpdateOperationsInput | number
  Vita?: Prisma.IntFieldUpdateOperationsInput | number
  VitaPerLivello?: Prisma.IntFieldUpdateOperationsInput | number
  Mana?: Prisma.IntFieldUpdateOperationsInput | number
  ManaPerLivello?: Prisma.IntFieldUpdateOperationsInput | number
  Velocità_di_movimento?: Prisma.IntFieldUpdateOperationsInput | number
  Armatura?: Prisma.FloatFieldUpdateOperationsInput | number
  ArmaturaPerLivello?: Prisma.FloatFieldUpdateOperationsInput | number
  ResistenzaMagica?: Prisma.FloatFieldUpdateOperationsInput | number
  ResistenzaMagicaPerLivello?: Prisma.FloatFieldUpdateOperationsInput | number
  Gittata?: Prisma.IntFieldUpdateOperationsInput | number
  RigenerazioneVita?: Prisma.FloatFieldUpdateOperationsInput | number
  RigenerazioneMana?: Prisma.FloatFieldUpdateOperationsInput | number
  RigenerazioneManaPerLivello?: Prisma.FloatFieldUpdateOperationsInput | number
  Critico?: Prisma.FloatFieldUpdateOperationsInput | number
  CriticoPerLivello?: Prisma.FloatFieldUpdateOperationsInput | number
  Attacco?: Prisma.FloatFieldUpdateOperationsInput | number
  AttaccoPerLivello?: Prisma.FloatFieldUpdateOperationsInput | number
  VelocitàDiAttacco?: Prisma.FloatFieldUpdateOperationsInput | number
  VelocitàDiAttaccoPerLivello?: Prisma.FloatFieldUpdateOperationsInput | number
  AttaccoMagico?: Prisma.IntFieldUpdateOperationsInput | number
  Champ?: Prisma.CampioneUpdateManyWithoutStatsNestedInput
}

export type SetBaseUncheckedUpdateWithoutItemInput = {
  IdStatistiche?: Prisma.IntFieldUpdateOperationsInput | number
  Vita?: Prisma.IntFieldUpdateOperationsInput | number
  VitaPerLivello?: Prisma.IntFieldUpdateOperationsInput | number
  Mana?: Prisma.IntFieldUpdateOperationsInput | number
  ManaPerLivello?: Prisma.IntFieldUpdateOperationsInput | number
  Velocità_di_movimento?: Prisma.IntFieldUpdateOperationsInput | number
  Armatura?: Prisma.FloatFieldUpdateOperationsInput | number
  ArmaturaPerLivello?: Prisma.FloatFieldUpdateOperationsInput | number
  ResistenzaMagica?: Prisma.FloatFieldUpdateOperationsInput | number
  ResistenzaMagicaPerLivello?: Prisma.FloatFieldUpdateOperationsInput | number
  Gittata?: Prisma.IntFieldUpdateOperationsInput | number
  RigenerazioneVita?: Prisma.FloatFieldUpdateOperationsInput | number
  RigenerazioneMana?: Prisma.FloatFieldUpdateOperationsInput | number
  RigenerazioneManaPerLivello?: Prisma.FloatFieldUpdateOperationsInput | number
  Critico?: Prisma.FloatFieldUpdateOperationsInput | number
  CriticoPerLivello?: Prisma.FloatFieldUpdateOperationsInput | number
  Attacco?: Prisma.FloatFieldUpdateOperationsInput | number
  AttaccoPerLivello?: Prisma.FloatFieldUpdateOperationsInput | number
  VelocitàDiAttacco?: Prisma.FloatFieldUpdateOperationsInput | number
  VelocitàDiAttaccoPerLivello?: Prisma.FloatFieldUpdateOperationsInput | number
  AttaccoMagico?: Prisma.IntFieldUpdateOperationsInput | number
  Champ?: Prisma.CampioneUncheckedUpdateManyWithoutStatsNestedInput
}


/**
 * Count Type SetBaseCountOutputType
 */

export type SetBaseCountOutputType = {
  Champ: number
  Item: number
}

export type SetBaseCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Champ?: boolean | SetBaseCountOutputTypeCountChampArgs
  Item?: boolean | SetBaseCountOutputTypeCountItemArgs
}

/**
 * SetBaseCountOutputType without action
 */
export type SetBaseCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SetBaseCountOutputType
   */
  select?: Prisma.SetBaseCountOutputTypeSelect<ExtArgs> | null
}

/**
 * SetBaseCountOutputType without action
 */
export type SetBaseCountOutputTypeCountChampArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CampioneWhereInput
}

/**
 * SetBaseCountOutputType without action
 */
export type SetBaseCountOutputTypeCountItemArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OggettoWhereInput
}


export type SetBaseSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  IdStatistiche?: boolean
  Vita?: boolean
  VitaPerLivello?: boolean
  Mana?: boolean
  ManaPerLivello?: boolean
  Velocità_di_movimento?: boolean
  Armatura?: boolean
  ArmaturaPerLivello?: boolean
  ResistenzaMagica?: boolean
  ResistenzaMagicaPerLivello?: boolean
  Gittata?: boolean
  RigenerazioneVita?: boolean
  RigenerazioneMana?: boolean
  RigenerazioneManaPerLivello?: boolean
  Critico?: boolean
  CriticoPerLivello?: boolean
  Attacco?: boolean
  AttaccoPerLivello?: boolean
  VelocitàDiAttacco?: boolean
  VelocitàDiAttaccoPerLivello?: boolean
  AttaccoMagico?: boolean
  Champ?: boolean | Prisma.SetBase$ChampArgs<ExtArgs>
  Item?: boolean | Prisma.SetBase$ItemArgs<ExtArgs>
  _count?: boolean | Prisma.SetBaseCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["setBase"]>

export type SetBaseSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  IdStatistiche?: boolean
  Vita?: boolean
  VitaPerLivello?: boolean
  Mana?: boolean
  ManaPerLivello?: boolean
  Velocità_di_movimento?: boolean
  Armatura?: boolean
  ArmaturaPerLivello?: boolean
  ResistenzaMagica?: boolean
  ResistenzaMagicaPerLivello?: boolean
  Gittata?: boolean
  RigenerazioneVita?: boolean
  RigenerazioneMana?: boolean
  RigenerazioneManaPerLivello?: boolean
  Critico?: boolean
  CriticoPerLivello?: boolean
  Attacco?: boolean
  AttaccoPerLivello?: boolean
  VelocitàDiAttacco?: boolean
  VelocitàDiAttaccoPerLivello?: boolean
  AttaccoMagico?: boolean
}, ExtArgs["result"]["setBase"]>

export type SetBaseSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  IdStatistiche?: boolean
  Vita?: boolean
  VitaPerLivello?: boolean
  Mana?: boolean
  ManaPerLivello?: boolean
  Velocità_di_movimento?: boolean
  Armatura?: boolean
  ArmaturaPerLivello?: boolean
  ResistenzaMagica?: boolean
  ResistenzaMagicaPerLivello?: boolean
  Gittata?: boolean
  RigenerazioneVita?: boolean
  RigenerazioneMana?: boolean
  RigenerazioneManaPerLivello?: boolean
  Critico?: boolean
  CriticoPerLivello?: boolean
  Attacco?: boolean
  AttaccoPerLivello?: boolean
  VelocitàDiAttacco?: boolean
  VelocitàDiAttaccoPerLivello?: boolean
  AttaccoMagico?: boolean
}, ExtArgs["result"]["setBase"]>

export type SetBaseSelectScalar = {
  IdStatistiche?: boolean
  Vita?: boolean
  VitaPerLivello?: boolean
  Mana?: boolean
  ManaPerLivello?: boolean
  Velocità_di_movimento?: boolean
  Armatura?: boolean
  ArmaturaPerLivello?: boolean
  ResistenzaMagica?: boolean
  ResistenzaMagicaPerLivello?: boolean
  Gittata?: boolean
  RigenerazioneVita?: boolean
  RigenerazioneMana?: boolean
  RigenerazioneManaPerLivello?: boolean
  Critico?: boolean
  CriticoPerLivello?: boolean
  Attacco?: boolean
  AttaccoPerLivello?: boolean
  VelocitàDiAttacco?: boolean
  VelocitàDiAttaccoPerLivello?: boolean
  AttaccoMagico?: boolean
}

export type SetBaseOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"IdStatistiche" | "Vita" | "VitaPerLivello" | "Mana" | "ManaPerLivello" | "Velocità_di_movimento" | "Armatura" | "ArmaturaPerLivello" | "ResistenzaMagica" | "ResistenzaMagicaPerLivello" | "Gittata" | "RigenerazioneVita" | "RigenerazioneMana" | "RigenerazioneManaPerLivello" | "Critico" | "CriticoPerLivello" | "Attacco" | "AttaccoPerLivello" | "VelocitàDiAttacco" | "VelocitàDiAttaccoPerLivello" | "AttaccoMagico", ExtArgs["result"]["setBase"]>
export type SetBaseInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Champ?: boolean | Prisma.SetBase$ChampArgs<ExtArgs>
  Item?: boolean | Prisma.SetBase$ItemArgs<ExtArgs>
  _count?: boolean | Prisma.SetBaseCountOutputTypeDefaultArgs<ExtArgs>
}
export type SetBaseIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type SetBaseIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $SetBasePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SetBase"
  objects: {
    Champ: Prisma.$CampionePayload<ExtArgs>[]
    Item: Prisma.$OggettoPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    IdStatistiche: number
    Vita: number
    VitaPerLivello: number
    Mana: number
    ManaPerLivello: number
    Velocità_di_movimento: number
    Armatura: number
    ArmaturaPerLivello: number
    ResistenzaMagica: number
    ResistenzaMagicaPerLivello: number
    Gittata: number
    RigenerazioneVita: number
    RigenerazioneMana: number
    RigenerazioneManaPerLivello: number
    Critico: number
    CriticoPerLivello: number
    Attacco: number
    AttaccoPerLivello: number
    VelocitàDiAttacco: number
    VelocitàDiAttaccoPerLivello: number
    AttaccoMagico: number
  }, ExtArgs["result"]["setBase"]>
  composites: {}
}

export type SetBaseGetPayload<S extends boolean | null | undefined | SetBaseDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SetBasePayload, S>

export type SetBaseCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SetBaseFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SetBaseCountAggregateInputType | true
  }

export interface SetBaseDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SetBase'], meta: { name: 'SetBase' } }
  /**
   * Find zero or one SetBase that matches the filter.
   * @param {SetBaseFindUniqueArgs} args - Arguments to find a SetBase
   * @example
   * // Get one SetBase
   * const setBase = await prisma.setBase.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SetBaseFindUniqueArgs>(args: Prisma.SelectSubset<T, SetBaseFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SetBaseClient<runtime.Types.Result.GetResult<Prisma.$SetBasePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SetBase that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SetBaseFindUniqueOrThrowArgs} args - Arguments to find a SetBase
   * @example
   * // Get one SetBase
   * const setBase = await prisma.setBase.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SetBaseFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SetBaseFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SetBaseClient<runtime.Types.Result.GetResult<Prisma.$SetBasePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SetBase that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SetBaseFindFirstArgs} args - Arguments to find a SetBase
   * @example
   * // Get one SetBase
   * const setBase = await prisma.setBase.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SetBaseFindFirstArgs>(args?: Prisma.SelectSubset<T, SetBaseFindFirstArgs<ExtArgs>>): Prisma.Prisma__SetBaseClient<runtime.Types.Result.GetResult<Prisma.$SetBasePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SetBase that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SetBaseFindFirstOrThrowArgs} args - Arguments to find a SetBase
   * @example
   * // Get one SetBase
   * const setBase = await prisma.setBase.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SetBaseFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SetBaseFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SetBaseClient<runtime.Types.Result.GetResult<Prisma.$SetBasePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SetBases that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SetBaseFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SetBases
   * const setBases = await prisma.setBase.findMany()
   * 
   * // Get first 10 SetBases
   * const setBases = await prisma.setBase.findMany({ take: 10 })
   * 
   * // Only select the `IdStatistiche`
   * const setBaseWithIdStatisticheOnly = await prisma.setBase.findMany({ select: { IdStatistiche: true } })
   * 
   */
  findMany<T extends SetBaseFindManyArgs>(args?: Prisma.SelectSubset<T, SetBaseFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SetBasePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SetBase.
   * @param {SetBaseCreateArgs} args - Arguments to create a SetBase.
   * @example
   * // Create one SetBase
   * const SetBase = await prisma.setBase.create({
   *   data: {
   *     // ... data to create a SetBase
   *   }
   * })
   * 
   */
  create<T extends SetBaseCreateArgs>(args: Prisma.SelectSubset<T, SetBaseCreateArgs<ExtArgs>>): Prisma.Prisma__SetBaseClient<runtime.Types.Result.GetResult<Prisma.$SetBasePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SetBases.
   * @param {SetBaseCreateManyArgs} args - Arguments to create many SetBases.
   * @example
   * // Create many SetBases
   * const setBase = await prisma.setBase.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SetBaseCreateManyArgs>(args?: Prisma.SelectSubset<T, SetBaseCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SetBases and returns the data saved in the database.
   * @param {SetBaseCreateManyAndReturnArgs} args - Arguments to create many SetBases.
   * @example
   * // Create many SetBases
   * const setBase = await prisma.setBase.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SetBases and only return the `IdStatistiche`
   * const setBaseWithIdStatisticheOnly = await prisma.setBase.createManyAndReturn({
   *   select: { IdStatistiche: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SetBaseCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SetBaseCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SetBasePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SetBase.
   * @param {SetBaseDeleteArgs} args - Arguments to delete one SetBase.
   * @example
   * // Delete one SetBase
   * const SetBase = await prisma.setBase.delete({
   *   where: {
   *     // ... filter to delete one SetBase
   *   }
   * })
   * 
   */
  delete<T extends SetBaseDeleteArgs>(args: Prisma.SelectSubset<T, SetBaseDeleteArgs<ExtArgs>>): Prisma.Prisma__SetBaseClient<runtime.Types.Result.GetResult<Prisma.$SetBasePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SetBase.
   * @param {SetBaseUpdateArgs} args - Arguments to update one SetBase.
   * @example
   * // Update one SetBase
   * const setBase = await prisma.setBase.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SetBaseUpdateArgs>(args: Prisma.SelectSubset<T, SetBaseUpdateArgs<ExtArgs>>): Prisma.Prisma__SetBaseClient<runtime.Types.Result.GetResult<Prisma.$SetBasePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SetBases.
   * @param {SetBaseDeleteManyArgs} args - Arguments to filter SetBases to delete.
   * @example
   * // Delete a few SetBases
   * const { count } = await prisma.setBase.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SetBaseDeleteManyArgs>(args?: Prisma.SelectSubset<T, SetBaseDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SetBases.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SetBaseUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SetBases
   * const setBase = await prisma.setBase.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SetBaseUpdateManyArgs>(args: Prisma.SelectSubset<T, SetBaseUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SetBases and returns the data updated in the database.
   * @param {SetBaseUpdateManyAndReturnArgs} args - Arguments to update many SetBases.
   * @example
   * // Update many SetBases
   * const setBase = await prisma.setBase.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SetBases and only return the `IdStatistiche`
   * const setBaseWithIdStatisticheOnly = await prisma.setBase.updateManyAndReturn({
   *   select: { IdStatistiche: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SetBaseUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SetBaseUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SetBasePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SetBase.
   * @param {SetBaseUpsertArgs} args - Arguments to update or create a SetBase.
   * @example
   * // Update or create a SetBase
   * const setBase = await prisma.setBase.upsert({
   *   create: {
   *     // ... data to create a SetBase
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SetBase we want to update
   *   }
   * })
   */
  upsert<T extends SetBaseUpsertArgs>(args: Prisma.SelectSubset<T, SetBaseUpsertArgs<ExtArgs>>): Prisma.Prisma__SetBaseClient<runtime.Types.Result.GetResult<Prisma.$SetBasePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SetBases.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SetBaseCountArgs} args - Arguments to filter SetBases to count.
   * @example
   * // Count the number of SetBases
   * const count = await prisma.setBase.count({
   *   where: {
   *     // ... the filter for the SetBases we want to count
   *   }
   * })
  **/
  count<T extends SetBaseCountArgs>(
    args?: Prisma.Subset<T, SetBaseCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SetBaseCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SetBase.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SetBaseAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SetBaseAggregateArgs>(args: Prisma.Subset<T, SetBaseAggregateArgs>): Prisma.PrismaPromise<GetSetBaseAggregateType<T>>

  /**
   * Group by SetBase.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SetBaseGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SetBaseGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SetBaseGroupByArgs['orderBy'] }
      : { orderBy?: SetBaseGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SetBaseGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSetBaseGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SetBase model
 */
readonly fields: SetBaseFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SetBase.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SetBaseClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  Champ<T extends Prisma.SetBase$ChampArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SetBase$ChampArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CampionePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  Item<T extends Prisma.SetBase$ItemArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SetBase$ItemArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OggettoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SetBase model
 */
export interface SetBaseFieldRefs {
  readonly IdStatistiche: Prisma.FieldRef<"SetBase", 'Int'>
  readonly Vita: Prisma.FieldRef<"SetBase", 'Int'>
  readonly VitaPerLivello: Prisma.FieldRef<"SetBase", 'Int'>
  readonly Mana: Prisma.FieldRef<"SetBase", 'Int'>
  readonly ManaPerLivello: Prisma.FieldRef<"SetBase", 'Int'>
  readonly Velocità_di_movimento: Prisma.FieldRef<"SetBase", 'Int'>
  readonly Armatura: Prisma.FieldRef<"SetBase", 'Float'>
  readonly ArmaturaPerLivello: Prisma.FieldRef<"SetBase", 'Float'>
  readonly ResistenzaMagica: Prisma.FieldRef<"SetBase", 'Float'>
  readonly ResistenzaMagicaPerLivello: Prisma.FieldRef<"SetBase", 'Float'>
  readonly Gittata: Prisma.FieldRef<"SetBase", 'Int'>
  readonly RigenerazioneVita: Prisma.FieldRef<"SetBase", 'Float'>
  readonly RigenerazioneMana: Prisma.FieldRef<"SetBase", 'Float'>
  readonly RigenerazioneManaPerLivello: Prisma.FieldRef<"SetBase", 'Float'>
  readonly Critico: Prisma.FieldRef<"SetBase", 'Float'>
  readonly CriticoPerLivello: Prisma.FieldRef<"SetBase", 'Float'>
  readonly Attacco: Prisma.FieldRef<"SetBase", 'Float'>
  readonly AttaccoPerLivello: Prisma.FieldRef<"SetBase", 'Float'>
  readonly VelocitàDiAttacco: Prisma.FieldRef<"SetBase", 'Float'>
  readonly VelocitàDiAttaccoPerLivello: Prisma.FieldRef<"SetBase", 'Float'>
  readonly AttaccoMagico: Prisma.FieldRef<"SetBase", 'Int'>
}
    

// Custom InputTypes
/**
 * SetBase findUnique
 */
export type SetBaseFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SetBase
   */
  select?: Prisma.SetBaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SetBase
   */
  omit?: Prisma.SetBaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SetBaseInclude<ExtArgs> | null
  /**
   * Filter, which SetBase to fetch.
   */
  where: Prisma.SetBaseWhereUniqueInput
}

/**
 * SetBase findUniqueOrThrow
 */
export type SetBaseFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SetBase
   */
  select?: Prisma.SetBaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SetBase
   */
  omit?: Prisma.SetBaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SetBaseInclude<ExtArgs> | null
  /**
   * Filter, which SetBase to fetch.
   */
  where: Prisma.SetBaseWhereUniqueInput
}

/**
 * SetBase findFirst
 */
export type SetBaseFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SetBase
   */
  select?: Prisma.SetBaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SetBase
   */
  omit?: Prisma.SetBaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SetBaseInclude<ExtArgs> | null
  /**
   * Filter, which SetBase to fetch.
   */
  where?: Prisma.SetBaseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SetBases to fetch.
   */
  orderBy?: Prisma.SetBaseOrderByWithRelationInput | Prisma.SetBaseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SetBases.
   */
  cursor?: Prisma.SetBaseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SetBases from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SetBases.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SetBases.
   */
  distinct?: Prisma.SetBaseScalarFieldEnum | Prisma.SetBaseScalarFieldEnum[]
}

/**
 * SetBase findFirstOrThrow
 */
export type SetBaseFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SetBase
   */
  select?: Prisma.SetBaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SetBase
   */
  omit?: Prisma.SetBaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SetBaseInclude<ExtArgs> | null
  /**
   * Filter, which SetBase to fetch.
   */
  where?: Prisma.SetBaseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SetBases to fetch.
   */
  orderBy?: Prisma.SetBaseOrderByWithRelationInput | Prisma.SetBaseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SetBases.
   */
  cursor?: Prisma.SetBaseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SetBases from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SetBases.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SetBases.
   */
  distinct?: Prisma.SetBaseScalarFieldEnum | Prisma.SetBaseScalarFieldEnum[]
}

/**
 * SetBase findMany
 */
export type SetBaseFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SetBase
   */
  select?: Prisma.SetBaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SetBase
   */
  omit?: Prisma.SetBaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SetBaseInclude<ExtArgs> | null
  /**
   * Filter, which SetBases to fetch.
   */
  where?: Prisma.SetBaseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SetBases to fetch.
   */
  orderBy?: Prisma.SetBaseOrderByWithRelationInput | Prisma.SetBaseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SetBases.
   */
  cursor?: Prisma.SetBaseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SetBases from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SetBases.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SetBases.
   */
  distinct?: Prisma.SetBaseScalarFieldEnum | Prisma.SetBaseScalarFieldEnum[]
}

/**
 * SetBase create
 */
export type SetBaseCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SetBase
   */
  select?: Prisma.SetBaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SetBase
   */
  omit?: Prisma.SetBaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SetBaseInclude<ExtArgs> | null
  /**
   * The data needed to create a SetBase.
   */
  data: Prisma.XOR<Prisma.SetBaseCreateInput, Prisma.SetBaseUncheckedCreateInput>
}

/**
 * SetBase createMany
 */
export type SetBaseCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SetBases.
   */
  data: Prisma.SetBaseCreateManyInput | Prisma.SetBaseCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SetBase createManyAndReturn
 */
export type SetBaseCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SetBase
   */
  select?: Prisma.SetBaseSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SetBase
   */
  omit?: Prisma.SetBaseOmit<ExtArgs> | null
  /**
   * The data used to create many SetBases.
   */
  data: Prisma.SetBaseCreateManyInput | Prisma.SetBaseCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SetBase update
 */
export type SetBaseUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SetBase
   */
  select?: Prisma.SetBaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SetBase
   */
  omit?: Prisma.SetBaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SetBaseInclude<ExtArgs> | null
  /**
   * The data needed to update a SetBase.
   */
  data: Prisma.XOR<Prisma.SetBaseUpdateInput, Prisma.SetBaseUncheckedUpdateInput>
  /**
   * Choose, which SetBase to update.
   */
  where: Prisma.SetBaseWhereUniqueInput
}

/**
 * SetBase updateMany
 */
export type SetBaseUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SetBases.
   */
  data: Prisma.XOR<Prisma.SetBaseUpdateManyMutationInput, Prisma.SetBaseUncheckedUpdateManyInput>
  /**
   * Filter which SetBases to update
   */
  where?: Prisma.SetBaseWhereInput
  /**
   * Limit how many SetBases to update.
   */
  limit?: number
}

/**
 * SetBase updateManyAndReturn
 */
export type SetBaseUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SetBase
   */
  select?: Prisma.SetBaseSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SetBase
   */
  omit?: Prisma.SetBaseOmit<ExtArgs> | null
  /**
   * The data used to update SetBases.
   */
  data: Prisma.XOR<Prisma.SetBaseUpdateManyMutationInput, Prisma.SetBaseUncheckedUpdateManyInput>
  /**
   * Filter which SetBases to update
   */
  where?: Prisma.SetBaseWhereInput
  /**
   * Limit how many SetBases to update.
   */
  limit?: number
}

/**
 * SetBase upsert
 */
export type SetBaseUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SetBase
   */
  select?: Prisma.SetBaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SetBase
   */
  omit?: Prisma.SetBaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SetBaseInclude<ExtArgs> | null
  /**
   * The filter to search for the SetBase to update in case it exists.
   */
  where: Prisma.SetBaseWhereUniqueInput
  /**
   * In case the SetBase found by the `where` argument doesn't exist, create a new SetBase with this data.
   */
  create: Prisma.XOR<Prisma.SetBaseCreateInput, Prisma.SetBaseUncheckedCreateInput>
  /**
   * In case the SetBase was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SetBaseUpdateInput, Prisma.SetBaseUncheckedUpdateInput>
}

/**
 * SetBase delete
 */
export type SetBaseDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SetBase
   */
  select?: Prisma.SetBaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SetBase
   */
  omit?: Prisma.SetBaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SetBaseInclude<ExtArgs> | null
  /**
   * Filter which SetBase to delete.
   */
  where: Prisma.SetBaseWhereUniqueInput
}

/**
 * SetBase deleteMany
 */
export type SetBaseDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SetBases to delete
   */
  where?: Prisma.SetBaseWhereInput
  /**
   * Limit how many SetBases to delete.
   */
  limit?: number
}

/**
 * SetBase.Champ
 */
export type SetBase$ChampArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Campione
   */
  select?: Prisma.CampioneSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Campione
   */
  omit?: Prisma.CampioneOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CampioneInclude<ExtArgs> | null
  where?: Prisma.CampioneWhereInput
  orderBy?: Prisma.CampioneOrderByWithRelationInput | Prisma.CampioneOrderByWithRelationInput[]
  cursor?: Prisma.CampioneWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CampioneScalarFieldEnum | Prisma.CampioneScalarFieldEnum[]
}

/**
 * SetBase.Item
 */
export type SetBase$ItemArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Oggetto
   */
  select?: Prisma.OggettoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Oggetto
   */
  omit?: Prisma.OggettoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OggettoInclude<ExtArgs> | null
  where?: Prisma.OggettoWhereInput
  orderBy?: Prisma.OggettoOrderByWithRelationInput | Prisma.OggettoOrderByWithRelationInput[]
  cursor?: Prisma.OggettoWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.OggettoScalarFieldEnum | Prisma.OggettoScalarFieldEnum[]
}

/**
 * SetBase without action
 */
export type SetBaseDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SetBase
   */
  select?: Prisma.SetBaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SetBase
   */
  omit?: Prisma.SetBaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SetBaseInclude<ExtArgs> | null
}
