
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Sezione_Runa` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Sezione_Runa
 * 
 */
export type Sezione_RunaModel = runtime.Types.Result.DefaultSelection<Prisma.$Sezione_RunaPayload>

export type AggregateSezione_Runa = {
  _count: Sezione_RunaCountAggregateOutputType | null
  _avg: Sezione_RunaAvgAggregateOutputType | null
  _sum: Sezione_RunaSumAggregateOutputType | null
  _min: Sezione_RunaMinAggregateOutputType | null
  _max: Sezione_RunaMaxAggregateOutputType | null
}

export type Sezione_RunaAvgAggregateOutputType = {
  Id: number | null
}

export type Sezione_RunaSumAggregateOutputType = {
  Id: number | null
}

export type Sezione_RunaMinAggregateOutputType = {
  Id: number | null
  Pietrachiave: string | null
  RigaSuperiore: string | null
  RigaCentrale: string | null
  RigaInferiore: string | null
}

export type Sezione_RunaMaxAggregateOutputType = {
  Id: number | null
  Pietrachiave: string | null
  RigaSuperiore: string | null
  RigaCentrale: string | null
  RigaInferiore: string | null
}

export type Sezione_RunaCountAggregateOutputType = {
  Id: number
  Pietrachiave: number
  RigaSuperiore: number
  RigaCentrale: number
  RigaInferiore: number
  _all: number
}


export type Sezione_RunaAvgAggregateInputType = {
  Id?: true
}

export type Sezione_RunaSumAggregateInputType = {
  Id?: true
}

export type Sezione_RunaMinAggregateInputType = {
  Id?: true
  Pietrachiave?: true
  RigaSuperiore?: true
  RigaCentrale?: true
  RigaInferiore?: true
}

export type Sezione_RunaMaxAggregateInputType = {
  Id?: true
  Pietrachiave?: true
  RigaSuperiore?: true
  RigaCentrale?: true
  RigaInferiore?: true
}

export type Sezione_RunaCountAggregateInputType = {
  Id?: true
  Pietrachiave?: true
  RigaSuperiore?: true
  RigaCentrale?: true
  RigaInferiore?: true
  _all?: true
}

export type Sezione_RunaAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Sezione_Runa to aggregate.
   */
  where?: Prisma.Sezione_RunaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Sezione_Runas to fetch.
   */
  orderBy?: Prisma.Sezione_RunaOrderByWithRelationInput | Prisma.Sezione_RunaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.Sezione_RunaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Sezione_Runas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Sezione_Runas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Sezione_Runas
  **/
  _count?: true | Sezione_RunaCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Sezione_RunaAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Sezione_RunaSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Sezione_RunaMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Sezione_RunaMaxAggregateInputType
}

export type GetSezione_RunaAggregateType<T extends Sezione_RunaAggregateArgs> = {
      [P in keyof T & keyof AggregateSezione_Runa]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSezione_Runa[P]>
    : Prisma.GetScalarType<T[P], AggregateSezione_Runa[P]>
}




export type Sezione_RunaGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.Sezione_RunaWhereInput
  orderBy?: Prisma.Sezione_RunaOrderByWithAggregationInput | Prisma.Sezione_RunaOrderByWithAggregationInput[]
  by: Prisma.Sezione_RunaScalarFieldEnum[] | Prisma.Sezione_RunaScalarFieldEnum
  having?: Prisma.Sezione_RunaScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Sezione_RunaCountAggregateInputType | true
  _avg?: Sezione_RunaAvgAggregateInputType
  _sum?: Sezione_RunaSumAggregateInputType
  _min?: Sezione_RunaMinAggregateInputType
  _max?: Sezione_RunaMaxAggregateInputType
}

export type Sezione_RunaGroupByOutputType = {
  Id: number
  Pietrachiave: string
  RigaSuperiore: string
  RigaCentrale: string
  RigaInferiore: string
  _count: Sezione_RunaCountAggregateOutputType | null
  _avg: Sezione_RunaAvgAggregateOutputType | null
  _sum: Sezione_RunaSumAggregateOutputType | null
  _min: Sezione_RunaMinAggregateOutputType | null
  _max: Sezione_RunaMaxAggregateOutputType | null
}

export type GetSezione_RunaGroupByPayload<T extends Sezione_RunaGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Sezione_RunaGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Sezione_RunaGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Sezione_RunaGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Sezione_RunaGroupByOutputType[P]>
      }
    >
  >



export type Sezione_RunaWhereInput = {
  AND?: Prisma.Sezione_RunaWhereInput | Prisma.Sezione_RunaWhereInput[]
  OR?: Prisma.Sezione_RunaWhereInput[]
  NOT?: Prisma.Sezione_RunaWhereInput | Prisma.Sezione_RunaWhereInput[]
  Id?: Prisma.IntFilter<"Sezione_Runa"> | number
  Pietrachiave?: Prisma.StringFilter<"Sezione_Runa"> | string
  RigaSuperiore?: Prisma.StringFilter<"Sezione_Runa"> | string
  RigaCentrale?: Prisma.StringFilter<"Sezione_Runa"> | string
  RigaInferiore?: Prisma.StringFilter<"Sezione_Runa"> | string
  Shard?: Prisma.Pagina_RunaListRelationFilter
  Prim?: Prisma.Pagina_RunaListRelationFilter
  Secon?: Prisma.Pagina_RunaListRelationFilter
  Keystone?: Prisma.XOR<Prisma.RunaScalarRelationFilter, Prisma.RunaWhereInput>
  Middle?: Prisma.XOR<Prisma.RunaScalarRelationFilter, Prisma.RunaWhereInput>
  Lower?: Prisma.XOR<Prisma.RunaScalarRelationFilter, Prisma.RunaWhereInput>
  First?: Prisma.XOR<Prisma.RunaScalarRelationFilter, Prisma.RunaWhereInput>
}

export type Sezione_RunaOrderByWithRelationInput = {
  Id?: Prisma.SortOrder
  Pietrachiave?: Prisma.SortOrder
  RigaSuperiore?: Prisma.SortOrder
  RigaCentrale?: Prisma.SortOrder
  RigaInferiore?: Prisma.SortOrder
  Shard?: Prisma.Pagina_RunaOrderByRelationAggregateInput
  Prim?: Prisma.Pagina_RunaOrderByRelationAggregateInput
  Secon?: Prisma.Pagina_RunaOrderByRelationAggregateInput
  Keystone?: Prisma.RunaOrderByWithRelationInput
  Middle?: Prisma.RunaOrderByWithRelationInput
  Lower?: Prisma.RunaOrderByWithRelationInput
  First?: Prisma.RunaOrderByWithRelationInput
}

export type Sezione_RunaWhereUniqueInput = Prisma.AtLeast<{
  Id?: number
  AND?: Prisma.Sezione_RunaWhereInput | Prisma.Sezione_RunaWhereInput[]
  OR?: Prisma.Sezione_RunaWhereInput[]
  NOT?: Prisma.Sezione_RunaWhereInput | Prisma.Sezione_RunaWhereInput[]
  Pietrachiave?: Prisma.StringFilter<"Sezione_Runa"> | string
  RigaSuperiore?: Prisma.StringFilter<"Sezione_Runa"> | string
  RigaCentrale?: Prisma.StringFilter<"Sezione_Runa"> | string
  RigaInferiore?: Prisma.StringFilter<"Sezione_Runa"> | string
  Shard?: Prisma.Pagina_RunaListRelationFilter
  Prim?: Prisma.Pagina_RunaListRelationFilter
  Secon?: Prisma.Pagina_RunaListRelationFilter
  Keystone?: Prisma.XOR<Prisma.RunaScalarRelationFilter, Prisma.RunaWhereInput>
  Middle?: Prisma.XOR<Prisma.RunaScalarRelationFilter, Prisma.RunaWhereInput>
  Lower?: Prisma.XOR<Prisma.RunaScalarRelationFilter, Prisma.RunaWhereInput>
  First?: Prisma.XOR<Prisma.RunaScalarRelationFilter, Prisma.RunaWhereInput>
}, "Id">

export type Sezione_RunaOrderByWithAggregationInput = {
  Id?: Prisma.SortOrder
  Pietrachiave?: Prisma.SortOrder
  RigaSuperiore?: Prisma.SortOrder
  RigaCentrale?: Prisma.SortOrder
  RigaInferiore?: Prisma.SortOrder
  _count?: Prisma.Sezione_RunaCountOrderByAggregateInput
  _avg?: Prisma.Sezione_RunaAvgOrderByAggregateInput
  _max?: Prisma.Sezione_RunaMaxOrderByAggregateInput
  _min?: Prisma.Sezione_RunaMinOrderByAggregateInput
  _sum?: Prisma.Sezione_RunaSumOrderByAggregateInput
}

export type Sezione_RunaScalarWhereWithAggregatesInput = {
  AND?: Prisma.Sezione_RunaScalarWhereWithAggregatesInput | Prisma.Sezione_RunaScalarWhereWithAggregatesInput[]
  OR?: Prisma.Sezione_RunaScalarWhereWithAggregatesInput[]
  NOT?: Prisma.Sezione_RunaScalarWhereWithAggregatesInput | Prisma.Sezione_RunaScalarWhereWithAggregatesInput[]
  Id?: Prisma.IntWithAggregatesFilter<"Sezione_Runa"> | number
  Pietrachiave?: Prisma.StringWithAggregatesFilter<"Sezione_Runa"> | string
  RigaSuperiore?: Prisma.StringWithAggregatesFilter<"Sezione_Runa"> | string
  RigaCentrale?: Prisma.StringWithAggregatesFilter<"Sezione_Runa"> | string
  RigaInferiore?: Prisma.StringWithAggregatesFilter<"Sezione_Runa"> | string
}

export type Sezione_RunaCreateInput = {
  Id: number
  Shard?: Prisma.Pagina_RunaCreateNestedManyWithoutShardsInput
  Prim?: Prisma.Pagina_RunaCreateNestedManyWithoutPrincipaleInput
  Secon?: Prisma.Pagina_RunaCreateNestedManyWithoutSecondariaInput
  Keystone: Prisma.RunaCreateNestedOneWithoutKeystoneInput
  Middle: Prisma.RunaCreateNestedOneWithoutCentraleInput
  Lower: Prisma.RunaCreateNestedOneWithoutUltimaInput
  First: Prisma.RunaCreateNestedOneWithoutPrimaInput
}

export type Sezione_RunaUncheckedCreateInput = {
  Id: number
  Pietrachiave: string
  RigaSuperiore: string
  RigaCentrale: string
  RigaInferiore: string
  Shard?: Prisma.Pagina_RunaUncheckedCreateNestedManyWithoutShardsInput
  Prim?: Prisma.Pagina_RunaUncheckedCreateNestedManyWithoutPrincipaleInput
  Secon?: Prisma.Pagina_RunaUncheckedCreateNestedManyWithoutSecondariaInput
}

export type Sezione_RunaUpdateInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
  Shard?: Prisma.Pagina_RunaUpdateManyWithoutShardsNestedInput
  Prim?: Prisma.Pagina_RunaUpdateManyWithoutPrincipaleNestedInput
  Secon?: Prisma.Pagina_RunaUpdateManyWithoutSecondariaNestedInput
  Keystone?: Prisma.RunaUpdateOneRequiredWithoutKeystoneNestedInput
  Middle?: Prisma.RunaUpdateOneRequiredWithoutCentraleNestedInput
  Lower?: Prisma.RunaUpdateOneRequiredWithoutUltimaNestedInput
  First?: Prisma.RunaUpdateOneRequiredWithoutPrimaNestedInput
}

export type Sezione_RunaUncheckedUpdateInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
  Pietrachiave?: Prisma.StringFieldUpdateOperationsInput | string
  RigaSuperiore?: Prisma.StringFieldUpdateOperationsInput | string
  RigaCentrale?: Prisma.StringFieldUpdateOperationsInput | string
  RigaInferiore?: Prisma.StringFieldUpdateOperationsInput | string
  Shard?: Prisma.Pagina_RunaUncheckedUpdateManyWithoutShardsNestedInput
  Prim?: Prisma.Pagina_RunaUncheckedUpdateManyWithoutPrincipaleNestedInput
  Secon?: Prisma.Pagina_RunaUncheckedUpdateManyWithoutSecondariaNestedInput
}

export type Sezione_RunaCreateManyInput = {
  Id: number
  Pietrachiave: string
  RigaSuperiore: string
  RigaCentrale: string
  RigaInferiore: string
}

export type Sezione_RunaUpdateManyMutationInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
}

export type Sezione_RunaUncheckedUpdateManyInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
  Pietrachiave?: Prisma.StringFieldUpdateOperationsInput | string
  RigaSuperiore?: Prisma.StringFieldUpdateOperationsInput | string
  RigaCentrale?: Prisma.StringFieldUpdateOperationsInput | string
  RigaInferiore?: Prisma.StringFieldUpdateOperationsInput | string
}

export type Sezione_RunaScalarRelationFilter = {
  is?: Prisma.Sezione_RunaWhereInput
  isNot?: Prisma.Sezione_RunaWhereInput
}

export type Sezione_RunaCountOrderByAggregateInput = {
  Id?: Prisma.SortOrder
  Pietrachiave?: Prisma.SortOrder
  RigaSuperiore?: Prisma.SortOrder
  RigaCentrale?: Prisma.SortOrder
  RigaInferiore?: Prisma.SortOrder
}

export type Sezione_RunaAvgOrderByAggregateInput = {
  Id?: Prisma.SortOrder
}

export type Sezione_RunaMaxOrderByAggregateInput = {
  Id?: Prisma.SortOrder
  Pietrachiave?: Prisma.SortOrder
  RigaSuperiore?: Prisma.SortOrder
  RigaCentrale?: Prisma.SortOrder
  RigaInferiore?: Prisma.SortOrder
}

export type Sezione_RunaMinOrderByAggregateInput = {
  Id?: Prisma.SortOrder
  Pietrachiave?: Prisma.SortOrder
  RigaSuperiore?: Prisma.SortOrder
  RigaCentrale?: Prisma.SortOrder
  RigaInferiore?: Prisma.SortOrder
}

export type Sezione_RunaSumOrderByAggregateInput = {
  Id?: Prisma.SortOrder
}

export type Sezione_RunaListRelationFilter = {
  every?: Prisma.Sezione_RunaWhereInput
  some?: Prisma.Sezione_RunaWhereInput
  none?: Prisma.Sezione_RunaWhereInput
}

export type Sezione_RunaOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type Sezione_RunaCreateNestedOneWithoutShardInput = {
  create?: Prisma.XOR<Prisma.Sezione_RunaCreateWithoutShardInput, Prisma.Sezione_RunaUncheckedCreateWithoutShardInput>
  connectOrCreate?: Prisma.Sezione_RunaCreateOrConnectWithoutShardInput
  connect?: Prisma.Sezione_RunaWhereUniqueInput
}

export type Sezione_RunaCreateNestedOneWithoutPrimInput = {
  create?: Prisma.XOR<Prisma.Sezione_RunaCreateWithoutPrimInput, Prisma.Sezione_RunaUncheckedCreateWithoutPrimInput>
  connectOrCreate?: Prisma.Sezione_RunaCreateOrConnectWithoutPrimInput
  connect?: Prisma.Sezione_RunaWhereUniqueInput
}

export type Sezione_RunaCreateNestedOneWithoutSeconInput = {
  create?: Prisma.XOR<Prisma.Sezione_RunaCreateWithoutSeconInput, Prisma.Sezione_RunaUncheckedCreateWithoutSeconInput>
  connectOrCreate?: Prisma.Sezione_RunaCreateOrConnectWithoutSeconInput
  connect?: Prisma.Sezione_RunaWhereUniqueInput
}

export type Sezione_RunaUpdateOneRequiredWithoutShardNestedInput = {
  create?: Prisma.XOR<Prisma.Sezione_RunaCreateWithoutShardInput, Prisma.Sezione_RunaUncheckedCreateWithoutShardInput>
  connectOrCreate?: Prisma.Sezione_RunaCreateOrConnectWithoutShardInput
  upsert?: Prisma.Sezione_RunaUpsertWithoutShardInput
  connect?: Prisma.Sezione_RunaWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.Sezione_RunaUpdateToOneWithWhereWithoutShardInput, Prisma.Sezione_RunaUpdateWithoutShardInput>, Prisma.Sezione_RunaUncheckedUpdateWithoutShardInput>
}

export type Sezione_RunaUpdateOneRequiredWithoutPrimNestedInput = {
  create?: Prisma.XOR<Prisma.Sezione_RunaCreateWithoutPrimInput, Prisma.Sezione_RunaUncheckedCreateWithoutPrimInput>
  connectOrCreate?: Prisma.Sezione_RunaCreateOrConnectWithoutPrimInput
  upsert?: Prisma.Sezione_RunaUpsertWithoutPrimInput
  connect?: Prisma.Sezione_RunaWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.Sezione_RunaUpdateToOneWithWhereWithoutPrimInput, Prisma.Sezione_RunaUpdateWithoutPrimInput>, Prisma.Sezione_RunaUncheckedUpdateWithoutPrimInput>
}

export type Sezione_RunaUpdateOneRequiredWithoutSeconNestedInput = {
  create?: Prisma.XOR<Prisma.Sezione_RunaCreateWithoutSeconInput, Prisma.Sezione_RunaUncheckedCreateWithoutSeconInput>
  connectOrCreate?: Prisma.Sezione_RunaCreateOrConnectWithoutSeconInput
  upsert?: Prisma.Sezione_RunaUpsertWithoutSeconInput
  connect?: Prisma.Sezione_RunaWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.Sezione_RunaUpdateToOneWithWhereWithoutSeconInput, Prisma.Sezione_RunaUpdateWithoutSeconInput>, Prisma.Sezione_RunaUncheckedUpdateWithoutSeconInput>
}

export type Sezione_RunaCreateNestedManyWithoutKeystoneInput = {
  create?: Prisma.XOR<Prisma.Sezione_RunaCreateWithoutKeystoneInput, Prisma.Sezione_RunaUncheckedCreateWithoutKeystoneInput> | Prisma.Sezione_RunaCreateWithoutKeystoneInput[] | Prisma.Sezione_RunaUncheckedCreateWithoutKeystoneInput[]
  connectOrCreate?: Prisma.Sezione_RunaCreateOrConnectWithoutKeystoneInput | Prisma.Sezione_RunaCreateOrConnectWithoutKeystoneInput[]
  createMany?: Prisma.Sezione_RunaCreateManyKeystoneInputEnvelope
  connect?: Prisma.Sezione_RunaWhereUniqueInput | Prisma.Sezione_RunaWhereUniqueInput[]
}

export type Sezione_RunaCreateNestedManyWithoutMiddleInput = {
  create?: Prisma.XOR<Prisma.Sezione_RunaCreateWithoutMiddleInput, Prisma.Sezione_RunaUncheckedCreateWithoutMiddleInput> | Prisma.Sezione_RunaCreateWithoutMiddleInput[] | Prisma.Sezione_RunaUncheckedCreateWithoutMiddleInput[]
  connectOrCreate?: Prisma.Sezione_RunaCreateOrConnectWithoutMiddleInput | Prisma.Sezione_RunaCreateOrConnectWithoutMiddleInput[]
  createMany?: Prisma.Sezione_RunaCreateManyMiddleInputEnvelope
  connect?: Prisma.Sezione_RunaWhereUniqueInput | Prisma.Sezione_RunaWhereUniqueInput[]
}

export type Sezione_RunaCreateNestedManyWithoutLowerInput = {
  create?: Prisma.XOR<Prisma.Sezione_RunaCreateWithoutLowerInput, Prisma.Sezione_RunaUncheckedCreateWithoutLowerInput> | Prisma.Sezione_RunaCreateWithoutLowerInput[] | Prisma.Sezione_RunaUncheckedCreateWithoutLowerInput[]
  connectOrCreate?: Prisma.Sezione_RunaCreateOrConnectWithoutLowerInput | Prisma.Sezione_RunaCreateOrConnectWithoutLowerInput[]
  createMany?: Prisma.Sezione_RunaCreateManyLowerInputEnvelope
  connect?: Prisma.Sezione_RunaWhereUniqueInput | Prisma.Sezione_RunaWhereUniqueInput[]
}

export type Sezione_RunaCreateNestedManyWithoutFirstInput = {
  create?: Prisma.XOR<Prisma.Sezione_RunaCreateWithoutFirstInput, Prisma.Sezione_RunaUncheckedCreateWithoutFirstInput> | Prisma.Sezione_RunaCreateWithoutFirstInput[] | Prisma.Sezione_RunaUncheckedCreateWithoutFirstInput[]
  connectOrCreate?: Prisma.Sezione_RunaCreateOrConnectWithoutFirstInput | Prisma.Sezione_RunaCreateOrConnectWithoutFirstInput[]
  createMany?: Prisma.Sezione_RunaCreateManyFirstInputEnvelope
  connect?: Prisma.Sezione_RunaWhereUniqueInput | Prisma.Sezione_RunaWhereUniqueInput[]
}

export type Sezione_RunaUncheckedCreateNestedManyWithoutKeystoneInput = {
  create?: Prisma.XOR<Prisma.Sezione_RunaCreateWithoutKeystoneInput, Prisma.Sezione_RunaUncheckedCreateWithoutKeystoneInput> | Prisma.Sezione_RunaCreateWithoutKeystoneInput[] | Prisma.Sezione_RunaUncheckedCreateWithoutKeystoneInput[]
  connectOrCreate?: Prisma.Sezione_RunaCreateOrConnectWithoutKeystoneInput | Prisma.Sezione_RunaCreateOrConnectWithoutKeystoneInput[]
  createMany?: Prisma.Sezione_RunaCreateManyKeystoneInputEnvelope
  connect?: Prisma.Sezione_RunaWhereUniqueInput | Prisma.Sezione_RunaWhereUniqueInput[]
}

export type Sezione_RunaUncheckedCreateNestedManyWithoutMiddleInput = {
  create?: Prisma.XOR<Prisma.Sezione_RunaCreateWithoutMiddleInput, Prisma.Sezione_RunaUncheckedCreateWithoutMiddleInput> | Prisma.Sezione_RunaCreateWithoutMiddleInput[] | Prisma.Sezione_RunaUncheckedCreateWithoutMiddleInput[]
  connectOrCreate?: Prisma.Sezione_RunaCreateOrConnectWithoutMiddleInput | Prisma.Sezione_RunaCreateOrConnectWithoutMiddleInput[]
  createMany?: Prisma.Sezione_RunaCreateManyMiddleInputEnvelope
  connect?: Prisma.Sezione_RunaWhereUniqueInput | Prisma.Sezione_RunaWhereUniqueInput[]
}

export type Sezione_RunaUncheckedCreateNestedManyWithoutLowerInput = {
  create?: Prisma.XOR<Prisma.Sezione_RunaCreateWithoutLowerInput, Prisma.Sezione_RunaUncheckedCreateWithoutLowerInput> | Prisma.Sezione_RunaCreateWithoutLowerInput[] | Prisma.Sezione_RunaUncheckedCreateWithoutLowerInput[]
  connectOrCreate?: Prisma.Sezione_RunaCreateOrConnectWithoutLowerInput | Prisma.Sezione_RunaCreateOrConnectWithoutLowerInput[]
  createMany?: Prisma.Sezione_RunaCreateManyLowerInputEnvelope
  connect?: Prisma.Sezione_RunaWhereUniqueInput | Prisma.Sezione_RunaWhereUniqueInput[]
}

export type Sezione_RunaUncheckedCreateNestedManyWithoutFirstInput = {
  create?: Prisma.XOR<Prisma.Sezione_RunaCreateWithoutFirstInput, Prisma.Sezione_RunaUncheckedCreateWithoutFirstInput> | Prisma.Sezione_RunaCreateWithoutFirstInput[] | Prisma.Sezione_RunaUncheckedCreateWithoutFirstInput[]
  connectOrCreate?: Prisma.Sezione_RunaCreateOrConnectWithoutFirstInput | Prisma.Sezione_RunaCreateOrConnectWithoutFirstInput[]
  createMany?: Prisma.Sezione_RunaCreateManyFirstInputEnvelope
  connect?: Prisma.Sezione_RunaWhereUniqueInput | Prisma.Sezione_RunaWhereUniqueInput[]
}

export type Sezione_RunaUpdateManyWithoutKeystoneNestedInput = {
  create?: Prisma.XOR<Prisma.Sezione_RunaCreateWithoutKeystoneInput, Prisma.Sezione_RunaUncheckedCreateWithoutKeystoneInput> | Prisma.Sezione_RunaCreateWithoutKeystoneInput[] | Prisma.Sezione_RunaUncheckedCreateWithoutKeystoneInput[]
  connectOrCreate?: Prisma.Sezione_RunaCreateOrConnectWithoutKeystoneInput | Prisma.Sezione_RunaCreateOrConnectWithoutKeystoneInput[]
  upsert?: Prisma.Sezione_RunaUpsertWithWhereUniqueWithoutKeystoneInput | Prisma.Sezione_RunaUpsertWithWhereUniqueWithoutKeystoneInput[]
  createMany?: Prisma.Sezione_RunaCreateManyKeystoneInputEnvelope
  set?: Prisma.Sezione_RunaWhereUniqueInput | Prisma.Sezione_RunaWhereUniqueInput[]
  disconnect?: Prisma.Sezione_RunaWhereUniqueInput | Prisma.Sezione_RunaWhereUniqueInput[]
  delete?: Prisma.Sezione_RunaWhereUniqueInput | Prisma.Sezione_RunaWhereUniqueInput[]
  connect?: Prisma.Sezione_RunaWhereUniqueInput | Prisma.Sezione_RunaWhereUniqueInput[]
  update?: Prisma.Sezione_RunaUpdateWithWhereUniqueWithoutKeystoneInput | Prisma.Sezione_RunaUpdateWithWhereUniqueWithoutKeystoneInput[]
  updateMany?: Prisma.Sezione_RunaUpdateManyWithWhereWithoutKeystoneInput | Prisma.Sezione_RunaUpdateManyWithWhereWithoutKeystoneInput[]
  deleteMany?: Prisma.Sezione_RunaScalarWhereInput | Prisma.Sezione_RunaScalarWhereInput[]
}

export type Sezione_RunaUpdateManyWithoutMiddleNestedInput = {
  create?: Prisma.XOR<Prisma.Sezione_RunaCreateWithoutMiddleInput, Prisma.Sezione_RunaUncheckedCreateWithoutMiddleInput> | Prisma.Sezione_RunaCreateWithoutMiddleInput[] | Prisma.Sezione_RunaUncheckedCreateWithoutMiddleInput[]
  connectOrCreate?: Prisma.Sezione_RunaCreateOrConnectWithoutMiddleInput | Prisma.Sezione_RunaCreateOrConnectWithoutMiddleInput[]
  upsert?: Prisma.Sezione_RunaUpsertWithWhereUniqueWithoutMiddleInput | Prisma.Sezione_RunaUpsertWithWhereUniqueWithoutMiddleInput[]
  createMany?: Prisma.Sezione_RunaCreateManyMiddleInputEnvelope
  set?: Prisma.Sezione_RunaWhereUniqueInput | Prisma.Sezione_RunaWhereUniqueInput[]
  disconnect?: Prisma.Sezione_RunaWhereUniqueInput | Prisma.Sezione_RunaWhereUniqueInput[]
  delete?: Prisma.Sezione_RunaWhereUniqueInput | Prisma.Sezione_RunaWhereUniqueInput[]
  connect?: Prisma.Sezione_RunaWhereUniqueInput | Prisma.Sezione_RunaWhereUniqueInput[]
  update?: Prisma.Sezione_RunaUpdateWithWhereUniqueWithoutMiddleInput | Prisma.Sezione_RunaUpdateWithWhereUniqueWithoutMiddleInput[]
  updateMany?: Prisma.Sezione_RunaUpdateManyWithWhereWithoutMiddleInput | Prisma.Sezione_RunaUpdateManyWithWhereWithoutMiddleInput[]
  deleteMany?: Prisma.Sezione_RunaScalarWhereInput | Prisma.Sezione_RunaScalarWhereInput[]
}

export type Sezione_RunaUpdateManyWithoutLowerNestedInput = {
  create?: Prisma.XOR<Prisma.Sezione_RunaCreateWithoutLowerInput, Prisma.Sezione_RunaUncheckedCreateWithoutLowerInput> | Prisma.Sezione_RunaCreateWithoutLowerInput[] | Prisma.Sezione_RunaUncheckedCreateWithoutLowerInput[]
  connectOrCreate?: Prisma.Sezione_RunaCreateOrConnectWithoutLowerInput | Prisma.Sezione_RunaCreateOrConnectWithoutLowerInput[]
  upsert?: Prisma.Sezione_RunaUpsertWithWhereUniqueWithoutLowerInput | Prisma.Sezione_RunaUpsertWithWhereUniqueWithoutLowerInput[]
  createMany?: Prisma.Sezione_RunaCreateManyLowerInputEnvelope
  set?: Prisma.Sezione_RunaWhereUniqueInput | Prisma.Sezione_RunaWhereUniqueInput[]
  disconnect?: Prisma.Sezione_RunaWhereUniqueInput | Prisma.Sezione_RunaWhereUniqueInput[]
  delete?: Prisma.Sezione_RunaWhereUniqueInput | Prisma.Sezione_RunaWhereUniqueInput[]
  connect?: Prisma.Sezione_RunaWhereUniqueInput | Prisma.Sezione_RunaWhereUniqueInput[]
  update?: Prisma.Sezione_RunaUpdateWithWhereUniqueWithoutLowerInput | Prisma.Sezione_RunaUpdateWithWhereUniqueWithoutLowerInput[]
  updateMany?: Prisma.Sezione_RunaUpdateManyWithWhereWithoutLowerInput | Prisma.Sezione_RunaUpdateManyWithWhereWithoutLowerInput[]
  deleteMany?: Prisma.Sezione_RunaScalarWhereInput | Prisma.Sezione_RunaScalarWhereInput[]
}

export type Sezione_RunaUpdateManyWithoutFirstNestedInput = {
  create?: Prisma.XOR<Prisma.Sezione_RunaCreateWithoutFirstInput, Prisma.Sezione_RunaUncheckedCreateWithoutFirstInput> | Prisma.Sezione_RunaCreateWithoutFirstInput[] | Prisma.Sezione_RunaUncheckedCreateWithoutFirstInput[]
  connectOrCreate?: Prisma.Sezione_RunaCreateOrConnectWithoutFirstInput | Prisma.Sezione_RunaCreateOrConnectWithoutFirstInput[]
  upsert?: Prisma.Sezione_RunaUpsertWithWhereUniqueWithoutFirstInput | Prisma.Sezione_RunaUpsertWithWhereUniqueWithoutFirstInput[]
  createMany?: Prisma.Sezione_RunaCreateManyFirstInputEnvelope
  set?: Prisma.Sezione_RunaWhereUniqueInput | Prisma.Sezione_RunaWhereUniqueInput[]
  disconnect?: Prisma.Sezione_RunaWhereUniqueInput | Prisma.Sezione_RunaWhereUniqueInput[]
  delete?: Prisma.Sezione_RunaWhereUniqueInput | Prisma.Sezione_RunaWhereUniqueInput[]
  connect?: Prisma.Sezione_RunaWhereUniqueInput | Prisma.Sezione_RunaWhereUniqueInput[]
  update?: Prisma.Sezione_RunaUpdateWithWhereUniqueWithoutFirstInput | Prisma.Sezione_RunaUpdateWithWhereUniqueWithoutFirstInput[]
  updateMany?: Prisma.Sezione_RunaUpdateManyWithWhereWithoutFirstInput | Prisma.Sezione_RunaUpdateManyWithWhereWithoutFirstInput[]
  deleteMany?: Prisma.Sezione_RunaScalarWhereInput | Prisma.Sezione_RunaScalarWhereInput[]
}

export type Sezione_RunaUncheckedUpdateManyWithoutKeystoneNestedInput = {
  create?: Prisma.XOR<Prisma.Sezione_RunaCreateWithoutKeystoneInput, Prisma.Sezione_RunaUncheckedCreateWithoutKeystoneInput> | Prisma.Sezione_RunaCreateWithoutKeystoneInput[] | Prisma.Sezione_RunaUncheckedCreateWithoutKeystoneInput[]
  connectOrCreate?: Prisma.Sezione_RunaCreateOrConnectWithoutKeystoneInput | Prisma.Sezione_RunaCreateOrConnectWithoutKeystoneInput[]
  upsert?: Prisma.Sezione_RunaUpsertWithWhereUniqueWithoutKeystoneInput | Prisma.Sezione_RunaUpsertWithWhereUniqueWithoutKeystoneInput[]
  createMany?: Prisma.Sezione_RunaCreateManyKeystoneInputEnvelope
  set?: Prisma.Sezione_RunaWhereUniqueInput | Prisma.Sezione_RunaWhereUniqueInput[]
  disconnect?: Prisma.Sezione_RunaWhereUniqueInput | Prisma.Sezione_RunaWhereUniqueInput[]
  delete?: Prisma.Sezione_RunaWhereUniqueInput | Prisma.Sezione_RunaWhereUniqueInput[]
  connect?: Prisma.Sezione_RunaWhereUniqueInput | Prisma.Sezione_RunaWhereUniqueInput[]
  update?: Prisma.Sezione_RunaUpdateWithWhereUniqueWithoutKeystoneInput | Prisma.Sezione_RunaUpdateWithWhereUniqueWithoutKeystoneInput[]
  updateMany?: Prisma.Sezione_RunaUpdateManyWithWhereWithoutKeystoneInput | Prisma.Sezione_RunaUpdateManyWithWhereWithoutKeystoneInput[]
  deleteMany?: Prisma.Sezione_RunaScalarWhereInput | Prisma.Sezione_RunaScalarWhereInput[]
}

export type Sezione_RunaUncheckedUpdateManyWithoutMiddleNestedInput = {
  create?: Prisma.XOR<Prisma.Sezione_RunaCreateWithoutMiddleInput, Prisma.Sezione_RunaUncheckedCreateWithoutMiddleInput> | Prisma.Sezione_RunaCreateWithoutMiddleInput[] | Prisma.Sezione_RunaUncheckedCreateWithoutMiddleInput[]
  connectOrCreate?: Prisma.Sezione_RunaCreateOrConnectWithoutMiddleInput | Prisma.Sezione_RunaCreateOrConnectWithoutMiddleInput[]
  upsert?: Prisma.Sezione_RunaUpsertWithWhereUniqueWithoutMiddleInput | Prisma.Sezione_RunaUpsertWithWhereUniqueWithoutMiddleInput[]
  createMany?: Prisma.Sezione_RunaCreateManyMiddleInputEnvelope
  set?: Prisma.Sezione_RunaWhereUniqueInput | Prisma.Sezione_RunaWhereUniqueInput[]
  disconnect?: Prisma.Sezione_RunaWhereUniqueInput | Prisma.Sezione_RunaWhereUniqueInput[]
  delete?: Prisma.Sezione_RunaWhereUniqueInput | Prisma.Sezione_RunaWhereUniqueInput[]
  connect?: Prisma.Sezione_RunaWhereUniqueInput | Prisma.Sezione_RunaWhereUniqueInput[]
  update?: Prisma.Sezione_RunaUpdateWithWhereUniqueWithoutMiddleInput | Prisma.Sezione_RunaUpdateWithWhereUniqueWithoutMiddleInput[]
  updateMany?: Prisma.Sezione_RunaUpdateManyWithWhereWithoutMiddleInput | Prisma.Sezione_RunaUpdateManyWithWhereWithoutMiddleInput[]
  deleteMany?: Prisma.Sezione_RunaScalarWhereInput | Prisma.Sezione_RunaScalarWhereInput[]
}

export type Sezione_RunaUncheckedUpdateManyWithoutLowerNestedInput = {
  create?: Prisma.XOR<Prisma.Sezione_RunaCreateWithoutLowerInput, Prisma.Sezione_RunaUncheckedCreateWithoutLowerInput> | Prisma.Sezione_RunaCreateWithoutLowerInput[] | Prisma.Sezione_RunaUncheckedCreateWithoutLowerInput[]
  connectOrCreate?: Prisma.Sezione_RunaCreateOrConnectWithoutLowerInput | Prisma.Sezione_RunaCreateOrConnectWithoutLowerInput[]
  upsert?: Prisma.Sezione_RunaUpsertWithWhereUniqueWithoutLowerInput | Prisma.Sezione_RunaUpsertWithWhereUniqueWithoutLowerInput[]
  createMany?: Prisma.Sezione_RunaCreateManyLowerInputEnvelope
  set?: Prisma.Sezione_RunaWhereUniqueInput | Prisma.Sezione_RunaWhereUniqueInput[]
  disconnect?: Prisma.Sezione_RunaWhereUniqueInput | Prisma.Sezione_RunaWhereUniqueInput[]
  delete?: Prisma.Sezione_RunaWhereUniqueInput | Prisma.Sezione_RunaWhereUniqueInput[]
  connect?: Prisma.Sezione_RunaWhereUniqueInput | Prisma.Sezione_RunaWhereUniqueInput[]
  update?: Prisma.Sezione_RunaUpdateWithWhereUniqueWithoutLowerInput | Prisma.Sezione_RunaUpdateWithWhereUniqueWithoutLowerInput[]
  updateMany?: Prisma.Sezione_RunaUpdateManyWithWhereWithoutLowerInput | Prisma.Sezione_RunaUpdateManyWithWhereWithoutLowerInput[]
  deleteMany?: Prisma.Sezione_RunaScalarWhereInput | Prisma.Sezione_RunaScalarWhereInput[]
}

export type Sezione_RunaUncheckedUpdateManyWithoutFirstNestedInput = {
  create?: Prisma.XOR<Prisma.Sezione_RunaCreateWithoutFirstInput, Prisma.Sezione_RunaUncheckedCreateWithoutFirstInput> | Prisma.Sezione_RunaCreateWithoutFirstInput[] | Prisma.Sezione_RunaUncheckedCreateWithoutFirstInput[]
  connectOrCreate?: Prisma.Sezione_RunaCreateOrConnectWithoutFirstInput | Prisma.Sezione_RunaCreateOrConnectWithoutFirstInput[]
  upsert?: Prisma.Sezione_RunaUpsertWithWhereUniqueWithoutFirstInput | Prisma.Sezione_RunaUpsertWithWhereUniqueWithoutFirstInput[]
  createMany?: Prisma.Sezione_RunaCreateManyFirstInputEnvelope
  set?: Prisma.Sezione_RunaWhereUniqueInput | Prisma.Sezione_RunaWhereUniqueInput[]
  disconnect?: Prisma.Sezione_RunaWhereUniqueInput | Prisma.Sezione_RunaWhereUniqueInput[]
  delete?: Prisma.Sezione_RunaWhereUniqueInput | Prisma.Sezione_RunaWhereUniqueInput[]
  connect?: Prisma.Sezione_RunaWhereUniqueInput | Prisma.Sezione_RunaWhereUniqueInput[]
  update?: Prisma.Sezione_RunaUpdateWithWhereUniqueWithoutFirstInput | Prisma.Sezione_RunaUpdateWithWhereUniqueWithoutFirstInput[]
  updateMany?: Prisma.Sezione_RunaUpdateManyWithWhereWithoutFirstInput | Prisma.Sezione_RunaUpdateManyWithWhereWithoutFirstInput[]
  deleteMany?: Prisma.Sezione_RunaScalarWhereInput | Prisma.Sezione_RunaScalarWhereInput[]
}

export type Sezione_RunaCreateWithoutShardInput = {
  Id: number
  Prim?: Prisma.Pagina_RunaCreateNestedManyWithoutPrincipaleInput
  Secon?: Prisma.Pagina_RunaCreateNestedManyWithoutSecondariaInput
  Keystone: Prisma.RunaCreateNestedOneWithoutKeystoneInput
  Middle: Prisma.RunaCreateNestedOneWithoutCentraleInput
  Lower: Prisma.RunaCreateNestedOneWithoutUltimaInput
  First: Prisma.RunaCreateNestedOneWithoutPrimaInput
}

export type Sezione_RunaUncheckedCreateWithoutShardInput = {
  Id: number
  Pietrachiave: string
  RigaSuperiore: string
  RigaCentrale: string
  RigaInferiore: string
  Prim?: Prisma.Pagina_RunaUncheckedCreateNestedManyWithoutPrincipaleInput
  Secon?: Prisma.Pagina_RunaUncheckedCreateNestedManyWithoutSecondariaInput
}

export type Sezione_RunaCreateOrConnectWithoutShardInput = {
  where: Prisma.Sezione_RunaWhereUniqueInput
  create: Prisma.XOR<Prisma.Sezione_RunaCreateWithoutShardInput, Prisma.Sezione_RunaUncheckedCreateWithoutShardInput>
}

export type Sezione_RunaCreateWithoutPrimInput = {
  Id: number
  Shard?: Prisma.Pagina_RunaCreateNestedManyWithoutShardsInput
  Secon?: Prisma.Pagina_RunaCreateNestedManyWithoutSecondariaInput
  Keystone: Prisma.RunaCreateNestedOneWithoutKeystoneInput
  Middle: Prisma.RunaCreateNestedOneWithoutCentraleInput
  Lower: Prisma.RunaCreateNestedOneWithoutUltimaInput
  First: Prisma.RunaCreateNestedOneWithoutPrimaInput
}

export type Sezione_RunaUncheckedCreateWithoutPrimInput = {
  Id: number
  Pietrachiave: string
  RigaSuperiore: string
  RigaCentrale: string
  RigaInferiore: string
  Shard?: Prisma.Pagina_RunaUncheckedCreateNestedManyWithoutShardsInput
  Secon?: Prisma.Pagina_RunaUncheckedCreateNestedManyWithoutSecondariaInput
}

export type Sezione_RunaCreateOrConnectWithoutPrimInput = {
  where: Prisma.Sezione_RunaWhereUniqueInput
  create: Prisma.XOR<Prisma.Sezione_RunaCreateWithoutPrimInput, Prisma.Sezione_RunaUncheckedCreateWithoutPrimInput>
}

export type Sezione_RunaCreateWithoutSeconInput = {
  Id: number
  Shard?: Prisma.Pagina_RunaCreateNestedManyWithoutShardsInput
  Prim?: Prisma.Pagina_RunaCreateNestedManyWithoutPrincipaleInput
  Keystone: Prisma.RunaCreateNestedOneWithoutKeystoneInput
  Middle: Prisma.RunaCreateNestedOneWithoutCentraleInput
  Lower: Prisma.RunaCreateNestedOneWithoutUltimaInput
  First: Prisma.RunaCreateNestedOneWithoutPrimaInput
}

export type Sezione_RunaUncheckedCreateWithoutSeconInput = {
  Id: number
  Pietrachiave: string
  RigaSuperiore: string
  RigaCentrale: string
  RigaInferiore: string
  Shard?: Prisma.Pagina_RunaUncheckedCreateNestedManyWithoutShardsInput
  Prim?: Prisma.Pagina_RunaUncheckedCreateNestedManyWithoutPrincipaleInput
}

export type Sezione_RunaCreateOrConnectWithoutSeconInput = {
  where: Prisma.Sezione_RunaWhereUniqueInput
  create: Prisma.XOR<Prisma.Sezione_RunaCreateWithoutSeconInput, Prisma.Sezione_RunaUncheckedCreateWithoutSeconInput>
}

export type Sezione_RunaUpsertWithoutShardInput = {
  update: Prisma.XOR<Prisma.Sezione_RunaUpdateWithoutShardInput, Prisma.Sezione_RunaUncheckedUpdateWithoutShardInput>
  create: Prisma.XOR<Prisma.Sezione_RunaCreateWithoutShardInput, Prisma.Sezione_RunaUncheckedCreateWithoutShardInput>
  where?: Prisma.Sezione_RunaWhereInput
}

export type Sezione_RunaUpdateToOneWithWhereWithoutShardInput = {
  where?: Prisma.Sezione_RunaWhereInput
  data: Prisma.XOR<Prisma.Sezione_RunaUpdateWithoutShardInput, Prisma.Sezione_RunaUncheckedUpdateWithoutShardInput>
}

export type Sezione_RunaUpdateWithoutShardInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
  Prim?: Prisma.Pagina_RunaUpdateManyWithoutPrincipaleNestedInput
  Secon?: Prisma.Pagina_RunaUpdateManyWithoutSecondariaNestedInput
  Keystone?: Prisma.RunaUpdateOneRequiredWithoutKeystoneNestedInput
  Middle?: Prisma.RunaUpdateOneRequiredWithoutCentraleNestedInput
  Lower?: Prisma.RunaUpdateOneRequiredWithoutUltimaNestedInput
  First?: Prisma.RunaUpdateOneRequiredWithoutPrimaNestedInput
}

export type Sezione_RunaUncheckedUpdateWithoutShardInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
  Pietrachiave?: Prisma.StringFieldUpdateOperationsInput | string
  RigaSuperiore?: Prisma.StringFieldUpdateOperationsInput | string
  RigaCentrale?: Prisma.StringFieldUpdateOperationsInput | string
  RigaInferiore?: Prisma.StringFieldUpdateOperationsInput | string
  Prim?: Prisma.Pagina_RunaUncheckedUpdateManyWithoutPrincipaleNestedInput
  Secon?: Prisma.Pagina_RunaUncheckedUpdateManyWithoutSecondariaNestedInput
}

export type Sezione_RunaUpsertWithoutPrimInput = {
  update: Prisma.XOR<Prisma.Sezione_RunaUpdateWithoutPrimInput, Prisma.Sezione_RunaUncheckedUpdateWithoutPrimInput>
  create: Prisma.XOR<Prisma.Sezione_RunaCreateWithoutPrimInput, Prisma.Sezione_RunaUncheckedCreateWithoutPrimInput>
  where?: Prisma.Sezione_RunaWhereInput
}

export type Sezione_RunaUpdateToOneWithWhereWithoutPrimInput = {
  where?: Prisma.Sezione_RunaWhereInput
  data: Prisma.XOR<Prisma.Sezione_RunaUpdateWithoutPrimInput, Prisma.Sezione_RunaUncheckedUpdateWithoutPrimInput>
}

export type Sezione_RunaUpdateWithoutPrimInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
  Shard?: Prisma.Pagina_RunaUpdateManyWithoutShardsNestedInput
  Secon?: Prisma.Pagina_RunaUpdateManyWithoutSecondariaNestedInput
  Keystone?: Prisma.RunaUpdateOneRequiredWithoutKeystoneNestedInput
  Middle?: Prisma.RunaUpdateOneRequiredWithoutCentraleNestedInput
  Lower?: Prisma.RunaUpdateOneRequiredWithoutUltimaNestedInput
  First?: Prisma.RunaUpdateOneRequiredWithoutPrimaNestedInput
}

export type Sezione_RunaUncheckedUpdateWithoutPrimInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
  Pietrachiave?: Prisma.StringFieldUpdateOperationsInput | string
  RigaSuperiore?: Prisma.StringFieldUpdateOperationsInput | string
  RigaCentrale?: Prisma.StringFieldUpdateOperationsInput | string
  RigaInferiore?: Prisma.StringFieldUpdateOperationsInput | string
  Shard?: Prisma.Pagina_RunaUncheckedUpdateManyWithoutShardsNestedInput
  Secon?: Prisma.Pagina_RunaUncheckedUpdateManyWithoutSecondariaNestedInput
}

export type Sezione_RunaUpsertWithoutSeconInput = {
  update: Prisma.XOR<Prisma.Sezione_RunaUpdateWithoutSeconInput, Prisma.Sezione_RunaUncheckedUpdateWithoutSeconInput>
  create: Prisma.XOR<Prisma.Sezione_RunaCreateWithoutSeconInput, Prisma.Sezione_RunaUncheckedCreateWithoutSeconInput>
  where?: Prisma.Sezione_RunaWhereInput
}

export type Sezione_RunaUpdateToOneWithWhereWithoutSeconInput = {
  where?: Prisma.Sezione_RunaWhereInput
  data: Prisma.XOR<Prisma.Sezione_RunaUpdateWithoutSeconInput, Prisma.Sezione_RunaUncheckedUpdateWithoutSeconInput>
}

export type Sezione_RunaUpdateWithoutSeconInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
  Shard?: Prisma.Pagina_RunaUpdateManyWithoutShardsNestedInput
  Prim?: Prisma.Pagina_RunaUpdateManyWithoutPrincipaleNestedInput
  Keystone?: Prisma.RunaUpdateOneRequiredWithoutKeystoneNestedInput
  Middle?: Prisma.RunaUpdateOneRequiredWithoutCentraleNestedInput
  Lower?: Prisma.RunaUpdateOneRequiredWithoutUltimaNestedInput
  First?: Prisma.RunaUpdateOneRequiredWithoutPrimaNestedInput
}

export type Sezione_RunaUncheckedUpdateWithoutSeconInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
  Pietrachiave?: Prisma.StringFieldUpdateOperationsInput | string
  RigaSuperiore?: Prisma.StringFieldUpdateOperationsInput | string
  RigaCentrale?: Prisma.StringFieldUpdateOperationsInput | string
  RigaInferiore?: Prisma.StringFieldUpdateOperationsInput | string
  Shard?: Prisma.Pagina_RunaUncheckedUpdateManyWithoutShardsNestedInput
  Prim?: Prisma.Pagina_RunaUncheckedUpdateManyWithoutPrincipaleNestedInput
}

export type Sezione_RunaCreateWithoutKeystoneInput = {
  Id: number
  Shard?: Prisma.Pagina_RunaCreateNestedManyWithoutShardsInput
  Prim?: Prisma.Pagina_RunaCreateNestedManyWithoutPrincipaleInput
  Secon?: Prisma.Pagina_RunaCreateNestedManyWithoutSecondariaInput
  Middle: Prisma.RunaCreateNestedOneWithoutCentraleInput
  Lower: Prisma.RunaCreateNestedOneWithoutUltimaInput
  First: Prisma.RunaCreateNestedOneWithoutPrimaInput
}

export type Sezione_RunaUncheckedCreateWithoutKeystoneInput = {
  Id: number
  RigaSuperiore: string
  RigaCentrale: string
  RigaInferiore: string
  Shard?: Prisma.Pagina_RunaUncheckedCreateNestedManyWithoutShardsInput
  Prim?: Prisma.Pagina_RunaUncheckedCreateNestedManyWithoutPrincipaleInput
  Secon?: Prisma.Pagina_RunaUncheckedCreateNestedManyWithoutSecondariaInput
}

export type Sezione_RunaCreateOrConnectWithoutKeystoneInput = {
  where: Prisma.Sezione_RunaWhereUniqueInput
  create: Prisma.XOR<Prisma.Sezione_RunaCreateWithoutKeystoneInput, Prisma.Sezione_RunaUncheckedCreateWithoutKeystoneInput>
}

export type Sezione_RunaCreateManyKeystoneInputEnvelope = {
  data: Prisma.Sezione_RunaCreateManyKeystoneInput | Prisma.Sezione_RunaCreateManyKeystoneInput[]
  skipDuplicates?: boolean
}

export type Sezione_RunaCreateWithoutMiddleInput = {
  Id: number
  Shard?: Prisma.Pagina_RunaCreateNestedManyWithoutShardsInput
  Prim?: Prisma.Pagina_RunaCreateNestedManyWithoutPrincipaleInput
  Secon?: Prisma.Pagina_RunaCreateNestedManyWithoutSecondariaInput
  Keystone: Prisma.RunaCreateNestedOneWithoutKeystoneInput
  Lower: Prisma.RunaCreateNestedOneWithoutUltimaInput
  First: Prisma.RunaCreateNestedOneWithoutPrimaInput
}

export type Sezione_RunaUncheckedCreateWithoutMiddleInput = {
  Id: number
  Pietrachiave: string
  RigaSuperiore: string
  RigaInferiore: string
  Shard?: Prisma.Pagina_RunaUncheckedCreateNestedManyWithoutShardsInput
  Prim?: Prisma.Pagina_RunaUncheckedCreateNestedManyWithoutPrincipaleInput
  Secon?: Prisma.Pagina_RunaUncheckedCreateNestedManyWithoutSecondariaInput
}

export type Sezione_RunaCreateOrConnectWithoutMiddleInput = {
  where: Prisma.Sezione_RunaWhereUniqueInput
  create: Prisma.XOR<Prisma.Sezione_RunaCreateWithoutMiddleInput, Prisma.Sezione_RunaUncheckedCreateWithoutMiddleInput>
}

export type Sezione_RunaCreateManyMiddleInputEnvelope = {
  data: Prisma.Sezione_RunaCreateManyMiddleInput | Prisma.Sezione_RunaCreateManyMiddleInput[]
  skipDuplicates?: boolean
}

export type Sezione_RunaCreateWithoutLowerInput = {
  Id: number
  Shard?: Prisma.Pagina_RunaCreateNestedManyWithoutShardsInput
  Prim?: Prisma.Pagina_RunaCreateNestedManyWithoutPrincipaleInput
  Secon?: Prisma.Pagina_RunaCreateNestedManyWithoutSecondariaInput
  Keystone: Prisma.RunaCreateNestedOneWithoutKeystoneInput
  Middle: Prisma.RunaCreateNestedOneWithoutCentraleInput
  First: Prisma.RunaCreateNestedOneWithoutPrimaInput
}

export type Sezione_RunaUncheckedCreateWithoutLowerInput = {
  Id: number
  Pietrachiave: string
  RigaSuperiore: string
  RigaCentrale: string
  Shard?: Prisma.Pagina_RunaUncheckedCreateNestedManyWithoutShardsInput
  Prim?: Prisma.Pagina_RunaUncheckedCreateNestedManyWithoutPrincipaleInput
  Secon?: Prisma.Pagina_RunaUncheckedCreateNestedManyWithoutSecondariaInput
}

export type Sezione_RunaCreateOrConnectWithoutLowerInput = {
  where: Prisma.Sezione_RunaWhereUniqueInput
  create: Prisma.XOR<Prisma.Sezione_RunaCreateWithoutLowerInput, Prisma.Sezione_RunaUncheckedCreateWithoutLowerInput>
}

export type Sezione_RunaCreateManyLowerInputEnvelope = {
  data: Prisma.Sezione_RunaCreateManyLowerInput | Prisma.Sezione_RunaCreateManyLowerInput[]
  skipDuplicates?: boolean
}

export type Sezione_RunaCreateWithoutFirstInput = {
  Id: number
  Shard?: Prisma.Pagina_RunaCreateNestedManyWithoutShardsInput
  Prim?: Prisma.Pagina_RunaCreateNestedManyWithoutPrincipaleInput
  Secon?: Prisma.Pagina_RunaCreateNestedManyWithoutSecondariaInput
  Keystone: Prisma.RunaCreateNestedOneWithoutKeystoneInput
  Middle: Prisma.RunaCreateNestedOneWithoutCentraleInput
  Lower: Prisma.RunaCreateNestedOneWithoutUltimaInput
}

export type Sezione_RunaUncheckedCreateWithoutFirstInput = {
  Id: number
  Pietrachiave: string
  RigaCentrale: string
  RigaInferiore: string
  Shard?: Prisma.Pagina_RunaUncheckedCreateNestedManyWithoutShardsInput
  Prim?: Prisma.Pagina_RunaUncheckedCreateNestedManyWithoutPrincipaleInput
  Secon?: Prisma.Pagina_RunaUncheckedCreateNestedManyWithoutSecondariaInput
}

export type Sezione_RunaCreateOrConnectWithoutFirstInput = {
  where: Prisma.Sezione_RunaWhereUniqueInput
  create: Prisma.XOR<Prisma.Sezione_RunaCreateWithoutFirstInput, Prisma.Sezione_RunaUncheckedCreateWithoutFirstInput>
}

export type Sezione_RunaCreateManyFirstInputEnvelope = {
  data: Prisma.Sezione_RunaCreateManyFirstInput | Prisma.Sezione_RunaCreateManyFirstInput[]
  skipDuplicates?: boolean
}

export type Sezione_RunaUpsertWithWhereUniqueWithoutKeystoneInput = {
  where: Prisma.Sezione_RunaWhereUniqueInput
  update: Prisma.XOR<Prisma.Sezione_RunaUpdateWithoutKeystoneInput, Prisma.Sezione_RunaUncheckedUpdateWithoutKeystoneInput>
  create: Prisma.XOR<Prisma.Sezione_RunaCreateWithoutKeystoneInput, Prisma.Sezione_RunaUncheckedCreateWithoutKeystoneInput>
}

export type Sezione_RunaUpdateWithWhereUniqueWithoutKeystoneInput = {
  where: Prisma.Sezione_RunaWhereUniqueInput
  data: Prisma.XOR<Prisma.Sezione_RunaUpdateWithoutKeystoneInput, Prisma.Sezione_RunaUncheckedUpdateWithoutKeystoneInput>
}

export type Sezione_RunaUpdateManyWithWhereWithoutKeystoneInput = {
  where: Prisma.Sezione_RunaScalarWhereInput
  data: Prisma.XOR<Prisma.Sezione_RunaUpdateManyMutationInput, Prisma.Sezione_RunaUncheckedUpdateManyWithoutKeystoneInput>
}

export type Sezione_RunaScalarWhereInput = {
  AND?: Prisma.Sezione_RunaScalarWhereInput | Prisma.Sezione_RunaScalarWhereInput[]
  OR?: Prisma.Sezione_RunaScalarWhereInput[]
  NOT?: Prisma.Sezione_RunaScalarWhereInput | Prisma.Sezione_RunaScalarWhereInput[]
  Id?: Prisma.IntFilter<"Sezione_Runa"> | number
  Pietrachiave?: Prisma.StringFilter<"Sezione_Runa"> | string
  RigaSuperiore?: Prisma.StringFilter<"Sezione_Runa"> | string
  RigaCentrale?: Prisma.StringFilter<"Sezione_Runa"> | string
  RigaInferiore?: Prisma.StringFilter<"Sezione_Runa"> | string
}

export type Sezione_RunaUpsertWithWhereUniqueWithoutMiddleInput = {
  where: Prisma.Sezione_RunaWhereUniqueInput
  update: Prisma.XOR<Prisma.Sezione_RunaUpdateWithoutMiddleInput, Prisma.Sezione_RunaUncheckedUpdateWithoutMiddleInput>
  create: Prisma.XOR<Prisma.Sezione_RunaCreateWithoutMiddleInput, Prisma.Sezione_RunaUncheckedCreateWithoutMiddleInput>
}

export type Sezione_RunaUpdateWithWhereUniqueWithoutMiddleInput = {
  where: Prisma.Sezione_RunaWhereUniqueInput
  data: Prisma.XOR<Prisma.Sezione_RunaUpdateWithoutMiddleInput, Prisma.Sezione_RunaUncheckedUpdateWithoutMiddleInput>
}

export type Sezione_RunaUpdateManyWithWhereWithoutMiddleInput = {
  where: Prisma.Sezione_RunaScalarWhereInput
  data: Prisma.XOR<Prisma.Sezione_RunaUpdateManyMutationInput, Prisma.Sezione_RunaUncheckedUpdateManyWithoutMiddleInput>
}

export type Sezione_RunaUpsertWithWhereUniqueWithoutLowerInput = {
  where: Prisma.Sezione_RunaWhereUniqueInput
  update: Prisma.XOR<Prisma.Sezione_RunaUpdateWithoutLowerInput, Prisma.Sezione_RunaUncheckedUpdateWithoutLowerInput>
  create: Prisma.XOR<Prisma.Sezione_RunaCreateWithoutLowerInput, Prisma.Sezione_RunaUncheckedCreateWithoutLowerInput>
}

export type Sezione_RunaUpdateWithWhereUniqueWithoutLowerInput = {
  where: Prisma.Sezione_RunaWhereUniqueInput
  data: Prisma.XOR<Prisma.Sezione_RunaUpdateWithoutLowerInput, Prisma.Sezione_RunaUncheckedUpdateWithoutLowerInput>
}

export type Sezione_RunaUpdateManyWithWhereWithoutLowerInput = {
  where: Prisma.Sezione_RunaScalarWhereInput
  data: Prisma.XOR<Prisma.Sezione_RunaUpdateManyMutationInput, Prisma.Sezione_RunaUncheckedUpdateManyWithoutLowerInput>
}

export type Sezione_RunaUpsertWithWhereUniqueWithoutFirstInput = {
  where: Prisma.Sezione_RunaWhereUniqueInput
  update: Prisma.XOR<Prisma.Sezione_RunaUpdateWithoutFirstInput, Prisma.Sezione_RunaUncheckedUpdateWithoutFirstInput>
  create: Prisma.XOR<Prisma.Sezione_RunaCreateWithoutFirstInput, Prisma.Sezione_RunaUncheckedCreateWithoutFirstInput>
}

export type Sezione_RunaUpdateWithWhereUniqueWithoutFirstInput = {
  where: Prisma.Sezione_RunaWhereUniqueInput
  data: Prisma.XOR<Prisma.Sezione_RunaUpdateWithoutFirstInput, Prisma.Sezione_RunaUncheckedUpdateWithoutFirstInput>
}

export type Sezione_RunaUpdateManyWithWhereWithoutFirstInput = {
  where: Prisma.Sezione_RunaScalarWhereInput
  data: Prisma.XOR<Prisma.Sezione_RunaUpdateManyMutationInput, Prisma.Sezione_RunaUncheckedUpdateManyWithoutFirstInput>
}

export type Sezione_RunaCreateManyKeystoneInput = {
  Id: number
  RigaSuperiore: string
  RigaCentrale: string
  RigaInferiore: string
}

export type Sezione_RunaCreateManyMiddleInput = {
  Id: number
  Pietrachiave: string
  RigaSuperiore: string
  RigaInferiore: string
}

export type Sezione_RunaCreateManyLowerInput = {
  Id: number
  Pietrachiave: string
  RigaSuperiore: string
  RigaCentrale: string
}

export type Sezione_RunaCreateManyFirstInput = {
  Id: number
  Pietrachiave: string
  RigaCentrale: string
  RigaInferiore: string
}

export type Sezione_RunaUpdateWithoutKeystoneInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
  Shard?: Prisma.Pagina_RunaUpdateManyWithoutShardsNestedInput
  Prim?: Prisma.Pagina_RunaUpdateManyWithoutPrincipaleNestedInput
  Secon?: Prisma.Pagina_RunaUpdateManyWithoutSecondariaNestedInput
  Middle?: Prisma.RunaUpdateOneRequiredWithoutCentraleNestedInput
  Lower?: Prisma.RunaUpdateOneRequiredWithoutUltimaNestedInput
  First?: Prisma.RunaUpdateOneRequiredWithoutPrimaNestedInput
}

export type Sezione_RunaUncheckedUpdateWithoutKeystoneInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
  RigaSuperiore?: Prisma.StringFieldUpdateOperationsInput | string
  RigaCentrale?: Prisma.StringFieldUpdateOperationsInput | string
  RigaInferiore?: Prisma.StringFieldUpdateOperationsInput | string
  Shard?: Prisma.Pagina_RunaUncheckedUpdateManyWithoutShardsNestedInput
  Prim?: Prisma.Pagina_RunaUncheckedUpdateManyWithoutPrincipaleNestedInput
  Secon?: Prisma.Pagina_RunaUncheckedUpdateManyWithoutSecondariaNestedInput
}

export type Sezione_RunaUncheckedUpdateManyWithoutKeystoneInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
  RigaSuperiore?: Prisma.StringFieldUpdateOperationsInput | string
  RigaCentrale?: Prisma.StringFieldUpdateOperationsInput | string
  RigaInferiore?: Prisma.StringFieldUpdateOperationsInput | string
}

export type Sezione_RunaUpdateWithoutMiddleInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
  Shard?: Prisma.Pagina_RunaUpdateManyWithoutShardsNestedInput
  Prim?: Prisma.Pagina_RunaUpdateManyWithoutPrincipaleNestedInput
  Secon?: Prisma.Pagina_RunaUpdateManyWithoutSecondariaNestedInput
  Keystone?: Prisma.RunaUpdateOneRequiredWithoutKeystoneNestedInput
  Lower?: Prisma.RunaUpdateOneRequiredWithoutUltimaNestedInput
  First?: Prisma.RunaUpdateOneRequiredWithoutPrimaNestedInput
}

export type Sezione_RunaUncheckedUpdateWithoutMiddleInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
  Pietrachiave?: Prisma.StringFieldUpdateOperationsInput | string
  RigaSuperiore?: Prisma.StringFieldUpdateOperationsInput | string
  RigaInferiore?: Prisma.StringFieldUpdateOperationsInput | string
  Shard?: Prisma.Pagina_RunaUncheckedUpdateManyWithoutShardsNestedInput
  Prim?: Prisma.Pagina_RunaUncheckedUpdateManyWithoutPrincipaleNestedInput
  Secon?: Prisma.Pagina_RunaUncheckedUpdateManyWithoutSecondariaNestedInput
}

export type Sezione_RunaUncheckedUpdateManyWithoutMiddleInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
  Pietrachiave?: Prisma.StringFieldUpdateOperationsInput | string
  RigaSuperiore?: Prisma.StringFieldUpdateOperationsInput | string
  RigaInferiore?: Prisma.StringFieldUpdateOperationsInput | string
}

export type Sezione_RunaUpdateWithoutLowerInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
  Shard?: Prisma.Pagina_RunaUpdateManyWithoutShardsNestedInput
  Prim?: Prisma.Pagina_RunaUpdateManyWithoutPrincipaleNestedInput
  Secon?: Prisma.Pagina_RunaUpdateManyWithoutSecondariaNestedInput
  Keystone?: Prisma.RunaUpdateOneRequiredWithoutKeystoneNestedInput
  Middle?: Prisma.RunaUpdateOneRequiredWithoutCentraleNestedInput
  First?: Prisma.RunaUpdateOneRequiredWithoutPrimaNestedInput
}

export type Sezione_RunaUncheckedUpdateWithoutLowerInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
  Pietrachiave?: Prisma.StringFieldUpdateOperationsInput | string
  RigaSuperiore?: Prisma.StringFieldUpdateOperationsInput | string
  RigaCentrale?: Prisma.StringFieldUpdateOperationsInput | string
  Shard?: Prisma.Pagina_RunaUncheckedUpdateManyWithoutShardsNestedInput
  Prim?: Prisma.Pagina_RunaUncheckedUpdateManyWithoutPrincipaleNestedInput
  Secon?: Prisma.Pagina_RunaUncheckedUpdateManyWithoutSecondariaNestedInput
}

export type Sezione_RunaUncheckedUpdateManyWithoutLowerInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
  Pietrachiave?: Prisma.StringFieldUpdateOperationsInput | string
  RigaSuperiore?: Prisma.StringFieldUpdateOperationsInput | string
  RigaCentrale?: Prisma.StringFieldUpdateOperationsInput | string
}

export type Sezione_RunaUpdateWithoutFirstInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
  Shard?: Prisma.Pagina_RunaUpdateManyWithoutShardsNestedInput
  Prim?: Prisma.Pagina_RunaUpdateManyWithoutPrincipaleNestedInput
  Secon?: Prisma.Pagina_RunaUpdateManyWithoutSecondariaNestedInput
  Keystone?: Prisma.RunaUpdateOneRequiredWithoutKeystoneNestedInput
  Middle?: Prisma.RunaUpdateOneRequiredWithoutCentraleNestedInput
  Lower?: Prisma.RunaUpdateOneRequiredWithoutUltimaNestedInput
}

export type Sezione_RunaUncheckedUpdateWithoutFirstInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
  Pietrachiave?: Prisma.StringFieldUpdateOperationsInput | string
  RigaCentrale?: Prisma.StringFieldUpdateOperationsInput | string
  RigaInferiore?: Prisma.StringFieldUpdateOperationsInput | string
  Shard?: Prisma.Pagina_RunaUncheckedUpdateManyWithoutShardsNestedInput
  Prim?: Prisma.Pagina_RunaUncheckedUpdateManyWithoutPrincipaleNestedInput
  Secon?: Prisma.Pagina_RunaUncheckedUpdateManyWithoutSecondariaNestedInput
}

export type Sezione_RunaUncheckedUpdateManyWithoutFirstInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
  Pietrachiave?: Prisma.StringFieldUpdateOperationsInput | string
  RigaCentrale?: Prisma.StringFieldUpdateOperationsInput | string
  RigaInferiore?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type Sezione_RunaCountOutputType
 */

export type Sezione_RunaCountOutputType = {
  Shard: number
  Prim: number
  Secon: number
}

export type Sezione_RunaCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Shard?: boolean | Sezione_RunaCountOutputTypeCountShardArgs
  Prim?: boolean | Sezione_RunaCountOutputTypeCountPrimArgs
  Secon?: boolean | Sezione_RunaCountOutputTypeCountSeconArgs
}

/**
 * Sezione_RunaCountOutputType without action
 */
export type Sezione_RunaCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sezione_RunaCountOutputType
   */
  select?: Prisma.Sezione_RunaCountOutputTypeSelect<ExtArgs> | null
}

/**
 * Sezione_RunaCountOutputType without action
 */
export type Sezione_RunaCountOutputTypeCountShardArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.Pagina_RunaWhereInput
}

/**
 * Sezione_RunaCountOutputType without action
 */
export type Sezione_RunaCountOutputTypeCountPrimArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.Pagina_RunaWhereInput
}

/**
 * Sezione_RunaCountOutputType without action
 */
export type Sezione_RunaCountOutputTypeCountSeconArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.Pagina_RunaWhereInput
}


export type Sezione_RunaSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  Id?: boolean
  Pietrachiave?: boolean
  RigaSuperiore?: boolean
  RigaCentrale?: boolean
  RigaInferiore?: boolean
  Shard?: boolean | Prisma.Sezione_Runa$ShardArgs<ExtArgs>
  Prim?: boolean | Prisma.Sezione_Runa$PrimArgs<ExtArgs>
  Secon?: boolean | Prisma.Sezione_Runa$SeconArgs<ExtArgs>
  Keystone?: boolean | Prisma.RunaDefaultArgs<ExtArgs>
  Middle?: boolean | Prisma.RunaDefaultArgs<ExtArgs>
  Lower?: boolean | Prisma.RunaDefaultArgs<ExtArgs>
  First?: boolean | Prisma.RunaDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.Sezione_RunaCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["sezione_Runa"]>

export type Sezione_RunaSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  Id?: boolean
  Pietrachiave?: boolean
  RigaSuperiore?: boolean
  RigaCentrale?: boolean
  RigaInferiore?: boolean
  Keystone?: boolean | Prisma.RunaDefaultArgs<ExtArgs>
  Middle?: boolean | Prisma.RunaDefaultArgs<ExtArgs>
  Lower?: boolean | Prisma.RunaDefaultArgs<ExtArgs>
  First?: boolean | Prisma.RunaDefaultArgs<ExtArgs>
}, ExtArgs["result"]["sezione_Runa"]>

export type Sezione_RunaSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  Id?: boolean
  Pietrachiave?: boolean
  RigaSuperiore?: boolean
  RigaCentrale?: boolean
  RigaInferiore?: boolean
  Keystone?: boolean | Prisma.RunaDefaultArgs<ExtArgs>
  Middle?: boolean | Prisma.RunaDefaultArgs<ExtArgs>
  Lower?: boolean | Prisma.RunaDefaultArgs<ExtArgs>
  First?: boolean | Prisma.RunaDefaultArgs<ExtArgs>
}, ExtArgs["result"]["sezione_Runa"]>

export type Sezione_RunaSelectScalar = {
  Id?: boolean
  Pietrachiave?: boolean
  RigaSuperiore?: boolean
  RigaCentrale?: boolean
  RigaInferiore?: boolean
}

export type Sezione_RunaOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"Id" | "Pietrachiave" | "RigaSuperiore" | "RigaCentrale" | "RigaInferiore", ExtArgs["result"]["sezione_Runa"]>
export type Sezione_RunaInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Shard?: boolean | Prisma.Sezione_Runa$ShardArgs<ExtArgs>
  Prim?: boolean | Prisma.Sezione_Runa$PrimArgs<ExtArgs>
  Secon?: boolean | Prisma.Sezione_Runa$SeconArgs<ExtArgs>
  Keystone?: boolean | Prisma.RunaDefaultArgs<ExtArgs>
  Middle?: boolean | Prisma.RunaDefaultArgs<ExtArgs>
  Lower?: boolean | Prisma.RunaDefaultArgs<ExtArgs>
  First?: boolean | Prisma.RunaDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.Sezione_RunaCountOutputTypeDefaultArgs<ExtArgs>
}
export type Sezione_RunaIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Keystone?: boolean | Prisma.RunaDefaultArgs<ExtArgs>
  Middle?: boolean | Prisma.RunaDefaultArgs<ExtArgs>
  Lower?: boolean | Prisma.RunaDefaultArgs<ExtArgs>
  First?: boolean | Prisma.RunaDefaultArgs<ExtArgs>
}
export type Sezione_RunaIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Keystone?: boolean | Prisma.RunaDefaultArgs<ExtArgs>
  Middle?: boolean | Prisma.RunaDefaultArgs<ExtArgs>
  Lower?: boolean | Prisma.RunaDefaultArgs<ExtArgs>
  First?: boolean | Prisma.RunaDefaultArgs<ExtArgs>
}

export type $Sezione_RunaPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Sezione_Runa"
  objects: {
    Shard: Prisma.$Pagina_RunaPayload<ExtArgs>[]
    Prim: Prisma.$Pagina_RunaPayload<ExtArgs>[]
    Secon: Prisma.$Pagina_RunaPayload<ExtArgs>[]
    Keystone: Prisma.$RunaPayload<ExtArgs>
    Middle: Prisma.$RunaPayload<ExtArgs>
    Lower: Prisma.$RunaPayload<ExtArgs>
    First: Prisma.$RunaPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    Id: number
    Pietrachiave: string
    RigaSuperiore: string
    RigaCentrale: string
    RigaInferiore: string
  }, ExtArgs["result"]["sezione_Runa"]>
  composites: {}
}

export type Sezione_RunaGetPayload<S extends boolean | null | undefined | Sezione_RunaDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$Sezione_RunaPayload, S>

export type Sezione_RunaCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<Sezione_RunaFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Sezione_RunaCountAggregateInputType | true
  }

export interface Sezione_RunaDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Sezione_Runa'], meta: { name: 'Sezione_Runa' } }
  /**
   * Find zero or one Sezione_Runa that matches the filter.
   * @param {Sezione_RunaFindUniqueArgs} args - Arguments to find a Sezione_Runa
   * @example
   * // Get one Sezione_Runa
   * const sezione_Runa = await prisma.sezione_Runa.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends Sezione_RunaFindUniqueArgs>(args: Prisma.SelectSubset<T, Sezione_RunaFindUniqueArgs<ExtArgs>>): Prisma.Prisma__Sezione_RunaClient<runtime.Types.Result.GetResult<Prisma.$Sezione_RunaPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Sezione_Runa that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {Sezione_RunaFindUniqueOrThrowArgs} args - Arguments to find a Sezione_Runa
   * @example
   * // Get one Sezione_Runa
   * const sezione_Runa = await prisma.sezione_Runa.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends Sezione_RunaFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, Sezione_RunaFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__Sezione_RunaClient<runtime.Types.Result.GetResult<Prisma.$Sezione_RunaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Sezione_Runa that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Sezione_RunaFindFirstArgs} args - Arguments to find a Sezione_Runa
   * @example
   * // Get one Sezione_Runa
   * const sezione_Runa = await prisma.sezione_Runa.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends Sezione_RunaFindFirstArgs>(args?: Prisma.SelectSubset<T, Sezione_RunaFindFirstArgs<ExtArgs>>): Prisma.Prisma__Sezione_RunaClient<runtime.Types.Result.GetResult<Prisma.$Sezione_RunaPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Sezione_Runa that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Sezione_RunaFindFirstOrThrowArgs} args - Arguments to find a Sezione_Runa
   * @example
   * // Get one Sezione_Runa
   * const sezione_Runa = await prisma.sezione_Runa.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends Sezione_RunaFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, Sezione_RunaFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__Sezione_RunaClient<runtime.Types.Result.GetResult<Prisma.$Sezione_RunaPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Sezione_Runas that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Sezione_RunaFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Sezione_Runas
   * const sezione_Runas = await prisma.sezione_Runa.findMany()
   * 
   * // Get first 10 Sezione_Runas
   * const sezione_Runas = await prisma.sezione_Runa.findMany({ take: 10 })
   * 
   * // Only select the `Id`
   * const sezione_RunaWithIdOnly = await prisma.sezione_Runa.findMany({ select: { Id: true } })
   * 
   */
  findMany<T extends Sezione_RunaFindManyArgs>(args?: Prisma.SelectSubset<T, Sezione_RunaFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Sezione_RunaPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Sezione_Runa.
   * @param {Sezione_RunaCreateArgs} args - Arguments to create a Sezione_Runa.
   * @example
   * // Create one Sezione_Runa
   * const Sezione_Runa = await prisma.sezione_Runa.create({
   *   data: {
   *     // ... data to create a Sezione_Runa
   *   }
   * })
   * 
   */
  create<T extends Sezione_RunaCreateArgs>(args: Prisma.SelectSubset<T, Sezione_RunaCreateArgs<ExtArgs>>): Prisma.Prisma__Sezione_RunaClient<runtime.Types.Result.GetResult<Prisma.$Sezione_RunaPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Sezione_Runas.
   * @param {Sezione_RunaCreateManyArgs} args - Arguments to create many Sezione_Runas.
   * @example
   * // Create many Sezione_Runas
   * const sezione_Runa = await prisma.sezione_Runa.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends Sezione_RunaCreateManyArgs>(args?: Prisma.SelectSubset<T, Sezione_RunaCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Sezione_Runas and returns the data saved in the database.
   * @param {Sezione_RunaCreateManyAndReturnArgs} args - Arguments to create many Sezione_Runas.
   * @example
   * // Create many Sezione_Runas
   * const sezione_Runa = await prisma.sezione_Runa.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Sezione_Runas and only return the `Id`
   * const sezione_RunaWithIdOnly = await prisma.sezione_Runa.createManyAndReturn({
   *   select: { Id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends Sezione_RunaCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, Sezione_RunaCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Sezione_RunaPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Sezione_Runa.
   * @param {Sezione_RunaDeleteArgs} args - Arguments to delete one Sezione_Runa.
   * @example
   * // Delete one Sezione_Runa
   * const Sezione_Runa = await prisma.sezione_Runa.delete({
   *   where: {
   *     // ... filter to delete one Sezione_Runa
   *   }
   * })
   * 
   */
  delete<T extends Sezione_RunaDeleteArgs>(args: Prisma.SelectSubset<T, Sezione_RunaDeleteArgs<ExtArgs>>): Prisma.Prisma__Sezione_RunaClient<runtime.Types.Result.GetResult<Prisma.$Sezione_RunaPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Sezione_Runa.
   * @param {Sezione_RunaUpdateArgs} args - Arguments to update one Sezione_Runa.
   * @example
   * // Update one Sezione_Runa
   * const sezione_Runa = await prisma.sezione_Runa.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends Sezione_RunaUpdateArgs>(args: Prisma.SelectSubset<T, Sezione_RunaUpdateArgs<ExtArgs>>): Prisma.Prisma__Sezione_RunaClient<runtime.Types.Result.GetResult<Prisma.$Sezione_RunaPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Sezione_Runas.
   * @param {Sezione_RunaDeleteManyArgs} args - Arguments to filter Sezione_Runas to delete.
   * @example
   * // Delete a few Sezione_Runas
   * const { count } = await prisma.sezione_Runa.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends Sezione_RunaDeleteManyArgs>(args?: Prisma.SelectSubset<T, Sezione_RunaDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Sezione_Runas.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Sezione_RunaUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Sezione_Runas
   * const sezione_Runa = await prisma.sezione_Runa.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends Sezione_RunaUpdateManyArgs>(args: Prisma.SelectSubset<T, Sezione_RunaUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Sezione_Runas and returns the data updated in the database.
   * @param {Sezione_RunaUpdateManyAndReturnArgs} args - Arguments to update many Sezione_Runas.
   * @example
   * // Update many Sezione_Runas
   * const sezione_Runa = await prisma.sezione_Runa.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Sezione_Runas and only return the `Id`
   * const sezione_RunaWithIdOnly = await prisma.sezione_Runa.updateManyAndReturn({
   *   select: { Id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends Sezione_RunaUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, Sezione_RunaUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Sezione_RunaPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Sezione_Runa.
   * @param {Sezione_RunaUpsertArgs} args - Arguments to update or create a Sezione_Runa.
   * @example
   * // Update or create a Sezione_Runa
   * const sezione_Runa = await prisma.sezione_Runa.upsert({
   *   create: {
   *     // ... data to create a Sezione_Runa
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Sezione_Runa we want to update
   *   }
   * })
   */
  upsert<T extends Sezione_RunaUpsertArgs>(args: Prisma.SelectSubset<T, Sezione_RunaUpsertArgs<ExtArgs>>): Prisma.Prisma__Sezione_RunaClient<runtime.Types.Result.GetResult<Prisma.$Sezione_RunaPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Sezione_Runas.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Sezione_RunaCountArgs} args - Arguments to filter Sezione_Runas to count.
   * @example
   * // Count the number of Sezione_Runas
   * const count = await prisma.sezione_Runa.count({
   *   where: {
   *     // ... the filter for the Sezione_Runas we want to count
   *   }
   * })
  **/
  count<T extends Sezione_RunaCountArgs>(
    args?: Prisma.Subset<T, Sezione_RunaCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Sezione_RunaCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Sezione_Runa.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Sezione_RunaAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Sezione_RunaAggregateArgs>(args: Prisma.Subset<T, Sezione_RunaAggregateArgs>): Prisma.PrismaPromise<GetSezione_RunaAggregateType<T>>

  /**
   * Group by Sezione_Runa.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Sezione_RunaGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends Sezione_RunaGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: Sezione_RunaGroupByArgs['orderBy'] }
      : { orderBy?: Sezione_RunaGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, Sezione_RunaGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSezione_RunaGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Sezione_Runa model
 */
readonly fields: Sezione_RunaFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Sezione_Runa.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__Sezione_RunaClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  Shard<T extends Prisma.Sezione_Runa$ShardArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Sezione_Runa$ShardArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Pagina_RunaPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  Prim<T extends Prisma.Sezione_Runa$PrimArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Sezione_Runa$PrimArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Pagina_RunaPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  Secon<T extends Prisma.Sezione_Runa$SeconArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Sezione_Runa$SeconArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Pagina_RunaPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  Keystone<T extends Prisma.RunaDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.RunaDefaultArgs<ExtArgs>>): Prisma.Prisma__RunaClient<runtime.Types.Result.GetResult<Prisma.$RunaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  Middle<T extends Prisma.RunaDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.RunaDefaultArgs<ExtArgs>>): Prisma.Prisma__RunaClient<runtime.Types.Result.GetResult<Prisma.$RunaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  Lower<T extends Prisma.RunaDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.RunaDefaultArgs<ExtArgs>>): Prisma.Prisma__RunaClient<runtime.Types.Result.GetResult<Prisma.$RunaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  First<T extends Prisma.RunaDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.RunaDefaultArgs<ExtArgs>>): Prisma.Prisma__RunaClient<runtime.Types.Result.GetResult<Prisma.$RunaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Sezione_Runa model
 */
export interface Sezione_RunaFieldRefs {
  readonly Id: Prisma.FieldRef<"Sezione_Runa", 'Int'>
  readonly Pietrachiave: Prisma.FieldRef<"Sezione_Runa", 'String'>
  readonly RigaSuperiore: Prisma.FieldRef<"Sezione_Runa", 'String'>
  readonly RigaCentrale: Prisma.FieldRef<"Sezione_Runa", 'String'>
  readonly RigaInferiore: Prisma.FieldRef<"Sezione_Runa", 'String'>
}
    

// Custom InputTypes
/**
 * Sezione_Runa findUnique
 */
export type Sezione_RunaFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sezione_Runa
   */
  select?: Prisma.Sezione_RunaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sezione_Runa
   */
  omit?: Prisma.Sezione_RunaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Sezione_RunaInclude<ExtArgs> | null
  /**
   * Filter, which Sezione_Runa to fetch.
   */
  where: Prisma.Sezione_RunaWhereUniqueInput
}

/**
 * Sezione_Runa findUniqueOrThrow
 */
export type Sezione_RunaFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sezione_Runa
   */
  select?: Prisma.Sezione_RunaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sezione_Runa
   */
  omit?: Prisma.Sezione_RunaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Sezione_RunaInclude<ExtArgs> | null
  /**
   * Filter, which Sezione_Runa to fetch.
   */
  where: Prisma.Sezione_RunaWhereUniqueInput
}

/**
 * Sezione_Runa findFirst
 */
export type Sezione_RunaFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sezione_Runa
   */
  select?: Prisma.Sezione_RunaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sezione_Runa
   */
  omit?: Prisma.Sezione_RunaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Sezione_RunaInclude<ExtArgs> | null
  /**
   * Filter, which Sezione_Runa to fetch.
   */
  where?: Prisma.Sezione_RunaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Sezione_Runas to fetch.
   */
  orderBy?: Prisma.Sezione_RunaOrderByWithRelationInput | Prisma.Sezione_RunaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Sezione_Runas.
   */
  cursor?: Prisma.Sezione_RunaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Sezione_Runas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Sezione_Runas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Sezione_Runas.
   */
  distinct?: Prisma.Sezione_RunaScalarFieldEnum | Prisma.Sezione_RunaScalarFieldEnum[]
}

/**
 * Sezione_Runa findFirstOrThrow
 */
export type Sezione_RunaFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sezione_Runa
   */
  select?: Prisma.Sezione_RunaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sezione_Runa
   */
  omit?: Prisma.Sezione_RunaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Sezione_RunaInclude<ExtArgs> | null
  /**
   * Filter, which Sezione_Runa to fetch.
   */
  where?: Prisma.Sezione_RunaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Sezione_Runas to fetch.
   */
  orderBy?: Prisma.Sezione_RunaOrderByWithRelationInput | Prisma.Sezione_RunaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Sezione_Runas.
   */
  cursor?: Prisma.Sezione_RunaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Sezione_Runas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Sezione_Runas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Sezione_Runas.
   */
  distinct?: Prisma.Sezione_RunaScalarFieldEnum | Prisma.Sezione_RunaScalarFieldEnum[]
}

/**
 * Sezione_Runa findMany
 */
export type Sezione_RunaFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sezione_Runa
   */
  select?: Prisma.Sezione_RunaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sezione_Runa
   */
  omit?: Prisma.Sezione_RunaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Sezione_RunaInclude<ExtArgs> | null
  /**
   * Filter, which Sezione_Runas to fetch.
   */
  where?: Prisma.Sezione_RunaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Sezione_Runas to fetch.
   */
  orderBy?: Prisma.Sezione_RunaOrderByWithRelationInput | Prisma.Sezione_RunaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Sezione_Runas.
   */
  cursor?: Prisma.Sezione_RunaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Sezione_Runas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Sezione_Runas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Sezione_Runas.
   */
  distinct?: Prisma.Sezione_RunaScalarFieldEnum | Prisma.Sezione_RunaScalarFieldEnum[]
}

/**
 * Sezione_Runa create
 */
export type Sezione_RunaCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sezione_Runa
   */
  select?: Prisma.Sezione_RunaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sezione_Runa
   */
  omit?: Prisma.Sezione_RunaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Sezione_RunaInclude<ExtArgs> | null
  /**
   * The data needed to create a Sezione_Runa.
   */
  data: Prisma.XOR<Prisma.Sezione_RunaCreateInput, Prisma.Sezione_RunaUncheckedCreateInput>
}

/**
 * Sezione_Runa createMany
 */
export type Sezione_RunaCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Sezione_Runas.
   */
  data: Prisma.Sezione_RunaCreateManyInput | Prisma.Sezione_RunaCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Sezione_Runa createManyAndReturn
 */
export type Sezione_RunaCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sezione_Runa
   */
  select?: Prisma.Sezione_RunaSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Sezione_Runa
   */
  omit?: Prisma.Sezione_RunaOmit<ExtArgs> | null
  /**
   * The data used to create many Sezione_Runas.
   */
  data: Prisma.Sezione_RunaCreateManyInput | Prisma.Sezione_RunaCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Sezione_RunaIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Sezione_Runa update
 */
export type Sezione_RunaUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sezione_Runa
   */
  select?: Prisma.Sezione_RunaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sezione_Runa
   */
  omit?: Prisma.Sezione_RunaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Sezione_RunaInclude<ExtArgs> | null
  /**
   * The data needed to update a Sezione_Runa.
   */
  data: Prisma.XOR<Prisma.Sezione_RunaUpdateInput, Prisma.Sezione_RunaUncheckedUpdateInput>
  /**
   * Choose, which Sezione_Runa to update.
   */
  where: Prisma.Sezione_RunaWhereUniqueInput
}

/**
 * Sezione_Runa updateMany
 */
export type Sezione_RunaUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Sezione_Runas.
   */
  data: Prisma.XOR<Prisma.Sezione_RunaUpdateManyMutationInput, Prisma.Sezione_RunaUncheckedUpdateManyInput>
  /**
   * Filter which Sezione_Runas to update
   */
  where?: Prisma.Sezione_RunaWhereInput
  /**
   * Limit how many Sezione_Runas to update.
   */
  limit?: number
}

/**
 * Sezione_Runa updateManyAndReturn
 */
export type Sezione_RunaUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sezione_Runa
   */
  select?: Prisma.Sezione_RunaSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Sezione_Runa
   */
  omit?: Prisma.Sezione_RunaOmit<ExtArgs> | null
  /**
   * The data used to update Sezione_Runas.
   */
  data: Prisma.XOR<Prisma.Sezione_RunaUpdateManyMutationInput, Prisma.Sezione_RunaUncheckedUpdateManyInput>
  /**
   * Filter which Sezione_Runas to update
   */
  where?: Prisma.Sezione_RunaWhereInput
  /**
   * Limit how many Sezione_Runas to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Sezione_RunaIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Sezione_Runa upsert
 */
export type Sezione_RunaUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sezione_Runa
   */
  select?: Prisma.Sezione_RunaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sezione_Runa
   */
  omit?: Prisma.Sezione_RunaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Sezione_RunaInclude<ExtArgs> | null
  /**
   * The filter to search for the Sezione_Runa to update in case it exists.
   */
  where: Prisma.Sezione_RunaWhereUniqueInput
  /**
   * In case the Sezione_Runa found by the `where` argument doesn't exist, create a new Sezione_Runa with this data.
   */
  create: Prisma.XOR<Prisma.Sezione_RunaCreateInput, Prisma.Sezione_RunaUncheckedCreateInput>
  /**
   * In case the Sezione_Runa was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.Sezione_RunaUpdateInput, Prisma.Sezione_RunaUncheckedUpdateInput>
}

/**
 * Sezione_Runa delete
 */
export type Sezione_RunaDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sezione_Runa
   */
  select?: Prisma.Sezione_RunaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sezione_Runa
   */
  omit?: Prisma.Sezione_RunaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Sezione_RunaInclude<ExtArgs> | null
  /**
   * Filter which Sezione_Runa to delete.
   */
  where: Prisma.Sezione_RunaWhereUniqueInput
}

/**
 * Sezione_Runa deleteMany
 */
export type Sezione_RunaDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Sezione_Runas to delete
   */
  where?: Prisma.Sezione_RunaWhereInput
  /**
   * Limit how many Sezione_Runas to delete.
   */
  limit?: number
}

/**
 * Sezione_Runa.Shard
 */
export type Sezione_Runa$ShardArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pagina_Runa
   */
  select?: Prisma.Pagina_RunaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Pagina_Runa
   */
  omit?: Prisma.Pagina_RunaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Pagina_RunaInclude<ExtArgs> | null
  where?: Prisma.Pagina_RunaWhereInput
  orderBy?: Prisma.Pagina_RunaOrderByWithRelationInput | Prisma.Pagina_RunaOrderByWithRelationInput[]
  cursor?: Prisma.Pagina_RunaWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Pagina_RunaScalarFieldEnum | Prisma.Pagina_RunaScalarFieldEnum[]
}

/**
 * Sezione_Runa.Prim
 */
export type Sezione_Runa$PrimArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pagina_Runa
   */
  select?: Prisma.Pagina_RunaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Pagina_Runa
   */
  omit?: Prisma.Pagina_RunaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Pagina_RunaInclude<ExtArgs> | null
  where?: Prisma.Pagina_RunaWhereInput
  orderBy?: Prisma.Pagina_RunaOrderByWithRelationInput | Prisma.Pagina_RunaOrderByWithRelationInput[]
  cursor?: Prisma.Pagina_RunaWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Pagina_RunaScalarFieldEnum | Prisma.Pagina_RunaScalarFieldEnum[]
}

/**
 * Sezione_Runa.Secon
 */
export type Sezione_Runa$SeconArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pagina_Runa
   */
  select?: Prisma.Pagina_RunaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Pagina_Runa
   */
  omit?: Prisma.Pagina_RunaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Pagina_RunaInclude<ExtArgs> | null
  where?: Prisma.Pagina_RunaWhereInput
  orderBy?: Prisma.Pagina_RunaOrderByWithRelationInput | Prisma.Pagina_RunaOrderByWithRelationInput[]
  cursor?: Prisma.Pagina_RunaWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Pagina_RunaScalarFieldEnum | Prisma.Pagina_RunaScalarFieldEnum[]
}

/**
 * Sezione_Runa without action
 */
export type Sezione_RunaDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sezione_Runa
   */
  select?: Prisma.Sezione_RunaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sezione_Runa
   */
  omit?: Prisma.Sezione_RunaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Sezione_RunaInclude<ExtArgs> | null
}
